# CBT Configuration Overrides for peer custody count backfill to December 3, 2025
#
# Dec 3, 2025 00:00:00 UTC = 1764684000 (Unix timestamp)

models:
  env:
    MODELS_SCRIPTS_PATH: "../xatu-cbt/models/scripts"
    GENESIS_TIME: "1606824023"  # Mainnet genesis timestamp
    EXTERNAL_MODEL_MIN_TIMESTAMP: "1764684000"  # Dec 3, 2025 - for peer custody backfill

  overrides:
    # External dependencies for peer custody count
    libp2p_handle_metadata:
      config:
        limits:
          min: 1764684000  # Dec 3, 2025
    libp2p_synthetic_heartbeat:
      config:
        limits:
          min: 1764684000  # Dec 3, 2025

    # Peer custody count transformation models
    int_peer_custody_count_by_epoch:
      config:
        limits:
          min: 1764684000  # Dec 3, 2025
    fct_peer_custody_count_by_epoch:
      config:
        limits:
          min: 1764684000  # Dec 3, 2025
    fct_peer_custody_count_hourly:
      config:
        limits:
          min: 1764684000  # Dec 3, 2025
    fct_peer_custody_count_daily:
      config:
        limits:
          min: 1764684000  # Dec 3, 2025
    fct_peer_custody_count_weekly:
      config:
        limits:
          min: 1764684000  # Dec 3, 2025
    fct_peer_custody_count_monthly:
      config:
        limits:
          min: 1764684000  # Dec 3, 2025
