volumes:
  cbt-config:

services:
  cbt-redis:
    image: redis:7-alpine
    container_name: cbt-redis-${NETWORK}
    # No volume mount - Redis data should not persist across test runs
    # This ensures a clean state when containers are restarted
    command: redis-server
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - xatu_xatu-net

  # Config setup container
  cbt-config-setup:
    image: python:3.12-alpine
    container_name: cbt-config-setup-${NETWORK}
    volumes:
      - cbt-config:/config
      - ./overrides.yaml:/overrides.yaml:ro
      - ./overrides.tests.yaml:/overrides.tests.yaml:ro
    environment:
      - TESTING=${TESTING:-false}
      - NETWORK=${NETWORK}
      - CLICKHOUSE_USERNAME=${CLICKHOUSE_USERNAME}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
    command:
      - /bin/sh
      - -c
      - |
        pip install pyyaml > /dev/null 2>&1
        python3 << 'PYTHON_SCRIPT'
        import yaml
        import os
        
        network = os.environ.get('NETWORK', 'mainnet')
        testing = os.environ.get('TESTING', 'false').lower() == 'true'
        clickhouse_user = os.environ.get('CLICKHOUSE_USERNAME', 'default')
        clickhouse_pass = os.environ.get('CLICKHOUSE_PASSWORD', '')
        
        # Base configuration
        config = {
            'logging': 'debug',
            'metricsAddr': ':9090',
            'healthCheckAddr': ':8081',
            'clickhouse': {
                'url': f'http://{clickhouse_user}:{clickhouse_pass}@xatu-clickhouse-01:8123',
                'cluster': '{cluster}',
                'localSuffix': '_local',
                'admin': {
                    'incremental': {
                        'database': network,
                        'table': 'admin_cbt_incremental'
                    },
                    'scheduled': {
                        'database': network,
                        'table': 'admin_cbt_scheduled'
                    }
                }
            },
            'redis': {
                'url': f'redis://cbt-redis-{network}:6379/0'
            },
            'scheduler': {
                'concurrency': 10,
                'consolidation': '@every 10m'
            },
            'worker': {
                'concurrency': 10
            },
            'models': {
                'external': {
                    'defaultDatabase': network
                },
                'transformations': {
                    'defaultDatabase': network
                }
            },
            'frontend': {
                'enabled': True,
                'addr': ':8080'
            },
            'interval_types': {
                'slot': [
                    {
                        'name': 'Slot',
                        'expression': "math.floor((value - 1606824023) / 12)"
                    },
                    {
                        'name': 'Datetime',
                        'format': 'datetime',
                        'expression': "value * 1000"
                    }
                ],
                'block': [
                    {
                        'name': 'Block number'
                    }
                ],
                'entity': [
                    {
                        'name': 'Validator index'
                    }
                ]
            } 
        }
        
        # Merge with overrides if they exist
        override_file = '/overrides.tests.yaml' if testing else '/overrides.yaml'
        if os.path.exists(override_file) and os.path.getsize(override_file) > 0:
            with open(override_file, 'r') as f:
                overrides = yaml.safe_load(f)
                if overrides:
                    # Deep merge the configurations
                    def deep_merge(base, override):
                        for key, value in override.items():
                            if key in base and isinstance(base[key], dict) and isinstance(value, dict):
                                deep_merge(base[key], value)
                            else:
                                base[key] = value
                    deep_merge(config, overrides)
                    print(f"Merged {'test' if testing else 'production'} overrides")
        
        # Write the final configuration
        with open(f'/config/{network}.yaml', 'w') as f:
            yaml.dump(config, f, default_flow_style=False, sort_keys=False)
        
        print("Config file created successfully")
        PYTHON_SCRIPT

  # CBT Engine
  cbt-engine:
    image: ethpandaops/cbt:debian-latest
    container_name: cbt-engine-${NETWORK}
    depends_on:
      cbt-redis:
        condition: service_healthy
      cbt-config-setup:
        condition: service_completed_successfully
      # cbt-clickhouse-migrator:
      #   condition: service_completed_successfully
    volumes:
      - ./models:/models:ro
      - cbt-config:/config:ro
    command: ["--config", "/config/${NETWORK}.yaml"]
    restart: unless-stopped
    ports:
      - "8080:8080"  # Frontend port
    networks:
      - xatu_xatu-net
    deploy:
      replicas: 1

networks:
  xatu_xatu-net:
    external: true
