// Code generated by clickhouse-proto-gen. DO NOT EDIT.
// SQL query builder for dim_validator_status

package clickhouse

import (
	"fmt"
)

// BuildListDimValidatorStatusQuery constructs a parameterized SQL query from a ListDimValidatorStatusRequest
func BuildListDimValidatorStatusQuery(req *ListDimValidatorStatusRequest, options ...QueryOption) (SQLQuery, error) {
	// Validate that at least one primary key is provided
	// Primary keys can come from base table or projections
	if req.ValidatorIndex == nil {
		return SQLQuery{}, fmt.Errorf("primary key field validator_index is required")
	}

	// Build query using QueryBuilder
	qb := NewQueryBuilder()

	// Add primary key filter
	switch filter := req.ValidatorIndex.Filter.(type) {
	case *UInt32Filter_Eq:
		qb.AddCondition("validator_index", "=", filter.Eq)
	case *UInt32Filter_Ne:
		qb.AddCondition("validator_index", "!=", filter.Ne)
	case *UInt32Filter_Lt:
		qb.AddCondition("validator_index", "<", filter.Lt)
	case *UInt32Filter_Lte:
		qb.AddCondition("validator_index", "<=", filter.Lte)
	case *UInt32Filter_Gt:
		qb.AddCondition("validator_index", ">", filter.Gt)
	case *UInt32Filter_Gte:
		qb.AddCondition("validator_index", ">=", filter.Gte)
	case *UInt32Filter_Between:
		qb.AddBetweenCondition("validator_index", filter.Between.Min, filter.Between.Max.GetValue())
	case *UInt32Filter_In:
		if len(filter.In.Values) > 0 {
			qb.AddInCondition("validator_index", UInt32SliceToInterface(filter.In.Values))
		}
	case *UInt32Filter_NotIn:
		if len(filter.NotIn.Values) > 0 {
			qb.AddNotInCondition("validator_index", UInt32SliceToInterface(filter.NotIn.Values))
		}
	default:
		// Unsupported filter type
	}

	// Add filter for column: updated_date_time
	if req.UpdatedDateTime != nil {
		switch filter := req.UpdatedDateTime.Filter.(type) {
		case *UInt32Filter_Eq:
			qb.AddCondition("updated_date_time", "=", DateTimeValue{filter.Eq})
		case *UInt32Filter_Ne:
			qb.AddCondition("updated_date_time", "!=", DateTimeValue{filter.Ne})
		case *UInt32Filter_Lt:
			qb.AddCondition("updated_date_time", "<", DateTimeValue{filter.Lt})
		case *UInt32Filter_Lte:
			qb.AddCondition("updated_date_time", "<=", DateTimeValue{filter.Lte})
		case *UInt32Filter_Gt:
			qb.AddCondition("updated_date_time", ">", DateTimeValue{filter.Gt})
		case *UInt32Filter_Gte:
			qb.AddCondition("updated_date_time", ">=", DateTimeValue{filter.Gte})
		case *UInt32Filter_Between:
			qb.AddBetweenCondition("updated_date_time", DateTimeValue{filter.Between.Min}, DateTimeValue{filter.Between.Max.GetValue()})
		case *UInt32Filter_In:
			if len(filter.In.Values) > 0 {
				converted := make([]interface{}, len(filter.In.Values))
				for i, v := range filter.In.Values {
					converted[i] = DateTimeValue{v}
				}
				qb.AddInCondition("updated_date_time", converted)
			}
		case *UInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				converted := make([]interface{}, len(filter.NotIn.Values))
				for i, v := range filter.NotIn.Values {
					converted[i] = DateTimeValue{v}
				}
				qb.AddNotInCondition("updated_date_time", converted)
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: version
	if req.Version != nil {
		switch filter := req.Version.Filter.(type) {
		case *UInt32Filter_Eq:
			qb.AddCondition("version", "=", filter.Eq)
		case *UInt32Filter_Ne:
			qb.AddCondition("version", "!=", filter.Ne)
		case *UInt32Filter_Lt:
			qb.AddCondition("version", "<", filter.Lt)
		case *UInt32Filter_Lte:
			qb.AddCondition("version", "<=", filter.Lte)
		case *UInt32Filter_Gt:
			qb.AddCondition("version", ">", filter.Gt)
		case *UInt32Filter_Gte:
			qb.AddCondition("version", ">=", filter.Gte)
		case *UInt32Filter_Between:
			qb.AddBetweenCondition("version", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt32Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("version", UInt32SliceToInterface(filter.In.Values))
			}
		case *UInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("version", UInt32SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: pubkey
	if req.Pubkey != nil {
		switch filter := req.Pubkey.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("pubkey", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("pubkey", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("pubkey", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("pubkey", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("pubkey", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("pubkey", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("pubkey", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("pubkey", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("pubkey", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: status
	if req.Status != nil {
		switch filter := req.Status.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("status", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("status", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("status", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("status", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("status", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("status", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("status", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("status", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("status", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: epoch
	if req.Epoch != nil {
		switch filter := req.Epoch.Filter.(type) {
		case *UInt32Filter_Eq:
			qb.AddCondition("epoch", "=", filter.Eq)
		case *UInt32Filter_Ne:
			qb.AddCondition("epoch", "!=", filter.Ne)
		case *UInt32Filter_Lt:
			qb.AddCondition("epoch", "<", filter.Lt)
		case *UInt32Filter_Lte:
			qb.AddCondition("epoch", "<=", filter.Lte)
		case *UInt32Filter_Gt:
			qb.AddCondition("epoch", ">", filter.Gt)
		case *UInt32Filter_Gte:
			qb.AddCondition("epoch", ">=", filter.Gte)
		case *UInt32Filter_Between:
			qb.AddBetweenCondition("epoch", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt32Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("epoch", UInt32SliceToInterface(filter.In.Values))
			}
		case *UInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("epoch", UInt32SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: epoch_start_date_time
	if req.EpochStartDateTime != nil {
		switch filter := req.EpochStartDateTime.Filter.(type) {
		case *UInt32Filter_Eq:
			qb.AddCondition("epoch_start_date_time", "=", DateTimeValue{filter.Eq})
		case *UInt32Filter_Ne:
			qb.AddCondition("epoch_start_date_time", "!=", DateTimeValue{filter.Ne})
		case *UInt32Filter_Lt:
			qb.AddCondition("epoch_start_date_time", "<", DateTimeValue{filter.Lt})
		case *UInt32Filter_Lte:
			qb.AddCondition("epoch_start_date_time", "<=", DateTimeValue{filter.Lte})
		case *UInt32Filter_Gt:
			qb.AddCondition("epoch_start_date_time", ">", DateTimeValue{filter.Gt})
		case *UInt32Filter_Gte:
			qb.AddCondition("epoch_start_date_time", ">=", DateTimeValue{filter.Gte})
		case *UInt32Filter_Between:
			qb.AddBetweenCondition("epoch_start_date_time", DateTimeValue{filter.Between.Min}, DateTimeValue{filter.Between.Max.GetValue()})
		case *UInt32Filter_In:
			if len(filter.In.Values) > 0 {
				converted := make([]interface{}, len(filter.In.Values))
				for i, v := range filter.In.Values {
					converted[i] = DateTimeValue{v}
				}
				qb.AddInCondition("epoch_start_date_time", converted)
			}
		case *UInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				converted := make([]interface{}, len(filter.NotIn.Values))
				for i, v := range filter.NotIn.Values {
					converted[i] = DateTimeValue{v}
				}
				qb.AddNotInCondition("epoch_start_date_time", converted)
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: activation_epoch
	if req.ActivationEpoch != nil {
		switch filter := req.ActivationEpoch.Filter.(type) {
		case *NullableUInt64Filter_Eq:
			qb.AddCondition("activation_epoch", "=", filter.Eq)
		case *NullableUInt64Filter_Ne:
			qb.AddCondition("activation_epoch", "!=", filter.Ne)
		case *NullableUInt64Filter_Lt:
			qb.AddCondition("activation_epoch", "<", filter.Lt)
		case *NullableUInt64Filter_Lte:
			qb.AddCondition("activation_epoch", "<=", filter.Lte)
		case *NullableUInt64Filter_Gt:
			qb.AddCondition("activation_epoch", ">", filter.Gt)
		case *NullableUInt64Filter_Gte:
			qb.AddCondition("activation_epoch", ">=", filter.Gte)
		case *NullableUInt64Filter_Between:
			qb.AddBetweenCondition("activation_epoch", filter.Between.Min, filter.Between.Max.GetValue())
		case *NullableUInt64Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("activation_epoch", UInt64SliceToInterface(filter.In.Values))
			}
		case *NullableUInt64Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("activation_epoch", UInt64SliceToInterface(filter.NotIn.Values))
			}
		case *NullableUInt64Filter_IsNull:
			qb.AddIsNullCondition("activation_epoch")
		case *NullableUInt64Filter_IsNotNull:
			qb.AddIsNotNullCondition("activation_epoch")
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: activation_eligibility_epoch
	if req.ActivationEligibilityEpoch != nil {
		switch filter := req.ActivationEligibilityEpoch.Filter.(type) {
		case *NullableUInt64Filter_Eq:
			qb.AddCondition("activation_eligibility_epoch", "=", filter.Eq)
		case *NullableUInt64Filter_Ne:
			qb.AddCondition("activation_eligibility_epoch", "!=", filter.Ne)
		case *NullableUInt64Filter_Lt:
			qb.AddCondition("activation_eligibility_epoch", "<", filter.Lt)
		case *NullableUInt64Filter_Lte:
			qb.AddCondition("activation_eligibility_epoch", "<=", filter.Lte)
		case *NullableUInt64Filter_Gt:
			qb.AddCondition("activation_eligibility_epoch", ">", filter.Gt)
		case *NullableUInt64Filter_Gte:
			qb.AddCondition("activation_eligibility_epoch", ">=", filter.Gte)
		case *NullableUInt64Filter_Between:
			qb.AddBetweenCondition("activation_eligibility_epoch", filter.Between.Min, filter.Between.Max.GetValue())
		case *NullableUInt64Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("activation_eligibility_epoch", UInt64SliceToInterface(filter.In.Values))
			}
		case *NullableUInt64Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("activation_eligibility_epoch", UInt64SliceToInterface(filter.NotIn.Values))
			}
		case *NullableUInt64Filter_IsNull:
			qb.AddIsNullCondition("activation_eligibility_epoch")
		case *NullableUInt64Filter_IsNotNull:
			qb.AddIsNotNullCondition("activation_eligibility_epoch")
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: exit_epoch
	if req.ExitEpoch != nil {
		switch filter := req.ExitEpoch.Filter.(type) {
		case *NullableUInt64Filter_Eq:
			qb.AddCondition("exit_epoch", "=", filter.Eq)
		case *NullableUInt64Filter_Ne:
			qb.AddCondition("exit_epoch", "!=", filter.Ne)
		case *NullableUInt64Filter_Lt:
			qb.AddCondition("exit_epoch", "<", filter.Lt)
		case *NullableUInt64Filter_Lte:
			qb.AddCondition("exit_epoch", "<=", filter.Lte)
		case *NullableUInt64Filter_Gt:
			qb.AddCondition("exit_epoch", ">", filter.Gt)
		case *NullableUInt64Filter_Gte:
			qb.AddCondition("exit_epoch", ">=", filter.Gte)
		case *NullableUInt64Filter_Between:
			qb.AddBetweenCondition("exit_epoch", filter.Between.Min, filter.Between.Max.GetValue())
		case *NullableUInt64Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("exit_epoch", UInt64SliceToInterface(filter.In.Values))
			}
		case *NullableUInt64Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("exit_epoch", UInt64SliceToInterface(filter.NotIn.Values))
			}
		case *NullableUInt64Filter_IsNull:
			qb.AddIsNullCondition("exit_epoch")
		case *NullableUInt64Filter_IsNotNull:
			qb.AddIsNotNullCondition("exit_epoch")
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: withdrawable_epoch
	if req.WithdrawableEpoch != nil {
		switch filter := req.WithdrawableEpoch.Filter.(type) {
		case *NullableUInt64Filter_Eq:
			qb.AddCondition("withdrawable_epoch", "=", filter.Eq)
		case *NullableUInt64Filter_Ne:
			qb.AddCondition("withdrawable_epoch", "!=", filter.Ne)
		case *NullableUInt64Filter_Lt:
			qb.AddCondition("withdrawable_epoch", "<", filter.Lt)
		case *NullableUInt64Filter_Lte:
			qb.AddCondition("withdrawable_epoch", "<=", filter.Lte)
		case *NullableUInt64Filter_Gt:
			qb.AddCondition("withdrawable_epoch", ">", filter.Gt)
		case *NullableUInt64Filter_Gte:
			qb.AddCondition("withdrawable_epoch", ">=", filter.Gte)
		case *NullableUInt64Filter_Between:
			qb.AddBetweenCondition("withdrawable_epoch", filter.Between.Min, filter.Between.Max.GetValue())
		case *NullableUInt64Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("withdrawable_epoch", UInt64SliceToInterface(filter.In.Values))
			}
		case *NullableUInt64Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("withdrawable_epoch", UInt64SliceToInterface(filter.NotIn.Values))
			}
		case *NullableUInt64Filter_IsNull:
			qb.AddIsNullCondition("withdrawable_epoch")
		case *NullableUInt64Filter_IsNotNull:
			qb.AddIsNotNullCondition("withdrawable_epoch")
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: slashed
	if req.Slashed != nil {
		switch filter := req.Slashed.Filter.(type) {
		case *BoolFilter_Eq:
			qb.AddCondition("slashed", "=", filter.Eq)
		case *BoolFilter_Ne:
			qb.AddCondition("slashed", "!=", filter.Ne)
		default:
			// Unsupported filter type
		}
	}

	// Handle pagination per AIP-132
	// Validate page size
	if req.PageSize < 0 {
		return SQLQuery{}, fmt.Errorf("page_size must be non-negative, got %d", req.PageSize)
	}
	if req.PageSize > 10000 {
		return SQLQuery{}, fmt.Errorf("page_size must not exceed %d, got %d", 10000, req.PageSize)
	}

	var limit, offset uint32
	limit = 100 // Default page size
	if req.PageSize > 0 {
		limit = uint32(req.PageSize)
	}
	if req.PageToken != "" {
		decodedOffset, err := DecodePageToken(req.PageToken)
		if err != nil {
			return SQLQuery{}, fmt.Errorf("invalid page_token: %w", err)
		}
		offset = decodedOffset
	}

	// Handle custom ordering if provided
	var orderByClause string
	if req.OrderBy != "" {
		validFields := []string{"updated_date_time", "version", "validator_index", "pubkey", "status", "epoch", "epoch_start_date_time", "activation_epoch", "activation_eligibility_epoch", "exit_epoch", "withdrawable_epoch", "slashed"}
		orderFields, err := ParseOrderBy(req.OrderBy, validFields)
		if err != nil {
			return SQLQuery{}, fmt.Errorf("invalid order_by: %w", err)
		}
		orderByClause = BuildOrderByClause(orderFields)
	} else {
		// Default sorting by primary key
		orderByClause = " ORDER BY validator_index" + ", status"
	}

	// Build column list
	columns := []string{"toUnixTimestamp(`updated_date_time`) AS `updated_date_time`", "version", "validator_index", "pubkey", "status", "epoch", "toUnixTimestamp(`epoch_start_date_time`) AS `epoch_start_date_time`", "activation_epoch", "activation_eligibility_epoch", "exit_epoch", "withdrawable_epoch", "slashed"}

	return BuildParameterizedQuery("dim_validator_status", columns, qb, orderByClause, limit, offset, options...)
}

// BuildGetDimValidatorStatusQuery constructs a parameterized SQL query from a GetDimValidatorStatusRequest
func BuildGetDimValidatorStatusQuery(req *GetDimValidatorStatusRequest, options ...QueryOption) (SQLQuery, error) {
	// Validate primary key is provided
	if req.ValidatorIndex == 0 {
		return SQLQuery{}, fmt.Errorf("primary key field validator_index is required")
	}

	// Build query with primary key condition
	qb := NewQueryBuilder()
	qb.AddCondition("validator_index", "=", req.ValidatorIndex)

	// Build ORDER BY clause
	orderByClause := " ORDER BY validator_index, status"

	// Build column list
	columns := []string{"toUnixTimestamp(`updated_date_time`) AS `updated_date_time`", "version", "validator_index", "pubkey", "status", "epoch", "toUnixTimestamp(`epoch_start_date_time`) AS `epoch_start_date_time`", "activation_epoch", "activation_eligibility_epoch", "exit_epoch", "withdrawable_epoch", "slashed"}

	// Return single record
	return BuildParameterizedQuery("dim_validator_status", columns, qb, orderByClause, 1, 0, options...)
}
