// Code generated by clickhouse-proto-gen. DO NOT EDIT.
// SQL query builder for dim_token_contract

package clickhouse

import (
	"fmt"
)

// BuildListDimTokenContractQuery constructs a parameterized SQL query from a ListDimTokenContractRequest
func BuildListDimTokenContractQuery(req *ListDimTokenContractRequest, options ...QueryOption) (SQLQuery, error) {
	// Validate that at least one primary key is provided
	// Primary keys can come from base table or projections
	if req.ContractAddress == nil {
		return SQLQuery{}, fmt.Errorf("primary key field contract_address is required")
	}

	// Build query using QueryBuilder
	qb := NewQueryBuilder()

	// Add primary key filter
	switch filter := req.ContractAddress.Filter.(type) {
	case *StringFilter_Eq:
		qb.AddCondition("contract_address", "=", filter.Eq)
	case *StringFilter_Ne:
		qb.AddCondition("contract_address", "!=", filter.Ne)
	case *StringFilter_Contains:
		qb.AddLikeCondition("contract_address", "%" + filter.Contains + "%")
	case *StringFilter_StartsWith:
		qb.AddLikeCondition("contract_address", filter.StartsWith + "%")
	case *StringFilter_EndsWith:
		qb.AddLikeCondition("contract_address", "%" + filter.EndsWith)
	case *StringFilter_Like:
		qb.AddLikeCondition("contract_address", filter.Like)
	case *StringFilter_NotLike:
		qb.AddNotLikeCondition("contract_address", filter.NotLike)
	case *StringFilter_In:
		if len(filter.In.Values) > 0 {
			qb.AddInCondition("contract_address", StringSliceToInterface(filter.In.Values))
		}
	case *StringFilter_NotIn:
		if len(filter.NotIn.Values) > 0 {
			qb.AddNotInCondition("contract_address", StringSliceToInterface(filter.NotIn.Values))
		}
	default:
		// Unsupported filter type
	}

	// Add filter for column: updated_date_time
	if req.UpdatedDateTime != nil {
		switch filter := req.UpdatedDateTime.Filter.(type) {
		case *UInt32Filter_Eq:
			qb.AddCondition("updated_date_time", "=", DateTimeValue{filter.Eq})
		case *UInt32Filter_Ne:
			qb.AddCondition("updated_date_time", "!=", DateTimeValue{filter.Ne})
		case *UInt32Filter_Lt:
			qb.AddCondition("updated_date_time", "<", DateTimeValue{filter.Lt})
		case *UInt32Filter_Lte:
			qb.AddCondition("updated_date_time", "<=", DateTimeValue{filter.Lte})
		case *UInt32Filter_Gt:
			qb.AddCondition("updated_date_time", ">", DateTimeValue{filter.Gt})
		case *UInt32Filter_Gte:
			qb.AddCondition("updated_date_time", ">=", DateTimeValue{filter.Gte})
		case *UInt32Filter_Between:
			qb.AddBetweenCondition("updated_date_time", DateTimeValue{filter.Between.Min}, DateTimeValue{filter.Between.Max.GetValue()})
		case *UInt32Filter_In:
			if len(filter.In.Values) > 0 {
				converted := make([]interface{}, len(filter.In.Values))
				for i, v := range filter.In.Values {
					converted[i] = DateTimeValue{v}
				}
				qb.AddInCondition("updated_date_time", converted)
			}
		case *UInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				converted := make([]interface{}, len(filter.NotIn.Values))
				for i, v := range filter.NotIn.Values {
					converted[i] = DateTimeValue{v}
				}
				qb.AddNotInCondition("updated_date_time", converted)
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: token_standard
	if req.TokenStandard != nil {
		switch filter := req.TokenStandard.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("token_standard", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("token_standard", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("token_standard", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("token_standard", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("token_standard", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("token_standard", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("token_standard", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("token_standard", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("token_standard", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Handle pagination per AIP-132
	// Validate page size
	if req.PageSize < 0 {
		return SQLQuery{}, fmt.Errorf("page_size must be non-negative, got %d", req.PageSize)
	}
	if req.PageSize > 10000 {
		return SQLQuery{}, fmt.Errorf("page_size must not exceed %d, got %d", 10000, req.PageSize)
	}

	var limit, offset uint32
	limit = 100 // Default page size
	if req.PageSize > 0 {
		limit = uint32(req.PageSize)
	}
	if req.PageToken != "" {
		decodedOffset, err := DecodePageToken(req.PageToken)
		if err != nil {
			return SQLQuery{}, fmt.Errorf("invalid page_token: %w", err)
		}
		offset = decodedOffset
	}

	// Handle custom ordering if provided
	var orderByClause string
	if req.OrderBy != "" {
		validFields := []string{"updated_date_time", "contract_address", "token_standard"}
		orderFields, err := ParseOrderBy(req.OrderBy, validFields)
		if err != nil {
			return SQLQuery{}, fmt.Errorf("invalid order_by: %w", err)
		}
		orderByClause = BuildOrderByClause(orderFields)
	} else {
		// Default sorting by primary key
		orderByClause = " ORDER BY contract_address"
	}

	// Build column list
	columns := []string{"toUnixTimestamp(`updated_date_time`) AS `updated_date_time`", "contract_address", "token_standard"}

	return BuildParameterizedQuery("dim_token_contract", columns, qb, orderByClause, limit, offset, options...)
}

// BuildGetDimTokenContractQuery constructs a parameterized SQL query from a GetDimTokenContractRequest
func BuildGetDimTokenContractQuery(req *GetDimTokenContractRequest, options ...QueryOption) (SQLQuery, error) {
	// Validate primary key is provided
	if req.ContractAddress == "" {
		return SQLQuery{}, fmt.Errorf("primary key field contract_address is required")
	}

	// Build query with primary key condition
	qb := NewQueryBuilder()
	qb.AddCondition("contract_address", "=", req.ContractAddress)

	// Build ORDER BY clause
	orderByClause := " ORDER BY contract_address"

	// Build column list
	columns := []string{"toUnixTimestamp(`updated_date_time`) AS `updated_date_time`", "contract_address", "token_standard"}

	// Return single record
	return BuildParameterizedQuery("dim_token_contract", columns, qb, orderByClause, 1, 0, options...)
}
