// Code generated by clickhouse-proto-gen. DO NOT EDIT.
// Scannable result row for dim_node

package clickhouse

import (
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
)

// DimNodeRow is a ClickHouse-scannable result row for the dim_node table.
// Field types match the SELECT column expressions produced by
// BuildListDimNodeQuery and BuildGetDimNodeQuery: DateTime columns are unix
// timestamps, DateTime64 columns are unix microseconds, Date and large
// integer and decimal columns are strings, and FixedString columns are
// nullable. Scan rows with clickhouse-go's ScanStruct.
type DimNodeRow struct {
	UpdatedDateTime uint32 `ch:"updated_date_time" json:"updated_date_time"`
	ValidatorIndex uint32 `ch:"validator_index" json:"validator_index"`
	Name *string `ch:"name" json:"name"`
	Groups []string `ch:"groups" json:"groups"`
	Tags []string `ch:"tags" json:"tags"`
	Attributes map[string]string `ch:"attributes" json:"attributes"`
	Source string `ch:"source" json:"source"`
}

// TableName returns the ClickHouse table this row maps to.
func (DimNodeRow) TableName() string {
	return "dim_node"
}

// ToProto converts the row to its protobuf message.
func (r *DimNodeRow) ToProto() *DimNode {
	p := &DimNode{}

	p.UpdatedDateTime = r.UpdatedDateTime
	p.ValidatorIndex = r.ValidatorIndex
	if r.Name != nil {
		p.Name = wrapperspb.String(*r.Name)
	}
	p.Groups = r.Groups
	p.Tags = r.Tags
	p.Attributes = r.Attributes
	p.Source = r.Source
	return p
}
