// Code generated by clickhouse-proto-gen. DO NOT EDIT.
// Scannable result row for fct_attestation_participation_rate_daily

package clickhouse

// FctAttestationParticipationRateDailyRow is a ClickHouse-scannable result row for the fct_attestation_participation_rate_daily table.
// Field types match the SELECT column expressions produced by
// BuildListFctAttestationParticipationRateDailyQuery and BuildGetFctAttestationParticipationRateDailyQuery: DateTime columns are unix
// timestamps, DateTime64 columns are unix microseconds, Date and large
// integer and decimal columns are strings, and FixedString columns are
// nullable. Scan rows with clickhouse-go's ScanStruct.
type FctAttestationParticipationRateDailyRow struct {
	UpdatedDateTime uint32 `ch:"updated_date_time" json:"updated_date_time"`
	DayStartDate string `ch:"day_start_date" json:"day_start_date"`
	SlotCount uint32 `ch:"slot_count" json:"slot_count"`
	AvgParticipationRate float32 `ch:"avg_participation_rate" json:"avg_participation_rate"`
	MinParticipationRate float32 `ch:"min_participation_rate" json:"min_participation_rate"`
	MaxParticipationRate float32 `ch:"max_participation_rate" json:"max_participation_rate"`
	P05ParticipationRate float32 `ch:"p05_participation_rate" json:"p05_participation_rate"`
	P50ParticipationRate float32 `ch:"p50_participation_rate" json:"p50_participation_rate"`
	P95ParticipationRate float32 `ch:"p95_participation_rate" json:"p95_participation_rate"`
	StddevParticipationRate float32 `ch:"stddev_participation_rate" json:"stddev_participation_rate"`
	UpperBandParticipationRate float32 `ch:"upper_band_participation_rate" json:"upper_band_participation_rate"`
	LowerBandParticipationRate float32 `ch:"lower_band_participation_rate" json:"lower_band_participation_rate"`
	MovingAvgParticipationRate float32 `ch:"moving_avg_participation_rate" json:"moving_avg_participation_rate"`
}

// TableName returns the ClickHouse table this row maps to.
func (FctAttestationParticipationRateDailyRow) TableName() string {
	return "fct_attestation_participation_rate_daily"
}

// ToProto converts the row to its protobuf message.
func (r *FctAttestationParticipationRateDailyRow) ToProto() *FctAttestationParticipationRateDaily {
	p := &FctAttestationParticipationRateDaily{}

	p.UpdatedDateTime = r.UpdatedDateTime
	p.DayStartDate = r.DayStartDate
	p.SlotCount = r.SlotCount
	p.AvgParticipationRate = r.AvgParticipationRate
	p.MinParticipationRate = r.MinParticipationRate
	p.MaxParticipationRate = r.MaxParticipationRate
	p.P05ParticipationRate = r.P05ParticipationRate
	p.P50ParticipationRate = r.P50ParticipationRate
	p.P95ParticipationRate = r.P95ParticipationRate
	p.StddevParticipationRate = r.StddevParticipationRate
	p.UpperBandParticipationRate = r.UpperBandParticipationRate
	p.LowerBandParticipationRate = r.LowerBandParticipationRate
	p.MovingAvgParticipationRate = r.MovingAvgParticipationRate
	return p
}
