// Code generated by clickhouse-proto-gen. DO NOT EDIT.
// Scannable result row for fct_data_column_availability_daily

package clickhouse

// FctDataColumnAvailabilityDailyRow is a ClickHouse-scannable result row for the fct_data_column_availability_daily table.
// Field types match the SELECT column expressions produced by
// BuildListFctDataColumnAvailabilityDailyQuery and BuildGetFctDataColumnAvailabilityDailyQuery: DateTime columns are unix
// timestamps, DateTime64 columns are unix microseconds, Date and large
// integer and decimal columns are strings, and FixedString columns are
// nullable. Scan rows with clickhouse-go's ScanStruct.
type FctDataColumnAvailabilityDailyRow struct {
	UpdatedDateTime uint32 `ch:"updated_date_time" json:"updated_date_time"`
	Date string `ch:"date" json:"date"`
	ColumnIndex uint64 `ch:"column_index" json:"column_index"`
	HourCount uint32 `ch:"hour_count" json:"hour_count"`
	AvgAvailabilityPct float64 `ch:"avg_availability_pct" json:"avg_availability_pct"`
	MinAvailabilityPct float64 `ch:"min_availability_pct" json:"min_availability_pct"`
	MaxAvailabilityPct float64 `ch:"max_availability_pct" json:"max_availability_pct"`
	TotalProbeCount uint64 `ch:"total_probe_count" json:"total_probe_count"`
	TotalSuccessCount uint64 `ch:"total_success_count" json:"total_success_count"`
	TotalFailureCount uint64 `ch:"total_failure_count" json:"total_failure_count"`
	TotalMissingCount uint64 `ch:"total_missing_count" json:"total_missing_count"`
	MinResponseTimeMs uint32 `ch:"min_response_time_ms" json:"min_response_time_ms"`
	AvgP50ResponseTimeMs uint32 `ch:"avg_p50_response_time_ms" json:"avg_p50_response_time_ms"`
	AvgP95ResponseTimeMs uint32 `ch:"avg_p95_response_time_ms" json:"avg_p95_response_time_ms"`
	AvgP99ResponseTimeMs uint32 `ch:"avg_p99_response_time_ms" json:"avg_p99_response_time_ms"`
	MaxResponseTimeMs uint32 `ch:"max_response_time_ms" json:"max_response_time_ms"`
	MaxBlobCount uint32 `ch:"max_blob_count" json:"max_blob_count"`
}

// TableName returns the ClickHouse table this row maps to.
func (FctDataColumnAvailabilityDailyRow) TableName() string {
	return "fct_data_column_availability_daily"
}

// ToProto converts the row to its protobuf message.
func (r *FctDataColumnAvailabilityDailyRow) ToProto() *FctDataColumnAvailabilityDaily {
	p := &FctDataColumnAvailabilityDaily{}

	p.UpdatedDateTime = r.UpdatedDateTime
	p.Date = r.Date
	p.ColumnIndex = r.ColumnIndex
	p.HourCount = r.HourCount
	p.AvgAvailabilityPct = r.AvgAvailabilityPct
	p.MinAvailabilityPct = r.MinAvailabilityPct
	p.MaxAvailabilityPct = r.MaxAvailabilityPct
	p.TotalProbeCount = r.TotalProbeCount
	p.TotalSuccessCount = r.TotalSuccessCount
	p.TotalFailureCount = r.TotalFailureCount
	p.TotalMissingCount = r.TotalMissingCount
	p.MinResponseTimeMs = r.MinResponseTimeMs
	p.AvgP50ResponseTimeMs = r.AvgP50ResponseTimeMs
	p.AvgP95ResponseTimeMs = r.AvgP95ResponseTimeMs
	p.AvgP99ResponseTimeMs = r.AvgP99ResponseTimeMs
	p.MaxResponseTimeMs = r.MaxResponseTimeMs
	p.MaxBlobCount = r.MaxBlobCount
	return p
}
