// Code generated by clickhouse-proto-gen. DO NOT EDIT.
// Scannable result row for fct_storage_slot_state_with_expiry_by_block_hourly

package clickhouse

// FctStorageSlotStateWithExpiryByBlockHourlyRow is a ClickHouse-scannable result row for the fct_storage_slot_state_with_expiry_by_block_hourly table.
// Field types match the SELECT column expressions produced by
// BuildListFctStorageSlotStateWithExpiryByBlockHourlyQuery and BuildGetFctStorageSlotStateWithExpiryByBlockHourlyQuery: DateTime columns are unix
// timestamps, DateTime64 columns are unix microseconds, Date and large
// integer and decimal columns are strings, and FixedString columns are
// nullable. Scan rows with clickhouse-go's ScanStruct.
type FctStorageSlotStateWithExpiryByBlockHourlyRow struct {
	UpdatedDateTime uint32 `ch:"updated_date_time" json:"updated_date_time"`
	HourStartDateTime uint32 `ch:"hour_start_date_time" json:"hour_start_date_time"`
	ExpiryPolicy string `ch:"expiry_policy" json:"expiry_policy"`
	ActiveSlots int64 `ch:"active_slots" json:"active_slots"`
	EffectiveBytes int64 `ch:"effective_bytes" json:"effective_bytes"`
}

// TableName returns the ClickHouse table this row maps to.
func (FctStorageSlotStateWithExpiryByBlockHourlyRow) TableName() string {
	return "fct_storage_slot_state_with_expiry_by_block_hourly"
}

// ToProto converts the row to its protobuf message.
func (r *FctStorageSlotStateWithExpiryByBlockHourlyRow) ToProto() *FctStorageSlotStateWithExpiryByBlockHourly {
	p := &FctStorageSlotStateWithExpiryByBlockHourly{}

	p.UpdatedDateTime = r.UpdatedDateTime
	p.HourStartDateTime = r.HourStartDateTime
	p.ExpiryPolicy = r.ExpiryPolicy
	p.ActiveSlots = r.ActiveSlots
	p.EffectiveBytes = r.EffectiveBytes
	return p
}
