// Code generated by clickhouse-proto-gen. DO NOT EDIT.
// Scannable result row for fct_engine_new_payload_winrate_daily

package clickhouse

// FctEngineNewPayloadWinrateDailyRow is a ClickHouse-scannable result row for the fct_engine_new_payload_winrate_daily table.
// Field types match the SELECT column expressions produced by
// BuildListFctEngineNewPayloadWinrateDailyQuery and BuildGetFctEngineNewPayloadWinrateDailyQuery: DateTime columns are unix
// timestamps, DateTime64 columns are unix microseconds, Date and large
// integer and decimal columns are strings, and FixedString columns are
// nullable. Scan rows with clickhouse-go's ScanStruct.
type FctEngineNewPayloadWinrateDailyRow struct {
	UpdatedDateTime uint32 `ch:"updated_date_time" json:"updated_date_time"`
	DayStartDate string `ch:"day_start_date" json:"day_start_date"`
	NodeClass string `ch:"node_class" json:"node_class"`
	MetaExecutionImplementation string `ch:"meta_execution_implementation" json:"meta_execution_implementation"`
	WinCount uint32 `ch:"win_count" json:"win_count"`
}

// TableName returns the ClickHouse table this row maps to.
func (FctEngineNewPayloadWinrateDailyRow) TableName() string {
	return "fct_engine_new_payload_winrate_daily"
}

// ToProto converts the row to its protobuf message.
func (r *FctEngineNewPayloadWinrateDailyRow) ToProto() *FctEngineNewPayloadWinrateDaily {
	p := &FctEngineNewPayloadWinrateDaily{}

	p.UpdatedDateTime = r.UpdatedDateTime
	p.DayStartDate = r.DayStartDate
	p.NodeClass = r.NodeClass
	p.MetaExecutionImplementation = r.MetaExecutionImplementation
	p.WinCount = r.WinCount
	return p
}
