// Code generated by clickhouse-proto-gen. DO NOT EDIT.
// SQL query builder for fct_peer_count_by_custody_bucket_continent_hourly

package clickhouse

import (
	"fmt"
)

// BuildListFctPeerCountByCustodyBucketContinentHourlyQuery constructs a parameterized SQL query from a ListFctPeerCountByCustodyBucketContinentHourlyRequest
func BuildListFctPeerCountByCustodyBucketContinentHourlyQuery(req *ListFctPeerCountByCustodyBucketContinentHourlyRequest, options ...QueryOption) (SQLQuery, error) {
	// Validate that at least one primary key is provided
	// Primary keys can come from base table or projections
	if req.HourStartDateTime == nil {
		return SQLQuery{}, fmt.Errorf("primary key field hour_start_date_time is required")
	}

	// Build query using QueryBuilder
	qb := NewQueryBuilder()

	// Add primary key filter
	switch filter := req.HourStartDateTime.Filter.(type) {
	case *UInt32Filter_Eq:
		qb.AddCondition("hour_start_date_time", "=", DateTimeValue{filter.Eq})
	case *UInt32Filter_Ne:
		qb.AddCondition("hour_start_date_time", "!=", DateTimeValue{filter.Ne})
	case *UInt32Filter_Lt:
		qb.AddCondition("hour_start_date_time", "<", DateTimeValue{filter.Lt})
	case *UInt32Filter_Lte:
		qb.AddCondition("hour_start_date_time", "<=", DateTimeValue{filter.Lte})
	case *UInt32Filter_Gt:
		qb.AddCondition("hour_start_date_time", ">", DateTimeValue{filter.Gt})
	case *UInt32Filter_Gte:
		qb.AddCondition("hour_start_date_time", ">=", DateTimeValue{filter.Gte})
	case *UInt32Filter_Between:
		qb.AddBetweenCondition("hour_start_date_time", DateTimeValue{filter.Between.Min}, DateTimeValue{filter.Between.Max.GetValue()})
	case *UInt32Filter_In:
		if len(filter.In.Values) > 0 {
			converted := make([]interface{}, len(filter.In.Values))
			for i, v := range filter.In.Values {
				converted[i] = DateTimeValue{v}
			}
			qb.AddInCondition("hour_start_date_time", converted)
		}
	case *UInt32Filter_NotIn:
		if len(filter.NotIn.Values) > 0 {
			converted := make([]interface{}, len(filter.NotIn.Values))
			for i, v := range filter.NotIn.Values {
				converted[i] = DateTimeValue{v}
			}
			qb.AddNotInCondition("hour_start_date_time", converted)
		}
	default:
		// Unsupported filter type
	}

	// Add filter for column: updated_date_time
	if req.UpdatedDateTime != nil {
		switch filter := req.UpdatedDateTime.Filter.(type) {
		case *UInt32Filter_Eq:
			qb.AddCondition("updated_date_time", "=", DateTimeValue{filter.Eq})
		case *UInt32Filter_Ne:
			qb.AddCondition("updated_date_time", "!=", DateTimeValue{filter.Ne})
		case *UInt32Filter_Lt:
			qb.AddCondition("updated_date_time", "<", DateTimeValue{filter.Lt})
		case *UInt32Filter_Lte:
			qb.AddCondition("updated_date_time", "<=", DateTimeValue{filter.Lte})
		case *UInt32Filter_Gt:
			qb.AddCondition("updated_date_time", ">", DateTimeValue{filter.Gt})
		case *UInt32Filter_Gte:
			qb.AddCondition("updated_date_time", ">=", DateTimeValue{filter.Gte})
		case *UInt32Filter_Between:
			qb.AddBetweenCondition("updated_date_time", DateTimeValue{filter.Between.Min}, DateTimeValue{filter.Between.Max.GetValue()})
		case *UInt32Filter_In:
			if len(filter.In.Values) > 0 {
				converted := make([]interface{}, len(filter.In.Values))
				for i, v := range filter.In.Values {
					converted[i] = DateTimeValue{v}
				}
				qb.AddInCondition("updated_date_time", converted)
			}
		case *UInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				converted := make([]interface{}, len(filter.NotIn.Values))
				for i, v := range filter.NotIn.Values {
					converted[i] = DateTimeValue{v}
				}
				qb.AddNotInCondition("updated_date_time", converted)
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: peer_geo_continent_code
	if req.PeerGeoContinentCode != nil {
		switch filter := req.PeerGeoContinentCode.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("peer_geo_continent_code", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("peer_geo_continent_code", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("peer_geo_continent_code", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("peer_geo_continent_code", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("peer_geo_continent_code", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("peer_geo_continent_code", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("peer_geo_continent_code", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("peer_geo_continent_code", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("peer_geo_continent_code", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: custody_bucket
	if req.CustodyBucket != nil {
		switch filter := req.CustodyBucket.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("custody_bucket", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("custody_bucket", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("custody_bucket", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("custody_bucket", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("custody_bucket", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("custody_bucket", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("custody_bucket", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("custody_bucket", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("custody_bucket", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: epoch_count
	if req.EpochCount != nil {
		switch filter := req.EpochCount.Filter.(type) {
		case *UInt32Filter_Eq:
			qb.AddCondition("epoch_count", "=", filter.Eq)
		case *UInt32Filter_Ne:
			qb.AddCondition("epoch_count", "!=", filter.Ne)
		case *UInt32Filter_Lt:
			qb.AddCondition("epoch_count", "<", filter.Lt)
		case *UInt32Filter_Lte:
			qb.AddCondition("epoch_count", "<=", filter.Lte)
		case *UInt32Filter_Gt:
			qb.AddCondition("epoch_count", ">", filter.Gt)
		case *UInt32Filter_Gte:
			qb.AddCondition("epoch_count", ">=", filter.Gte)
		case *UInt32Filter_Between:
			qb.AddBetweenCondition("epoch_count", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt32Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("epoch_count", UInt32SliceToInterface(filter.In.Values))
			}
		case *UInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("epoch_count", UInt32SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: peer_count
	if req.PeerCount != nil {
		switch filter := req.PeerCount.Filter.(type) {
		case *UInt32Filter_Eq:
			qb.AddCondition("peer_count", "=", filter.Eq)
		case *UInt32Filter_Ne:
			qb.AddCondition("peer_count", "!=", filter.Ne)
		case *UInt32Filter_Lt:
			qb.AddCondition("peer_count", "<", filter.Lt)
		case *UInt32Filter_Lte:
			qb.AddCondition("peer_count", "<=", filter.Lte)
		case *UInt32Filter_Gt:
			qb.AddCondition("peer_count", ">", filter.Gt)
		case *UInt32Filter_Gte:
			qb.AddCondition("peer_count", ">=", filter.Gte)
		case *UInt32Filter_Between:
			qb.AddBetweenCondition("peer_count", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt32Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("peer_count", UInt32SliceToInterface(filter.In.Values))
			}
		case *UInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("peer_count", UInt32SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Handle pagination per AIP-132
	// Validate page size
	if req.PageSize < 0 {
		return SQLQuery{}, fmt.Errorf("page_size must be non-negative, got %d", req.PageSize)
	}
	if req.PageSize > 10000 {
		return SQLQuery{}, fmt.Errorf("page_size must not exceed %d, got %d", 10000, req.PageSize)
	}

	var limit, offset uint32
	limit = 100 // Default page size
	if req.PageSize > 0 {
		limit = uint32(req.PageSize)
	}
	if req.PageToken != "" {
		decodedOffset, err := DecodePageToken(req.PageToken)
		if err != nil {
			return SQLQuery{}, fmt.Errorf("invalid page_token: %w", err)
		}
		offset = decodedOffset
	}

	// Handle custom ordering if provided
	var orderByClause string
	if req.OrderBy != "" {
		validFields := []string{"updated_date_time", "hour_start_date_time", "peer_geo_continent_code", "custody_bucket", "epoch_count", "peer_count"}
		orderFields, err := ParseOrderBy(req.OrderBy, validFields)
		if err != nil {
			return SQLQuery{}, fmt.Errorf("invalid order_by: %w", err)
		}
		orderByClause = BuildOrderByClause(orderFields)
	} else {
		// Default sorting by primary key
		orderByClause = " ORDER BY hour_start_date_time" + ", peer_geo_continent_code" + ", custody_bucket"
	}

	// Build column list
	columns := []string{"toUnixTimestamp(`updated_date_time`) AS `updated_date_time`", "toUnixTimestamp(`hour_start_date_time`) AS `hour_start_date_time`", "peer_geo_continent_code", "custody_bucket", "epoch_count", "peer_count"}

	return BuildParameterizedQuery("fct_peer_count_by_custody_bucket_continent_hourly", columns, qb, orderByClause, limit, offset, options...)
}

// BuildGetFctPeerCountByCustodyBucketContinentHourlyQuery constructs a parameterized SQL query from a GetFctPeerCountByCustodyBucketContinentHourlyRequest
func BuildGetFctPeerCountByCustodyBucketContinentHourlyQuery(req *GetFctPeerCountByCustodyBucketContinentHourlyRequest, options ...QueryOption) (SQLQuery, error) {
	// Validate primary key is provided
	if req.HourStartDateTime == 0 {
		return SQLQuery{}, fmt.Errorf("primary key field hour_start_date_time is required")
	}

	// Build query with primary key condition
	qb := NewQueryBuilder()
	qb.AddCondition("hour_start_date_time", "=", req.HourStartDateTime)

	// Build ORDER BY clause
	orderByClause := " ORDER BY hour_start_date_time, peer_geo_continent_code, custody_bucket"

	// Build column list
	columns := []string{"toUnixTimestamp(`updated_date_time`) AS `updated_date_time`", "toUnixTimestamp(`hour_start_date_time`) AS `hour_start_date_time`", "peer_geo_continent_code", "custody_bucket", "epoch_count", "peer_count"}

	// Return single record
	return BuildParameterizedQuery("fct_peer_count_by_custody_bucket_continent_hourly", columns, qb, orderByClause, 1, 0, options...)
}
