// Code generated by clickhouse-proto-gen. DO NOT EDIT.
// Scannable result row for fct_sync_committee_participation_by_validator

package clickhouse

// FctSyncCommitteeParticipationByValidatorRow is a ClickHouse-scannable result row for the fct_sync_committee_participation_by_validator table.
// Field types match the SELECT column expressions produced by
// BuildListFctSyncCommitteeParticipationByValidatorQuery and BuildGetFctSyncCommitteeParticipationByValidatorQuery: DateTime columns are unix
// timestamps, DateTime64 columns are unix microseconds, Date and large
// integer and decimal columns are strings, and FixedString columns are
// nullable. Scan rows with clickhouse-go's ScanStruct.
type FctSyncCommitteeParticipationByValidatorRow struct {
	UpdatedDateTime uint32 `ch:"updated_date_time" json:"updated_date_time"`
	Slot uint64 `ch:"slot" json:"slot"`
	SlotStartDateTime uint32 `ch:"slot_start_date_time" json:"slot_start_date_time"`
	ValidatorIndex uint32 `ch:"validator_index" json:"validator_index"`
	Participated bool `ch:"participated" json:"participated"`
}

// TableName returns the ClickHouse table this row maps to.
func (FctSyncCommitteeParticipationByValidatorRow) TableName() string {
	return "fct_sync_committee_participation_by_validator"
}

// ToProto converts the row to its protobuf message.
func (r *FctSyncCommitteeParticipationByValidatorRow) ToProto() *FctSyncCommitteeParticipationByValidator {
	p := &FctSyncCommitteeParticipationByValidator{}

	p.UpdatedDateTime = r.UpdatedDateTime
	p.Slot = r.Slot
	p.SlotStartDateTime = r.SlotStartDateTime
	p.ValidatorIndex = r.ValidatorIndex
	p.Participated = r.Participated
	return p
}
