// Code generated by clickhouse-proto-gen. DO NOT EDIT.
// Scannable result row for fct_opcode_gas_by_opcode_daily

package clickhouse

// FctOpcodeGasByOpcodeDailyRow is a ClickHouse-scannable result row for the fct_opcode_gas_by_opcode_daily table.
// Field types match the SELECT column expressions produced by
// BuildListFctOpcodeGasByOpcodeDailyQuery and BuildGetFctOpcodeGasByOpcodeDailyQuery: DateTime columns are unix
// timestamps, DateTime64 columns are unix microseconds, Date and large
// integer and decimal columns are strings, and FixedString columns are
// nullable. Scan rows with clickhouse-go's ScanStruct.
type FctOpcodeGasByOpcodeDailyRow struct {
	UpdatedDateTime uint32 `ch:"updated_date_time" json:"updated_date_time"`
	DayStartDate string `ch:"day_start_date" json:"day_start_date"`
	Opcode string `ch:"opcode" json:"opcode"`
	BlockCount uint32 `ch:"block_count" json:"block_count"`
	TotalCount uint64 `ch:"total_count" json:"total_count"`
	TotalGas uint64 `ch:"total_gas" json:"total_gas"`
	TotalErrorCount uint64 `ch:"total_error_count" json:"total_error_count"`
	AvgCountPerBlock float32 `ch:"avg_count_per_block" json:"avg_count_per_block"`
	AvgGasPerBlock float32 `ch:"avg_gas_per_block" json:"avg_gas_per_block"`
	AvgGasPerExecution float32 `ch:"avg_gas_per_execution" json:"avg_gas_per_execution"`
}

// TableName returns the ClickHouse table this row maps to.
func (FctOpcodeGasByOpcodeDailyRow) TableName() string {
	return "fct_opcode_gas_by_opcode_daily"
}

// ToProto converts the row to its protobuf message.
func (r *FctOpcodeGasByOpcodeDailyRow) ToProto() *FctOpcodeGasByOpcodeDaily {
	p := &FctOpcodeGasByOpcodeDaily{}

	p.UpdatedDateTime = r.UpdatedDateTime
	p.DayStartDate = r.DayStartDate
	p.Opcode = r.Opcode
	p.BlockCount = r.BlockCount
	p.TotalCount = r.TotalCount
	p.TotalGas = r.TotalGas
	p.TotalErrorCount = r.TotalErrorCount
	p.AvgCountPerBlock = r.AvgCountPerBlock
	p.AvgGasPerBlock = r.AvgGasPerBlock
	p.AvgGasPerExecution = r.AvgGasPerExecution
	return p
}
