// Code generated by clickhouse-proto-gen. DO NOT EDIT.
// Scannable result row for fct_attestation_vote_correctness_by_validator

package clickhouse

import (
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
)

// FctAttestationVoteCorrectnessByValidatorRow is a ClickHouse-scannable result row for the fct_attestation_vote_correctness_by_validator table.
// Field types match the SELECT column expressions produced by
// BuildListFctAttestationVoteCorrectnessByValidatorQuery and BuildGetFctAttestationVoteCorrectnessByValidatorQuery: DateTime columns are unix
// timestamps, DateTime64 columns are unix microseconds, Date and large
// integer and decimal columns are strings, and FixedString columns are
// nullable. Scan rows with clickhouse-go's ScanStruct.
type FctAttestationVoteCorrectnessByValidatorRow struct {
	UpdatedDateTime uint32 `ch:"updated_date_time" json:"updated_date_time"`
	Slot uint64 `ch:"slot" json:"slot"`
	SlotStartDateTime uint32 `ch:"slot_start_date_time" json:"slot_start_date_time"`
	ValidatorIndex uint32 `ch:"validator_index" json:"validator_index"`
	Attested bool `ch:"attested" json:"attested"`
	HeadCorrect *bool `ch:"head_correct" json:"head_correct"`
	TargetCorrect *bool `ch:"target_correct" json:"target_correct"`
	SourceCorrect *bool `ch:"source_correct" json:"source_correct"`
	InclusionDistance *uint32 `ch:"inclusion_distance" json:"inclusion_distance"`
}

// TableName returns the ClickHouse table this row maps to.
func (FctAttestationVoteCorrectnessByValidatorRow) TableName() string {
	return "fct_attestation_vote_correctness_by_validator"
}

// ToProto converts the row to its protobuf message.
func (r *FctAttestationVoteCorrectnessByValidatorRow) ToProto() *FctAttestationVoteCorrectnessByValidator {
	p := &FctAttestationVoteCorrectnessByValidator{}

	p.UpdatedDateTime = r.UpdatedDateTime
	p.Slot = r.Slot
	p.SlotStartDateTime = r.SlotStartDateTime
	p.ValidatorIndex = r.ValidatorIndex
	p.Attested = r.Attested
	if r.HeadCorrect != nil {
		p.HeadCorrect = wrapperspb.Bool(*r.HeadCorrect)
	}
	if r.TargetCorrect != nil {
		p.TargetCorrect = wrapperspb.Bool(*r.TargetCorrect)
	}
	if r.SourceCorrect != nil {
		p.SourceCorrect = wrapperspb.Bool(*r.SourceCorrect)
	}
	if r.InclusionDistance != nil {
		p.InclusionDistance = wrapperspb.UInt32(*r.InclusionDistance)
	}
	return p
}
