// Code generated by clickhouse-proto-gen. DO NOT EDIT.
// SQL query builder for fct_sync_committee_participation_by_validator

package clickhouse

import (
	"fmt"
)

// BuildListFctSyncCommitteeParticipationByValidatorQuery constructs a parameterized SQL query from a ListFctSyncCommitteeParticipationByValidatorRequest
func BuildListFctSyncCommitteeParticipationByValidatorQuery(req *ListFctSyncCommitteeParticipationByValidatorRequest, options ...QueryOption) (SQLQuery, error) {
	// Validate that at least one primary key is provided
	// Primary keys can come from base table or projections
	if req.ValidatorIndex == nil {
		return SQLQuery{}, fmt.Errorf("primary key field validator_index is required")
	}

	// Build query using QueryBuilder
	qb := NewQueryBuilder()

	// Add primary key filter
	switch filter := req.ValidatorIndex.Filter.(type) {
	case *UInt32Filter_Eq:
		qb.AddCondition("validator_index", "=", filter.Eq)
	case *UInt32Filter_Ne:
		qb.AddCondition("validator_index", "!=", filter.Ne)
	case *UInt32Filter_Lt:
		qb.AddCondition("validator_index", "<", filter.Lt)
	case *UInt32Filter_Lte:
		qb.AddCondition("validator_index", "<=", filter.Lte)
	case *UInt32Filter_Gt:
		qb.AddCondition("validator_index", ">", filter.Gt)
	case *UInt32Filter_Gte:
		qb.AddCondition("validator_index", ">=", filter.Gte)
	case *UInt32Filter_Between:
		qb.AddBetweenCondition("validator_index", filter.Between.Min, filter.Between.Max.GetValue())
	case *UInt32Filter_In:
		if len(filter.In.Values) > 0 {
			qb.AddInCondition("validator_index", UInt32SliceToInterface(filter.In.Values))
		}
	case *UInt32Filter_NotIn:
		if len(filter.NotIn.Values) > 0 {
			qb.AddNotInCondition("validator_index", UInt32SliceToInterface(filter.NotIn.Values))
		}
	default:
		// Unsupported filter type
	}

	// Add filter for column: updated_date_time
	if req.UpdatedDateTime != nil {
		switch filter := req.UpdatedDateTime.Filter.(type) {
		case *UInt32Filter_Eq:
			qb.AddCondition("updated_date_time", "=", DateTimeValue{filter.Eq})
		case *UInt32Filter_Ne:
			qb.AddCondition("updated_date_time", "!=", DateTimeValue{filter.Ne})
		case *UInt32Filter_Lt:
			qb.AddCondition("updated_date_time", "<", DateTimeValue{filter.Lt})
		case *UInt32Filter_Lte:
			qb.AddCondition("updated_date_time", "<=", DateTimeValue{filter.Lte})
		case *UInt32Filter_Gt:
			qb.AddCondition("updated_date_time", ">", DateTimeValue{filter.Gt})
		case *UInt32Filter_Gte:
			qb.AddCondition("updated_date_time", ">=", DateTimeValue{filter.Gte})
		case *UInt32Filter_Between:
			qb.AddBetweenCondition("updated_date_time", DateTimeValue{filter.Between.Min}, DateTimeValue{filter.Between.Max.GetValue()})
		case *UInt32Filter_In:
			if len(filter.In.Values) > 0 {
				converted := make([]interface{}, len(filter.In.Values))
				for i, v := range filter.In.Values {
					converted[i] = DateTimeValue{v}
				}
				qb.AddInCondition("updated_date_time", converted)
			}
		case *UInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				converted := make([]interface{}, len(filter.NotIn.Values))
				for i, v := range filter.NotIn.Values {
					converted[i] = DateTimeValue{v}
				}
				qb.AddNotInCondition("updated_date_time", converted)
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: slot
	if req.Slot != nil {
		switch filter := req.Slot.Filter.(type) {
		case *UInt64Filter_Eq:
			qb.AddCondition("slot", "=", filter.Eq)
		case *UInt64Filter_Ne:
			qb.AddCondition("slot", "!=", filter.Ne)
		case *UInt64Filter_Lt:
			qb.AddCondition("slot", "<", filter.Lt)
		case *UInt64Filter_Lte:
			qb.AddCondition("slot", "<=", filter.Lte)
		case *UInt64Filter_Gt:
			qb.AddCondition("slot", ">", filter.Gt)
		case *UInt64Filter_Gte:
			qb.AddCondition("slot", ">=", filter.Gte)
		case *UInt64Filter_Between:
			qb.AddBetweenCondition("slot", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt64Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("slot", UInt64SliceToInterface(filter.In.Values))
			}
		case *UInt64Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("slot", UInt64SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: slot_start_date_time
	if req.SlotStartDateTime != nil {
		switch filter := req.SlotStartDateTime.Filter.(type) {
		case *UInt32Filter_Eq:
			qb.AddCondition("slot_start_date_time", "=", DateTimeValue{filter.Eq})
		case *UInt32Filter_Ne:
			qb.AddCondition("slot_start_date_time", "!=", DateTimeValue{filter.Ne})
		case *UInt32Filter_Lt:
			qb.AddCondition("slot_start_date_time", "<", DateTimeValue{filter.Lt})
		case *UInt32Filter_Lte:
			qb.AddCondition("slot_start_date_time", "<=", DateTimeValue{filter.Lte})
		case *UInt32Filter_Gt:
			qb.AddCondition("slot_start_date_time", ">", DateTimeValue{filter.Gt})
		case *UInt32Filter_Gte:
			qb.AddCondition("slot_start_date_time", ">=", DateTimeValue{filter.Gte})
		case *UInt32Filter_Between:
			qb.AddBetweenCondition("slot_start_date_time", DateTimeValue{filter.Between.Min}, DateTimeValue{filter.Between.Max.GetValue()})
		case *UInt32Filter_In:
			if len(filter.In.Values) > 0 {
				converted := make([]interface{}, len(filter.In.Values))
				for i, v := range filter.In.Values {
					converted[i] = DateTimeValue{v}
				}
				qb.AddInCondition("slot_start_date_time", converted)
			}
		case *UInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				converted := make([]interface{}, len(filter.NotIn.Values))
				for i, v := range filter.NotIn.Values {
					converted[i] = DateTimeValue{v}
				}
				qb.AddNotInCondition("slot_start_date_time", converted)
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: participated
	if req.Participated != nil {
		switch filter := req.Participated.Filter.(type) {
		case *BoolFilter_Eq:
			qb.AddCondition("participated", "=", filter.Eq)
		case *BoolFilter_Ne:
			qb.AddCondition("participated", "!=", filter.Ne)
		default:
			// Unsupported filter type
		}
	}

	// Handle pagination per AIP-132
	// Validate page size
	if req.PageSize < 0 {
		return SQLQuery{}, fmt.Errorf("page_size must be non-negative, got %d", req.PageSize)
	}
	if req.PageSize > 10000 {
		return SQLQuery{}, fmt.Errorf("page_size must not exceed %d, got %d", 10000, req.PageSize)
	}

	var limit, offset uint32
	limit = 100 // Default page size
	if req.PageSize > 0 {
		limit = uint32(req.PageSize)
	}
	if req.PageToken != "" {
		decodedOffset, err := DecodePageToken(req.PageToken)
		if err != nil {
			return SQLQuery{}, fmt.Errorf("invalid page_token: %w", err)
		}
		offset = decodedOffset
	}

	// Handle custom ordering if provided
	var orderByClause string
	if req.OrderBy != "" {
		validFields := []string{"updated_date_time", "slot", "slot_start_date_time", "validator_index", "participated"}
		orderFields, err := ParseOrderBy(req.OrderBy, validFields)
		if err != nil {
			return SQLQuery{}, fmt.Errorf("invalid order_by: %w", err)
		}
		orderByClause = BuildOrderByClause(orderFields)
	} else {
		// Default sorting by primary key
		orderByClause = " ORDER BY validator_index" + ", slot_start_date_time"
	}

	// Build column list
	columns := []string{"toUnixTimestamp(`updated_date_time`) AS `updated_date_time`", "slot", "toUnixTimestamp(`slot_start_date_time`) AS `slot_start_date_time`", "validator_index", "participated"}

	return BuildParameterizedQuery("fct_sync_committee_participation_by_validator", columns, qb, orderByClause, limit, offset, options...)
}

// BuildGetFctSyncCommitteeParticipationByValidatorQuery constructs a parameterized SQL query from a GetFctSyncCommitteeParticipationByValidatorRequest
func BuildGetFctSyncCommitteeParticipationByValidatorQuery(req *GetFctSyncCommitteeParticipationByValidatorRequest, options ...QueryOption) (SQLQuery, error) {
	// Validate primary key is provided
	if req.ValidatorIndex == 0 {
		return SQLQuery{}, fmt.Errorf("primary key field validator_index is required")
	}

	// Build query with primary key condition
	qb := NewQueryBuilder()
	qb.AddCondition("validator_index", "=", req.ValidatorIndex)

	// Build ORDER BY clause
	orderByClause := " ORDER BY validator_index, slot_start_date_time"

	// Build column list
	columns := []string{"toUnixTimestamp(`updated_date_time`) AS `updated_date_time`", "slot", "toUnixTimestamp(`slot_start_date_time`) AS `slot_start_date_time`", "validator_index", "participated"}

	// Return single record
	return BuildParameterizedQuery("fct_sync_committee_participation_by_validator", columns, qb, orderByClause, 1, 0, options...)
}
