// Code generated by clickhouse-proto-gen. DO NOT EDIT.
// Scannable result row for fct_block_blob_head

package clickhouse

// FctBlockBlobHeadRow is a ClickHouse-scannable result row for the fct_block_blob_head table.
// Field types match the SELECT column expressions produced by
// BuildListFctBlockBlobHeadQuery and BuildGetFctBlockBlobHeadQuery: DateTime columns are unix
// timestamps, DateTime64 columns are unix microseconds, Date and large
// integer and decimal columns are strings, and FixedString columns are
// nullable. Scan rows with clickhouse-go's ScanStruct.
type FctBlockBlobHeadRow struct {
	UpdatedDateTime uint32 `ch:"updated_date_time" json:"updated_date_time"`
	Slot uint32 `ch:"slot" json:"slot"`
	SlotStartDateTime uint32 `ch:"slot_start_date_time" json:"slot_start_date_time"`
	Epoch uint32 `ch:"epoch" json:"epoch"`
	EpochStartDateTime uint32 `ch:"epoch_start_date_time" json:"epoch_start_date_time"`
	BlockRoot string `ch:"block_root" json:"block_root"`
	BlobIndex uint32 `ch:"blob_index" json:"blob_index"`
	VersionedHash string `ch:"versioned_hash" json:"versioned_hash"`
	KzgCommitment string `ch:"kzg_commitment" json:"kzg_commitment"`
}

// TableName returns the ClickHouse table this row maps to.
func (FctBlockBlobHeadRow) TableName() string {
	return "fct_block_blob_head"
}

// ToProto converts the row to its protobuf message.
func (r *FctBlockBlobHeadRow) ToProto() *FctBlockBlobHead {
	p := &FctBlockBlobHead{}

	p.UpdatedDateTime = r.UpdatedDateTime
	p.Slot = r.Slot
	p.SlotStartDateTime = r.SlotStartDateTime
	p.Epoch = r.Epoch
	p.EpochStartDateTime = r.EpochStartDateTime
	p.BlockRoot = r.BlockRoot
	p.BlobIndex = r.BlobIndex
	p.VersionedHash = r.VersionedHash
	p.KzgCommitment = r.KzgCommitment
	return p
}
