// Code generated by clickhouse-proto-gen. DO NOT EDIT.
// Scannable result row for fct_engine_get_blobs_by_el_client

package clickhouse

// FctEngineGetBlobsByElClientRow is a ClickHouse-scannable result row for the fct_engine_get_blobs_by_el_client table.
// Field types match the SELECT column expressions produced by
// BuildListFctEngineGetBlobsByElClientQuery and BuildGetFctEngineGetBlobsByElClientQuery: DateTime columns are unix
// timestamps, DateTime64 columns are unix microseconds, Date and large
// integer and decimal columns are strings, and FixedString columns are
// nullable. Scan rows with clickhouse-go's ScanStruct.
type FctEngineGetBlobsByElClientRow struct {
	UpdatedDateTime uint32 `ch:"updated_date_time" json:"updated_date_time"`
	Slot uint32 `ch:"slot" json:"slot"`
	SlotStartDateTime uint32 `ch:"slot_start_date_time" json:"slot_start_date_time"`
	Epoch uint32 `ch:"epoch" json:"epoch"`
	EpochStartDateTime uint32 `ch:"epoch_start_date_time" json:"epoch_start_date_time"`
	BlockRoot *string `ch:"block_root" json:"block_root"`
	MetaExecutionImplementation string `ch:"meta_execution_implementation" json:"meta_execution_implementation"`
	MetaExecutionVersion string `ch:"meta_execution_version" json:"meta_execution_version"`
	Status string `ch:"status" json:"status"`
	NodeClass string `ch:"node_class" json:"node_class"`
	ObservationCount uint32 `ch:"observation_count" json:"observation_count"`
	UniqueNodeCount uint32 `ch:"unique_node_count" json:"unique_node_count"`
	MaxRequestedCount uint32 `ch:"max_requested_count" json:"max_requested_count"`
	AvgReturnedCount float64 `ch:"avg_returned_count" json:"avg_returned_count"`
	AvgDurationMs uint64 `ch:"avg_duration_ms" json:"avg_duration_ms"`
	MedianDurationMs uint64 `ch:"median_duration_ms" json:"median_duration_ms"`
	MinDurationMs uint64 `ch:"min_duration_ms" json:"min_duration_ms"`
	MaxDurationMs uint64 `ch:"max_duration_ms" json:"max_duration_ms"`
	P95DurationMs uint64 `ch:"p95_duration_ms" json:"p95_duration_ms"`
}

// TableName returns the ClickHouse table this row maps to.
func (FctEngineGetBlobsByElClientRow) TableName() string {
	return "fct_engine_get_blobs_by_el_client"
}

// ToProto converts the row to its protobuf message.
func (r *FctEngineGetBlobsByElClientRow) ToProto() *FctEngineGetBlobsByElClient {
	p := &FctEngineGetBlobsByElClient{}

	p.UpdatedDateTime = r.UpdatedDateTime
	p.Slot = r.Slot
	p.SlotStartDateTime = r.SlotStartDateTime
	p.Epoch = r.Epoch
	p.EpochStartDateTime = r.EpochStartDateTime
	if r.BlockRoot != nil {
		p.BlockRoot = *r.BlockRoot
	}
	p.MetaExecutionImplementation = r.MetaExecutionImplementation
	p.MetaExecutionVersion = r.MetaExecutionVersion
	p.Status = r.Status
	p.NodeClass = r.NodeClass
	p.ObservationCount = r.ObservationCount
	p.UniqueNodeCount = r.UniqueNodeCount
	p.MaxRequestedCount = r.MaxRequestedCount
	p.AvgReturnedCount = r.AvgReturnedCount
	p.AvgDurationMs = r.AvgDurationMs
	p.MedianDurationMs = r.MedianDurationMs
	p.MinDurationMs = r.MinDurationMs
	p.MaxDurationMs = r.MaxDurationMs
	p.P95DurationMs = r.P95DurationMs
	return p
}
