// Code generated by clickhouse-proto-gen. DO NOT EDIT.
// Scannable result row for fct_contract_storage_state_with_expiry_by_address_hourly

package clickhouse

// FctContractStorageStateWithExpiryByAddressHourlyRow is a ClickHouse-scannable result row for the fct_contract_storage_state_with_expiry_by_address_hourly table.
// Field types match the SELECT column expressions produced by
// BuildListFctContractStorageStateWithExpiryByAddressHourlyQuery and BuildGetFctContractStorageStateWithExpiryByAddressHourlyQuery: DateTime columns are unix
// timestamps, DateTime64 columns are unix microseconds, Date and large
// integer and decimal columns are strings, and FixedString columns are
// nullable. Scan rows with clickhouse-go's ScanStruct.
type FctContractStorageStateWithExpiryByAddressHourlyRow struct {
	UpdatedDateTime uint32 `ch:"updated_date_time" json:"updated_date_time"`
	Address string `ch:"address" json:"address"`
	HourStartDateTime uint32 `ch:"hour_start_date_time" json:"hour_start_date_time"`
	ExpiryPolicy string `ch:"expiry_policy" json:"expiry_policy"`
	ActiveSlots int64 `ch:"active_slots" json:"active_slots"`
	EffectiveBytes int64 `ch:"effective_bytes" json:"effective_bytes"`
}

// TableName returns the ClickHouse table this row maps to.
func (FctContractStorageStateWithExpiryByAddressHourlyRow) TableName() string {
	return "fct_contract_storage_state_with_expiry_by_address_hourly"
}

// ToProto converts the row to its protobuf message.
func (r *FctContractStorageStateWithExpiryByAddressHourlyRow) ToProto() *FctContractStorageStateWithExpiryByAddressHourly {
	p := &FctContractStorageStateWithExpiryByAddressHourly{}

	p.UpdatedDateTime = r.UpdatedDateTime
	p.Address = r.Address
	p.HourStartDateTime = r.HourStartDateTime
	p.ExpiryPolicy = r.ExpiryPolicy
	p.ActiveSlots = r.ActiveSlots
	p.EffectiveBytes = r.EffectiveBytes
	return p
}
