// Code generated by clickhouse-proto-gen. DO NOT EDIT.
// Scannable result row for fct_block_payload_ptc_vote_head

package clickhouse

// FctBlockPayloadPtcVoteHeadRow is a ClickHouse-scannable result row for the fct_block_payload_ptc_vote_head table.
// Field types match the SELECT column expressions produced by
// BuildListFctBlockPayloadPtcVoteHeadQuery and BuildGetFctBlockPayloadPtcVoteHeadQuery: DateTime columns are unix
// timestamps, DateTime64 columns are unix microseconds, Date and large
// integer and decimal columns are strings, and FixedString columns are
// nullable. Scan rows with clickhouse-go's ScanStruct.
type FctBlockPayloadPtcVoteHeadRow struct {
	UpdatedDateTime uint32 `ch:"updated_date_time" json:"updated_date_time"`
	Slot uint32 `ch:"slot" json:"slot"`
	SlotStartDateTime uint32 `ch:"slot_start_date_time" json:"slot_start_date_time"`
	Epoch uint32 `ch:"epoch" json:"epoch"`
	EpochStartDateTime uint32 `ch:"epoch_start_date_time" json:"epoch_start_date_time"`
	BlockRoot string `ch:"block_root" json:"block_root"`
	PtcValidatorsSeen uint32 `ch:"ptc_validators_seen" json:"ptc_validators_seen"`
	PayloadPresentVotes uint32 `ch:"payload_present_votes" json:"payload_present_votes"`
	BlobDataAvailableVotes uint32 `ch:"blob_data_available_votes" json:"blob_data_available_votes"`
	FirstSeenSlotStartDiff uint32 `ch:"first_seen_slot_start_diff" json:"first_seen_slot_start_diff"`
	LastSeenSlotStartDiff uint32 `ch:"last_seen_slot_start_diff" json:"last_seen_slot_start_diff"`
}

// TableName returns the ClickHouse table this row maps to.
func (FctBlockPayloadPtcVoteHeadRow) TableName() string {
	return "fct_block_payload_ptc_vote_head"
}

// ToProto converts the row to its protobuf message.
func (r *FctBlockPayloadPtcVoteHeadRow) ToProto() *FctBlockPayloadPtcVoteHead {
	p := &FctBlockPayloadPtcVoteHead{}

	p.UpdatedDateTime = r.UpdatedDateTime
	p.Slot = r.Slot
	p.SlotStartDateTime = r.SlotStartDateTime
	p.Epoch = r.Epoch
	p.EpochStartDateTime = r.EpochStartDateTime
	p.BlockRoot = r.BlockRoot
	p.PtcValidatorsSeen = r.PtcValidatorsSeen
	p.PayloadPresentVotes = r.PayloadPresentVotes
	p.BlobDataAvailableVotes = r.BlobDataAvailableVotes
	p.FirstSeenSlotStartDiff = r.FirstSeenSlotStartDiff
	p.LastSeenSlotStartDiff = r.LastSeenSlotStartDiff
	return p
}
