// Code generated by clickhouse-proto-gen. DO NOT EDIT.
// SQL query builder for fct_blob_count_hourly

package clickhouse

import (
	"fmt"
)

// BuildListFctBlobCountHourlyQuery constructs a parameterized SQL query from a ListFctBlobCountHourlyRequest
func BuildListFctBlobCountHourlyQuery(req *ListFctBlobCountHourlyRequest, options ...QueryOption) (SQLQuery, error) {
	// Validate that at least one primary key is provided
	// Primary keys can come from base table or projections
	if req.HourStartDateTime == nil {
		return SQLQuery{}, fmt.Errorf("primary key field hour_start_date_time is required")
	}

	// Build query using QueryBuilder
	qb := NewQueryBuilder()

	// Add primary key filter
	switch filter := req.HourStartDateTime.Filter.(type) {
	case *UInt32Filter_Eq:
		qb.AddCondition("hour_start_date_time", "=", DateTimeValue{filter.Eq})
	case *UInt32Filter_Ne:
		qb.AddCondition("hour_start_date_time", "!=", DateTimeValue{filter.Ne})
	case *UInt32Filter_Lt:
		qb.AddCondition("hour_start_date_time", "<", DateTimeValue{filter.Lt})
	case *UInt32Filter_Lte:
		qb.AddCondition("hour_start_date_time", "<=", DateTimeValue{filter.Lte})
	case *UInt32Filter_Gt:
		qb.AddCondition("hour_start_date_time", ">", DateTimeValue{filter.Gt})
	case *UInt32Filter_Gte:
		qb.AddCondition("hour_start_date_time", ">=", DateTimeValue{filter.Gte})
	case *UInt32Filter_Between:
		qb.AddBetweenCondition("hour_start_date_time", DateTimeValue{filter.Between.Min}, DateTimeValue{filter.Between.Max.GetValue()})
	case *UInt32Filter_In:
		if len(filter.In.Values) > 0 {
			converted := make([]interface{}, len(filter.In.Values))
			for i, v := range filter.In.Values {
				converted[i] = DateTimeValue{v}
			}
			qb.AddInCondition("hour_start_date_time", converted)
		}
	case *UInt32Filter_NotIn:
		if len(filter.NotIn.Values) > 0 {
			converted := make([]interface{}, len(filter.NotIn.Values))
			for i, v := range filter.NotIn.Values {
				converted[i] = DateTimeValue{v}
			}
			qb.AddNotInCondition("hour_start_date_time", converted)
		}
	default:
		// Unsupported filter type
	}

	// Add filter for column: updated_date_time
	if req.UpdatedDateTime != nil {
		switch filter := req.UpdatedDateTime.Filter.(type) {
		case *UInt32Filter_Eq:
			qb.AddCondition("updated_date_time", "=", DateTimeValue{filter.Eq})
		case *UInt32Filter_Ne:
			qb.AddCondition("updated_date_time", "!=", DateTimeValue{filter.Ne})
		case *UInt32Filter_Lt:
			qb.AddCondition("updated_date_time", "<", DateTimeValue{filter.Lt})
		case *UInt32Filter_Lte:
			qb.AddCondition("updated_date_time", "<=", DateTimeValue{filter.Lte})
		case *UInt32Filter_Gt:
			qb.AddCondition("updated_date_time", ">", DateTimeValue{filter.Gt})
		case *UInt32Filter_Gte:
			qb.AddCondition("updated_date_time", ">=", DateTimeValue{filter.Gte})
		case *UInt32Filter_Between:
			qb.AddBetweenCondition("updated_date_time", DateTimeValue{filter.Between.Min}, DateTimeValue{filter.Between.Max.GetValue()})
		case *UInt32Filter_In:
			if len(filter.In.Values) > 0 {
				converted := make([]interface{}, len(filter.In.Values))
				for i, v := range filter.In.Values {
					converted[i] = DateTimeValue{v}
				}
				qb.AddInCondition("updated_date_time", converted)
			}
		case *UInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				converted := make([]interface{}, len(filter.NotIn.Values))
				for i, v := range filter.NotIn.Values {
					converted[i] = DateTimeValue{v}
				}
				qb.AddNotInCondition("updated_date_time", converted)
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: block_count
	if req.BlockCount != nil {
		switch filter := req.BlockCount.Filter.(type) {
		case *UInt32Filter_Eq:
			qb.AddCondition("block_count", "=", filter.Eq)
		case *UInt32Filter_Ne:
			qb.AddCondition("block_count", "!=", filter.Ne)
		case *UInt32Filter_Lt:
			qb.AddCondition("block_count", "<", filter.Lt)
		case *UInt32Filter_Lte:
			qb.AddCondition("block_count", "<=", filter.Lte)
		case *UInt32Filter_Gt:
			qb.AddCondition("block_count", ">", filter.Gt)
		case *UInt32Filter_Gte:
			qb.AddCondition("block_count", ">=", filter.Gte)
		case *UInt32Filter_Between:
			qb.AddBetweenCondition("block_count", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt32Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("block_count", UInt32SliceToInterface(filter.In.Values))
			}
		case *UInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("block_count", UInt32SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: total_blobs
	if req.TotalBlobs != nil {
		switch filter := req.TotalBlobs.Filter.(type) {
		case *UInt64Filter_Eq:
			qb.AddCondition("total_blobs", "=", filter.Eq)
		case *UInt64Filter_Ne:
			qb.AddCondition("total_blobs", "!=", filter.Ne)
		case *UInt64Filter_Lt:
			qb.AddCondition("total_blobs", "<", filter.Lt)
		case *UInt64Filter_Lte:
			qb.AddCondition("total_blobs", "<=", filter.Lte)
		case *UInt64Filter_Gt:
			qb.AddCondition("total_blobs", ">", filter.Gt)
		case *UInt64Filter_Gte:
			qb.AddCondition("total_blobs", ">=", filter.Gte)
		case *UInt64Filter_Between:
			qb.AddBetweenCondition("total_blobs", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt64Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("total_blobs", UInt64SliceToInterface(filter.In.Values))
			}
		case *UInt64Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("total_blobs", UInt64SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: avg_blob_count

	// Add filter for column: min_blob_count
	if req.MinBlobCount != nil {
		switch filter := req.MinBlobCount.Filter.(type) {
		case *UInt32Filter_Eq:
			qb.AddCondition("min_blob_count", "=", filter.Eq)
		case *UInt32Filter_Ne:
			qb.AddCondition("min_blob_count", "!=", filter.Ne)
		case *UInt32Filter_Lt:
			qb.AddCondition("min_blob_count", "<", filter.Lt)
		case *UInt32Filter_Lte:
			qb.AddCondition("min_blob_count", "<=", filter.Lte)
		case *UInt32Filter_Gt:
			qb.AddCondition("min_blob_count", ">", filter.Gt)
		case *UInt32Filter_Gte:
			qb.AddCondition("min_blob_count", ">=", filter.Gte)
		case *UInt32Filter_Between:
			qb.AddBetweenCondition("min_blob_count", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt32Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("min_blob_count", UInt32SliceToInterface(filter.In.Values))
			}
		case *UInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("min_blob_count", UInt32SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: max_blob_count
	if req.MaxBlobCount != nil {
		switch filter := req.MaxBlobCount.Filter.(type) {
		case *UInt32Filter_Eq:
			qb.AddCondition("max_blob_count", "=", filter.Eq)
		case *UInt32Filter_Ne:
			qb.AddCondition("max_blob_count", "!=", filter.Ne)
		case *UInt32Filter_Lt:
			qb.AddCondition("max_blob_count", "<", filter.Lt)
		case *UInt32Filter_Lte:
			qb.AddCondition("max_blob_count", "<=", filter.Lte)
		case *UInt32Filter_Gt:
			qb.AddCondition("max_blob_count", ">", filter.Gt)
		case *UInt32Filter_Gte:
			qb.AddCondition("max_blob_count", ">=", filter.Gte)
		case *UInt32Filter_Between:
			qb.AddBetweenCondition("max_blob_count", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt32Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("max_blob_count", UInt32SliceToInterface(filter.In.Values))
			}
		case *UInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("max_blob_count", UInt32SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: p05_blob_count

	// Add filter for column: p50_blob_count

	// Add filter for column: p95_blob_count

	// Add filter for column: stddev_blob_count

	// Add filter for column: upper_band_blob_count

	// Add filter for column: lower_band_blob_count

	// Add filter for column: moving_avg_blob_count

	// Handle pagination per AIP-132
	// Validate page size
	if req.PageSize < 0 {
		return SQLQuery{}, fmt.Errorf("page_size must be non-negative, got %d", req.PageSize)
	}
	if req.PageSize > 10000 {
		return SQLQuery{}, fmt.Errorf("page_size must not exceed %d, got %d", 10000, req.PageSize)
	}

	var limit, offset uint32
	limit = 100 // Default page size
	if req.PageSize > 0 {
		limit = uint32(req.PageSize)
	}
	if req.PageToken != "" {
		decodedOffset, err := DecodePageToken(req.PageToken)
		if err != nil {
			return SQLQuery{}, fmt.Errorf("invalid page_token: %w", err)
		}
		offset = decodedOffset
	}

	// Handle custom ordering if provided
	var orderByClause string
	if req.OrderBy != "" {
		validFields := []string{"updated_date_time", "hour_start_date_time", "block_count", "total_blobs", "avg_blob_count", "min_blob_count", "max_blob_count", "p05_blob_count", "p50_blob_count", "p95_blob_count", "stddev_blob_count", "upper_band_blob_count", "lower_band_blob_count", "moving_avg_blob_count"}
		orderFields, err := ParseOrderBy(req.OrderBy, validFields)
		if err != nil {
			return SQLQuery{}, fmt.Errorf("invalid order_by: %w", err)
		}
		orderByClause = BuildOrderByClause(orderFields)
	} else {
		// Default sorting by primary key
		orderByClause = " ORDER BY hour_start_date_time"
	}

	// Build column list
	columns := []string{"toUnixTimestamp(`updated_date_time`) AS `updated_date_time`", "toUnixTimestamp(`hour_start_date_time`) AS `hour_start_date_time`", "block_count", "total_blobs", "avg_blob_count", "min_blob_count", "max_blob_count", "p05_blob_count", "p50_blob_count", "p95_blob_count", "stddev_blob_count", "upper_band_blob_count", "lower_band_blob_count", "moving_avg_blob_count"}

	return BuildParameterizedQuery("fct_blob_count_hourly", columns, qb, orderByClause, limit, offset, options...)
}

// BuildGetFctBlobCountHourlyQuery constructs a parameterized SQL query from a GetFctBlobCountHourlyRequest
func BuildGetFctBlobCountHourlyQuery(req *GetFctBlobCountHourlyRequest, options ...QueryOption) (SQLQuery, error) {
	// Validate primary key is provided
	if req.HourStartDateTime == 0 {
		return SQLQuery{}, fmt.Errorf("primary key field hour_start_date_time is required")
	}

	// Build query with primary key condition
	qb := NewQueryBuilder()
	qb.AddCondition("hour_start_date_time", "=", req.HourStartDateTime)

	// Build ORDER BY clause
	orderByClause := " ORDER BY hour_start_date_time"

	// Build column list
	columns := []string{"toUnixTimestamp(`updated_date_time`) AS `updated_date_time`", "toUnixTimestamp(`hour_start_date_time`) AS `hour_start_date_time`", "block_count", "total_blobs", "avg_blob_count", "min_blob_count", "max_blob_count", "p05_blob_count", "p50_blob_count", "p95_blob_count", "stddev_blob_count", "upper_band_blob_count", "lower_band_blob_count", "moving_avg_blob_count"}

	// Return single record
	return BuildParameterizedQuery("fct_blob_count_hourly", columns, qb, orderByClause, 1, 0, options...)
}
