// Code generated by clickhouse-proto-gen. DO NOT EDIT.
// Scannable result row for fct_contract_storage_state_by_block_hourly

package clickhouse

// FctContractStorageStateByBlockHourlyRow is a ClickHouse-scannable result row for the fct_contract_storage_state_by_block_hourly table.
// Field types match the SELECT column expressions produced by
// BuildListFctContractStorageStateByBlockHourlyQuery and BuildGetFctContractStorageStateByBlockHourlyQuery: DateTime columns are unix
// timestamps, DateTime64 columns are unix microseconds, Date and large
// integer and decimal columns are strings, and FixedString columns are
// nullable. Scan rows with clickhouse-go's ScanStruct.
type FctContractStorageStateByBlockHourlyRow struct {
	UpdatedDateTime uint32 `ch:"updated_date_time" json:"updated_date_time"`
	HourStartDateTime uint32 `ch:"hour_start_date_time" json:"hour_start_date_time"`
	ActiveSlots int64 `ch:"active_slots" json:"active_slots"`
	EffectiveBytes int64 `ch:"effective_bytes" json:"effective_bytes"`
	ActiveContracts int64 `ch:"active_contracts" json:"active_contracts"`
}

// TableName returns the ClickHouse table this row maps to.
func (FctContractStorageStateByBlockHourlyRow) TableName() string {
	return "fct_contract_storage_state_by_block_hourly"
}

// ToProto converts the row to its protobuf message.
func (r *FctContractStorageStateByBlockHourlyRow) ToProto() *FctContractStorageStateByBlockHourly {
	p := &FctContractStorageStateByBlockHourly{}

	p.UpdatedDateTime = r.UpdatedDateTime
	p.HourStartDateTime = r.HourStartDateTime
	p.ActiveSlots = r.ActiveSlots
	p.EffectiveBytes = r.EffectiveBytes
	p.ActiveContracts = r.ActiveContracts
	return p
}
