// Code generated by clickhouse-proto-gen. DO NOT EDIT.
// SQL query builder for fct_engine_get_blobs_status_daily

package clickhouse

import (
	"fmt"
)

// BuildListFctEngineGetBlobsStatusDailyQuery constructs a parameterized SQL query from a ListFctEngineGetBlobsStatusDailyRequest
func BuildListFctEngineGetBlobsStatusDailyQuery(req *ListFctEngineGetBlobsStatusDailyRequest, options ...QueryOption) (SQLQuery, error) {
	// Validate that at least one primary key is provided
	// Primary keys can come from base table or projections
	if req.DayStartDate == nil {
		return SQLQuery{}, fmt.Errorf("primary key field day_start_date is required")
	}

	// Build query using QueryBuilder
	qb := NewQueryBuilder()

	// Add primary key filter
	switch filter := req.DayStartDate.Filter.(type) {
	case *StringFilter_Eq:
		qb.AddCondition("day_start_date", "=", filter.Eq)
	case *StringFilter_Ne:
		qb.AddCondition("day_start_date", "!=", filter.Ne)
	case *StringFilter_Contains:
		qb.AddLikeCondition("day_start_date", "%" + filter.Contains + "%")
	case *StringFilter_StartsWith:
		qb.AddLikeCondition("day_start_date", filter.StartsWith + "%")
	case *StringFilter_EndsWith:
		qb.AddLikeCondition("day_start_date", "%" + filter.EndsWith)
	case *StringFilter_Like:
		qb.AddLikeCondition("day_start_date", filter.Like)
	case *StringFilter_NotLike:
		qb.AddNotLikeCondition("day_start_date", filter.NotLike)
	case *StringFilter_In:
		if len(filter.In.Values) > 0 {
			qb.AddInCondition("day_start_date", StringSliceToInterface(filter.In.Values))
		}
	case *StringFilter_NotIn:
		if len(filter.NotIn.Values) > 0 {
			qb.AddNotInCondition("day_start_date", StringSliceToInterface(filter.NotIn.Values))
		}
	default:
		// Unsupported filter type
	}

	// Add filter for column: updated_date_time
	if req.UpdatedDateTime != nil {
		switch filter := req.UpdatedDateTime.Filter.(type) {
		case *UInt32Filter_Eq:
			qb.AddCondition("updated_date_time", "=", DateTimeValue{filter.Eq})
		case *UInt32Filter_Ne:
			qb.AddCondition("updated_date_time", "!=", DateTimeValue{filter.Ne})
		case *UInt32Filter_Lt:
			qb.AddCondition("updated_date_time", "<", DateTimeValue{filter.Lt})
		case *UInt32Filter_Lte:
			qb.AddCondition("updated_date_time", "<=", DateTimeValue{filter.Lte})
		case *UInt32Filter_Gt:
			qb.AddCondition("updated_date_time", ">", DateTimeValue{filter.Gt})
		case *UInt32Filter_Gte:
			qb.AddCondition("updated_date_time", ">=", DateTimeValue{filter.Gte})
		case *UInt32Filter_Between:
			qb.AddBetweenCondition("updated_date_time", DateTimeValue{filter.Between.Min}, DateTimeValue{filter.Between.Max.GetValue()})
		case *UInt32Filter_In:
			if len(filter.In.Values) > 0 {
				converted := make([]interface{}, len(filter.In.Values))
				for i, v := range filter.In.Values {
					converted[i] = DateTimeValue{v}
				}
				qb.AddInCondition("updated_date_time", converted)
			}
		case *UInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				converted := make([]interface{}, len(filter.NotIn.Values))
				for i, v := range filter.NotIn.Values {
					converted[i] = DateTimeValue{v}
				}
				qb.AddNotInCondition("updated_date_time", converted)
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: node_class
	if req.NodeClass != nil {
		switch filter := req.NodeClass.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("node_class", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("node_class", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("node_class", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("node_class", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("node_class", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("node_class", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("node_class", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("node_class", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("node_class", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: slot_count
	if req.SlotCount != nil {
		switch filter := req.SlotCount.Filter.(type) {
		case *UInt32Filter_Eq:
			qb.AddCondition("slot_count", "=", filter.Eq)
		case *UInt32Filter_Ne:
			qb.AddCondition("slot_count", "!=", filter.Ne)
		case *UInt32Filter_Lt:
			qb.AddCondition("slot_count", "<", filter.Lt)
		case *UInt32Filter_Lte:
			qb.AddCondition("slot_count", "<=", filter.Lte)
		case *UInt32Filter_Gt:
			qb.AddCondition("slot_count", ">", filter.Gt)
		case *UInt32Filter_Gte:
			qb.AddCondition("slot_count", ">=", filter.Gte)
		case *UInt32Filter_Between:
			qb.AddBetweenCondition("slot_count", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt32Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("slot_count", UInt32SliceToInterface(filter.In.Values))
			}
		case *UInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("slot_count", UInt32SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: observation_count
	if req.ObservationCount != nil {
		switch filter := req.ObservationCount.Filter.(type) {
		case *UInt64Filter_Eq:
			qb.AddCondition("observation_count", "=", filter.Eq)
		case *UInt64Filter_Ne:
			qb.AddCondition("observation_count", "!=", filter.Ne)
		case *UInt64Filter_Lt:
			qb.AddCondition("observation_count", "<", filter.Lt)
		case *UInt64Filter_Lte:
			qb.AddCondition("observation_count", "<=", filter.Lte)
		case *UInt64Filter_Gt:
			qb.AddCondition("observation_count", ">", filter.Gt)
		case *UInt64Filter_Gte:
			qb.AddCondition("observation_count", ">=", filter.Gte)
		case *UInt64Filter_Between:
			qb.AddBetweenCondition("observation_count", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt64Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("observation_count", UInt64SliceToInterface(filter.In.Values))
			}
		case *UInt64Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("observation_count", UInt64SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: success_count
	if req.SuccessCount != nil {
		switch filter := req.SuccessCount.Filter.(type) {
		case *UInt64Filter_Eq:
			qb.AddCondition("success_count", "=", filter.Eq)
		case *UInt64Filter_Ne:
			qb.AddCondition("success_count", "!=", filter.Ne)
		case *UInt64Filter_Lt:
			qb.AddCondition("success_count", "<", filter.Lt)
		case *UInt64Filter_Lte:
			qb.AddCondition("success_count", "<=", filter.Lte)
		case *UInt64Filter_Gt:
			qb.AddCondition("success_count", ">", filter.Gt)
		case *UInt64Filter_Gte:
			qb.AddCondition("success_count", ">=", filter.Gte)
		case *UInt64Filter_Between:
			qb.AddBetweenCondition("success_count", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt64Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("success_count", UInt64SliceToInterface(filter.In.Values))
			}
		case *UInt64Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("success_count", UInt64SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: partial_count
	if req.PartialCount != nil {
		switch filter := req.PartialCount.Filter.(type) {
		case *UInt64Filter_Eq:
			qb.AddCondition("partial_count", "=", filter.Eq)
		case *UInt64Filter_Ne:
			qb.AddCondition("partial_count", "!=", filter.Ne)
		case *UInt64Filter_Lt:
			qb.AddCondition("partial_count", "<", filter.Lt)
		case *UInt64Filter_Lte:
			qb.AddCondition("partial_count", "<=", filter.Lte)
		case *UInt64Filter_Gt:
			qb.AddCondition("partial_count", ">", filter.Gt)
		case *UInt64Filter_Gte:
			qb.AddCondition("partial_count", ">=", filter.Gte)
		case *UInt64Filter_Between:
			qb.AddBetweenCondition("partial_count", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt64Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("partial_count", UInt64SliceToInterface(filter.In.Values))
			}
		case *UInt64Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("partial_count", UInt64SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: empty_count
	if req.EmptyCount != nil {
		switch filter := req.EmptyCount.Filter.(type) {
		case *UInt64Filter_Eq:
			qb.AddCondition("empty_count", "=", filter.Eq)
		case *UInt64Filter_Ne:
			qb.AddCondition("empty_count", "!=", filter.Ne)
		case *UInt64Filter_Lt:
			qb.AddCondition("empty_count", "<", filter.Lt)
		case *UInt64Filter_Lte:
			qb.AddCondition("empty_count", "<=", filter.Lte)
		case *UInt64Filter_Gt:
			qb.AddCondition("empty_count", ">", filter.Gt)
		case *UInt64Filter_Gte:
			qb.AddCondition("empty_count", ">=", filter.Gte)
		case *UInt64Filter_Between:
			qb.AddBetweenCondition("empty_count", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt64Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("empty_count", UInt64SliceToInterface(filter.In.Values))
			}
		case *UInt64Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("empty_count", UInt64SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: unsupported_count
	if req.UnsupportedCount != nil {
		switch filter := req.UnsupportedCount.Filter.(type) {
		case *UInt64Filter_Eq:
			qb.AddCondition("unsupported_count", "=", filter.Eq)
		case *UInt64Filter_Ne:
			qb.AddCondition("unsupported_count", "!=", filter.Ne)
		case *UInt64Filter_Lt:
			qb.AddCondition("unsupported_count", "<", filter.Lt)
		case *UInt64Filter_Lte:
			qb.AddCondition("unsupported_count", "<=", filter.Lte)
		case *UInt64Filter_Gt:
			qb.AddCondition("unsupported_count", ">", filter.Gt)
		case *UInt64Filter_Gte:
			qb.AddCondition("unsupported_count", ">=", filter.Gte)
		case *UInt64Filter_Between:
			qb.AddBetweenCondition("unsupported_count", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt64Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("unsupported_count", UInt64SliceToInterface(filter.In.Values))
			}
		case *UInt64Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("unsupported_count", UInt64SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: error_count
	if req.ErrorCount != nil {
		switch filter := req.ErrorCount.Filter.(type) {
		case *UInt64Filter_Eq:
			qb.AddCondition("error_count", "=", filter.Eq)
		case *UInt64Filter_Ne:
			qb.AddCondition("error_count", "!=", filter.Ne)
		case *UInt64Filter_Lt:
			qb.AddCondition("error_count", "<", filter.Lt)
		case *UInt64Filter_Lte:
			qb.AddCondition("error_count", "<=", filter.Lte)
		case *UInt64Filter_Gt:
			qb.AddCondition("error_count", ">", filter.Gt)
		case *UInt64Filter_Gte:
			qb.AddCondition("error_count", ">=", filter.Gte)
		case *UInt64Filter_Between:
			qb.AddBetweenCondition("error_count", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt64Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("error_count", UInt64SliceToInterface(filter.In.Values))
			}
		case *UInt64Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("error_count", UInt64SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: success_pct

	// Add filter for column: avg_duration_ms
	if req.AvgDurationMs != nil {
		switch filter := req.AvgDurationMs.Filter.(type) {
		case *UInt64Filter_Eq:
			qb.AddCondition("avg_duration_ms", "=", filter.Eq)
		case *UInt64Filter_Ne:
			qb.AddCondition("avg_duration_ms", "!=", filter.Ne)
		case *UInt64Filter_Lt:
			qb.AddCondition("avg_duration_ms", "<", filter.Lt)
		case *UInt64Filter_Lte:
			qb.AddCondition("avg_duration_ms", "<=", filter.Lte)
		case *UInt64Filter_Gt:
			qb.AddCondition("avg_duration_ms", ">", filter.Gt)
		case *UInt64Filter_Gte:
			qb.AddCondition("avg_duration_ms", ">=", filter.Gte)
		case *UInt64Filter_Between:
			qb.AddBetweenCondition("avg_duration_ms", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt64Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("avg_duration_ms", UInt64SliceToInterface(filter.In.Values))
			}
		case *UInt64Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("avg_duration_ms", UInt64SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: avg_p50_duration_ms
	if req.AvgP50DurationMs != nil {
		switch filter := req.AvgP50DurationMs.Filter.(type) {
		case *UInt64Filter_Eq:
			qb.AddCondition("avg_p50_duration_ms", "=", filter.Eq)
		case *UInt64Filter_Ne:
			qb.AddCondition("avg_p50_duration_ms", "!=", filter.Ne)
		case *UInt64Filter_Lt:
			qb.AddCondition("avg_p50_duration_ms", "<", filter.Lt)
		case *UInt64Filter_Lte:
			qb.AddCondition("avg_p50_duration_ms", "<=", filter.Lte)
		case *UInt64Filter_Gt:
			qb.AddCondition("avg_p50_duration_ms", ">", filter.Gt)
		case *UInt64Filter_Gte:
			qb.AddCondition("avg_p50_duration_ms", ">=", filter.Gte)
		case *UInt64Filter_Between:
			qb.AddBetweenCondition("avg_p50_duration_ms", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt64Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("avg_p50_duration_ms", UInt64SliceToInterface(filter.In.Values))
			}
		case *UInt64Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("avg_p50_duration_ms", UInt64SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: avg_p95_duration_ms
	if req.AvgP95DurationMs != nil {
		switch filter := req.AvgP95DurationMs.Filter.(type) {
		case *UInt64Filter_Eq:
			qb.AddCondition("avg_p95_duration_ms", "=", filter.Eq)
		case *UInt64Filter_Ne:
			qb.AddCondition("avg_p95_duration_ms", "!=", filter.Ne)
		case *UInt64Filter_Lt:
			qb.AddCondition("avg_p95_duration_ms", "<", filter.Lt)
		case *UInt64Filter_Lte:
			qb.AddCondition("avg_p95_duration_ms", "<=", filter.Lte)
		case *UInt64Filter_Gt:
			qb.AddCondition("avg_p95_duration_ms", ">", filter.Gt)
		case *UInt64Filter_Gte:
			qb.AddCondition("avg_p95_duration_ms", ">=", filter.Gte)
		case *UInt64Filter_Between:
			qb.AddBetweenCondition("avg_p95_duration_ms", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt64Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("avg_p95_duration_ms", UInt64SliceToInterface(filter.In.Values))
			}
		case *UInt64Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("avg_p95_duration_ms", UInt64SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: max_duration_ms
	if req.MaxDurationMs != nil {
		switch filter := req.MaxDurationMs.Filter.(type) {
		case *UInt64Filter_Eq:
			qb.AddCondition("max_duration_ms", "=", filter.Eq)
		case *UInt64Filter_Ne:
			qb.AddCondition("max_duration_ms", "!=", filter.Ne)
		case *UInt64Filter_Lt:
			qb.AddCondition("max_duration_ms", "<", filter.Lt)
		case *UInt64Filter_Lte:
			qb.AddCondition("max_duration_ms", "<=", filter.Lte)
		case *UInt64Filter_Gt:
			qb.AddCondition("max_duration_ms", ">", filter.Gt)
		case *UInt64Filter_Gte:
			qb.AddCondition("max_duration_ms", ">=", filter.Gte)
		case *UInt64Filter_Between:
			qb.AddBetweenCondition("max_duration_ms", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt64Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("max_duration_ms", UInt64SliceToInterface(filter.In.Values))
			}
		case *UInt64Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("max_duration_ms", UInt64SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Handle pagination per AIP-132
	// Validate page size
	if req.PageSize < 0 {
		return SQLQuery{}, fmt.Errorf("page_size must be non-negative, got %d", req.PageSize)
	}
	if req.PageSize > 10000 {
		return SQLQuery{}, fmt.Errorf("page_size must not exceed %d, got %d", 10000, req.PageSize)
	}

	var limit, offset uint32
	limit = 100 // Default page size
	if req.PageSize > 0 {
		limit = uint32(req.PageSize)
	}
	if req.PageToken != "" {
		decodedOffset, err := DecodePageToken(req.PageToken)
		if err != nil {
			return SQLQuery{}, fmt.Errorf("invalid page_token: %w", err)
		}
		offset = decodedOffset
	}

	// Handle custom ordering if provided
	var orderByClause string
	if req.OrderBy != "" {
		validFields := []string{"updated_date_time", "day_start_date", "node_class", "slot_count", "observation_count", "success_count", "partial_count", "empty_count", "unsupported_count", "error_count", "success_pct", "avg_duration_ms", "avg_p50_duration_ms", "avg_p95_duration_ms", "max_duration_ms"}
		orderFields, err := ParseOrderBy(req.OrderBy, validFields)
		if err != nil {
			return SQLQuery{}, fmt.Errorf("invalid order_by: %w", err)
		}
		orderByClause = BuildOrderByClause(orderFields)
	} else {
		// Default sorting by primary key
		orderByClause = " ORDER BY day_start_date" + ", node_class"
	}

	// Build column list
	columns := []string{"toUnixTimestamp(`updated_date_time`) AS `updated_date_time`", "toString(`day_start_date`) AS `day_start_date`", "node_class", "slot_count", "observation_count", "success_count", "partial_count", "empty_count", "unsupported_count", "error_count", "success_pct", "avg_duration_ms", "avg_p50_duration_ms", "avg_p95_duration_ms", "max_duration_ms"}

	return BuildParameterizedQuery("fct_engine_get_blobs_status_daily", columns, qb, orderByClause, limit, offset, options...)
}

// BuildGetFctEngineGetBlobsStatusDailyQuery constructs a parameterized SQL query from a GetFctEngineGetBlobsStatusDailyRequest
func BuildGetFctEngineGetBlobsStatusDailyQuery(req *GetFctEngineGetBlobsStatusDailyRequest, options ...QueryOption) (SQLQuery, error) {
	// Validate primary key is provided
	if req.DayStartDate == "" {
		return SQLQuery{}, fmt.Errorf("primary key field day_start_date is required")
	}

	// Build query with primary key condition
	qb := NewQueryBuilder()
	qb.AddCondition("day_start_date", "=", req.DayStartDate)

	// Build ORDER BY clause
	orderByClause := " ORDER BY day_start_date, node_class"

	// Build column list
	columns := []string{"toUnixTimestamp(`updated_date_time`) AS `updated_date_time`", "toString(`day_start_date`) AS `day_start_date`", "node_class", "slot_count", "observation_count", "success_count", "partial_count", "empty_count", "unsupported_count", "error_count", "success_pct", "avg_duration_ms", "avg_p50_duration_ms", "avg_p95_duration_ms", "max_duration_ms"}

	// Return single record
	return BuildParameterizedQuery("fct_engine_get_blobs_status_daily", columns, qb, orderByClause, 1, 0, options...)
}
