// Code generated by clickhouse-proto-gen. DO NOT EDIT.
// SQL query builder for fct_contract_storage_state_by_address_daily

package clickhouse

import (
	"fmt"
)

// BuildListFctContractStorageStateByAddressDailyQuery constructs a parameterized SQL query from a ListFctContractStorageStateByAddressDailyRequest
func BuildListFctContractStorageStateByAddressDailyQuery(req *ListFctContractStorageStateByAddressDailyRequest, options ...QueryOption) (SQLQuery, error) {
	// Validate that at least one primary key is provided
	// Primary keys can come from base table or projections
	if req.Address == nil {
		return SQLQuery{}, fmt.Errorf("primary key field address is required")
	}

	// Build query using QueryBuilder
	qb := NewQueryBuilder()

	// Add primary key filter
	switch filter := req.Address.Filter.(type) {
	case *StringFilter_Eq:
		qb.AddCondition("address", "=", filter.Eq)
	case *StringFilter_Ne:
		qb.AddCondition("address", "!=", filter.Ne)
	case *StringFilter_Contains:
		qb.AddLikeCondition("address", "%" + filter.Contains + "%")
	case *StringFilter_StartsWith:
		qb.AddLikeCondition("address", filter.StartsWith + "%")
	case *StringFilter_EndsWith:
		qb.AddLikeCondition("address", "%" + filter.EndsWith)
	case *StringFilter_Like:
		qb.AddLikeCondition("address", filter.Like)
	case *StringFilter_NotLike:
		qb.AddNotLikeCondition("address", filter.NotLike)
	case *StringFilter_In:
		if len(filter.In.Values) > 0 {
			qb.AddInCondition("address", StringSliceToInterface(filter.In.Values))
		}
	case *StringFilter_NotIn:
		if len(filter.NotIn.Values) > 0 {
			qb.AddNotInCondition("address", StringSliceToInterface(filter.NotIn.Values))
		}
	default:
		// Unsupported filter type
	}

	// Add filter for column: updated_date_time
	if req.UpdatedDateTime != nil {
		switch filter := req.UpdatedDateTime.Filter.(type) {
		case *UInt32Filter_Eq:
			qb.AddCondition("updated_date_time", "=", DateTimeValue{filter.Eq})
		case *UInt32Filter_Ne:
			qb.AddCondition("updated_date_time", "!=", DateTimeValue{filter.Ne})
		case *UInt32Filter_Lt:
			qb.AddCondition("updated_date_time", "<", DateTimeValue{filter.Lt})
		case *UInt32Filter_Lte:
			qb.AddCondition("updated_date_time", "<=", DateTimeValue{filter.Lte})
		case *UInt32Filter_Gt:
			qb.AddCondition("updated_date_time", ">", DateTimeValue{filter.Gt})
		case *UInt32Filter_Gte:
			qb.AddCondition("updated_date_time", ">=", DateTimeValue{filter.Gte})
		case *UInt32Filter_Between:
			qb.AddBetweenCondition("updated_date_time", DateTimeValue{filter.Between.Min}, DateTimeValue{filter.Between.Max.GetValue()})
		case *UInt32Filter_In:
			if len(filter.In.Values) > 0 {
				converted := make([]interface{}, len(filter.In.Values))
				for i, v := range filter.In.Values {
					converted[i] = DateTimeValue{v}
				}
				qb.AddInCondition("updated_date_time", converted)
			}
		case *UInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				converted := make([]interface{}, len(filter.NotIn.Values))
				for i, v := range filter.NotIn.Values {
					converted[i] = DateTimeValue{v}
				}
				qb.AddNotInCondition("updated_date_time", converted)
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: day_start_date
	if req.DayStartDate != nil {
		switch filter := req.DayStartDate.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("day_start_date", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("day_start_date", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("day_start_date", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("day_start_date", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("day_start_date", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("day_start_date", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("day_start_date", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("day_start_date", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("day_start_date", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: active_slots
	if req.ActiveSlots != nil {
		switch filter := req.ActiveSlots.Filter.(type) {
		case *Int64Filter_Eq:
			qb.AddCondition("active_slots", "=", filter.Eq)
		case *Int64Filter_Ne:
			qb.AddCondition("active_slots", "!=", filter.Ne)
		case *Int64Filter_Lt:
			qb.AddCondition("active_slots", "<", filter.Lt)
		case *Int64Filter_Lte:
			qb.AddCondition("active_slots", "<=", filter.Lte)
		case *Int64Filter_Gt:
			qb.AddCondition("active_slots", ">", filter.Gt)
		case *Int64Filter_Gte:
			qb.AddCondition("active_slots", ">=", filter.Gte)
		case *Int64Filter_Between:
			qb.AddBetweenCondition("active_slots", filter.Between.Min, filter.Between.Max.GetValue())
		case *Int64Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("active_slots", Int64SliceToInterface(filter.In.Values))
			}
		case *Int64Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("active_slots", Int64SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: effective_bytes
	if req.EffectiveBytes != nil {
		switch filter := req.EffectiveBytes.Filter.(type) {
		case *Int64Filter_Eq:
			qb.AddCondition("effective_bytes", "=", filter.Eq)
		case *Int64Filter_Ne:
			qb.AddCondition("effective_bytes", "!=", filter.Ne)
		case *Int64Filter_Lt:
			qb.AddCondition("effective_bytes", "<", filter.Lt)
		case *Int64Filter_Lte:
			qb.AddCondition("effective_bytes", "<=", filter.Lte)
		case *Int64Filter_Gt:
			qb.AddCondition("effective_bytes", ">", filter.Gt)
		case *Int64Filter_Gte:
			qb.AddCondition("effective_bytes", ">=", filter.Gte)
		case *Int64Filter_Between:
			qb.AddBetweenCondition("effective_bytes", filter.Between.Min, filter.Between.Max.GetValue())
		case *Int64Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("effective_bytes", Int64SliceToInterface(filter.In.Values))
			}
		case *Int64Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("effective_bytes", Int64SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Handle pagination per AIP-132
	// Validate page size
	if req.PageSize < 0 {
		return SQLQuery{}, fmt.Errorf("page_size must be non-negative, got %d", req.PageSize)
	}
	if req.PageSize > 10000 {
		return SQLQuery{}, fmt.Errorf("page_size must not exceed %d, got %d", 10000, req.PageSize)
	}

	var limit, offset uint32
	limit = 100 // Default page size
	if req.PageSize > 0 {
		limit = uint32(req.PageSize)
	}
	if req.PageToken != "" {
		decodedOffset, err := DecodePageToken(req.PageToken)
		if err != nil {
			return SQLQuery{}, fmt.Errorf("invalid page_token: %w", err)
		}
		offset = decodedOffset
	}

	// Handle custom ordering if provided
	var orderByClause string
	if req.OrderBy != "" {
		validFields := []string{"updated_date_time", "address", "day_start_date", "active_slots", "effective_bytes"}
		orderFields, err := ParseOrderBy(req.OrderBy, validFields)
		if err != nil {
			return SQLQuery{}, fmt.Errorf("invalid order_by: %w", err)
		}
		orderByClause = BuildOrderByClause(orderFields)
	} else {
		// Default sorting by primary key
		orderByClause = " ORDER BY address" + ", day_start_date"
	}

	// Build column list
	columns := []string{"toUnixTimestamp(`updated_date_time`) AS `updated_date_time`", "address", "toString(`day_start_date`) AS `day_start_date`", "active_slots", "effective_bytes"}

	return BuildParameterizedQuery("fct_contract_storage_state_by_address_daily", columns, qb, orderByClause, limit, offset, options...)
}

// BuildGetFctContractStorageStateByAddressDailyQuery constructs a parameterized SQL query from a GetFctContractStorageStateByAddressDailyRequest
func BuildGetFctContractStorageStateByAddressDailyQuery(req *GetFctContractStorageStateByAddressDailyRequest, options ...QueryOption) (SQLQuery, error) {
	// Validate primary key is provided
	if req.Address == "" {
		return SQLQuery{}, fmt.Errorf("primary key field address is required")
	}

	// Build query with primary key condition
	qb := NewQueryBuilder()
	qb.AddCondition("address", "=", req.Address)

	// Build ORDER BY clause
	orderByClause := " ORDER BY address, day_start_date"

	// Build column list
	columns := []string{"toUnixTimestamp(`updated_date_time`) AS `updated_date_time`", "address", "toString(`day_start_date`) AS `day_start_date`", "active_slots", "effective_bytes"}

	// Return single record
	return BuildParameterizedQuery("fct_contract_storage_state_by_address_daily", columns, qb, orderByClause, 1, 0, options...)
}
