// Code generated by clickhouse-proto-gen. DO NOT EDIT.
// Scannable result row for fct_block_proposal_status_hourly

package clickhouse

// FctBlockProposalStatusHourlyRow is a ClickHouse-scannable result row for the fct_block_proposal_status_hourly table.
// Field types match the SELECT column expressions produced by
// BuildListFctBlockProposalStatusHourlyQuery and BuildGetFctBlockProposalStatusHourlyQuery: DateTime columns are unix
// timestamps, DateTime64 columns are unix microseconds, Date and large
// integer and decimal columns are strings, and FixedString columns are
// nullable. Scan rows with clickhouse-go's ScanStruct.
type FctBlockProposalStatusHourlyRow struct {
	UpdatedDateTime uint32 `ch:"updated_date_time" json:"updated_date_time"`
	HourStartDateTime uint32 `ch:"hour_start_date_time" json:"hour_start_date_time"`
	Status string `ch:"status" json:"status"`
	SlotCount uint32 `ch:"slot_count" json:"slot_count"`
}

// TableName returns the ClickHouse table this row maps to.
func (FctBlockProposalStatusHourlyRow) TableName() string {
	return "fct_block_proposal_status_hourly"
}

// ToProto converts the row to its protobuf message.
func (r *FctBlockProposalStatusHourlyRow) ToProto() *FctBlockProposalStatusHourly {
	p := &FctBlockProposalStatusHourly{}

	p.UpdatedDateTime = r.UpdatedDateTime
	p.HourStartDateTime = r.HourStartDateTime
	p.Status = r.Status
	p.SlotCount = r.SlotCount
	return p
}
