// Code generated by clickhouse-proto-gen. DO NOT EDIT.
// SQL query builder for fct_opcode_ops_hourly

package clickhouse

import (
	"fmt"
)

// BuildListFctOpcodeOpsHourlyQuery constructs a parameterized SQL query from a ListFctOpcodeOpsHourlyRequest
func BuildListFctOpcodeOpsHourlyQuery(req *ListFctOpcodeOpsHourlyRequest, options ...QueryOption) (SQLQuery, error) {
	// Validate that at least one primary key is provided
	// Primary keys can come from base table or projections
	if req.HourStartDateTime == nil {
		return SQLQuery{}, fmt.Errorf("primary key field hour_start_date_time is required")
	}

	// Build query using QueryBuilder
	qb := NewQueryBuilder()

	// Add primary key filter
	switch filter := req.HourStartDateTime.Filter.(type) {
	case *UInt32Filter_Eq:
		qb.AddCondition("hour_start_date_time", "=", DateTimeValue{filter.Eq})
	case *UInt32Filter_Ne:
		qb.AddCondition("hour_start_date_time", "!=", DateTimeValue{filter.Ne})
	case *UInt32Filter_Lt:
		qb.AddCondition("hour_start_date_time", "<", DateTimeValue{filter.Lt})
	case *UInt32Filter_Lte:
		qb.AddCondition("hour_start_date_time", "<=", DateTimeValue{filter.Lte})
	case *UInt32Filter_Gt:
		qb.AddCondition("hour_start_date_time", ">", DateTimeValue{filter.Gt})
	case *UInt32Filter_Gte:
		qb.AddCondition("hour_start_date_time", ">=", DateTimeValue{filter.Gte})
	case *UInt32Filter_Between:
		qb.AddBetweenCondition("hour_start_date_time", DateTimeValue{filter.Between.Min}, DateTimeValue{filter.Between.Max.GetValue()})
	case *UInt32Filter_In:
		if len(filter.In.Values) > 0 {
			converted := make([]interface{}, len(filter.In.Values))
			for i, v := range filter.In.Values {
				converted[i] = DateTimeValue{v}
			}
			qb.AddInCondition("hour_start_date_time", converted)
		}
	case *UInt32Filter_NotIn:
		if len(filter.NotIn.Values) > 0 {
			converted := make([]interface{}, len(filter.NotIn.Values))
			for i, v := range filter.NotIn.Values {
				converted[i] = DateTimeValue{v}
			}
			qb.AddNotInCondition("hour_start_date_time", converted)
		}
	default:
		// Unsupported filter type
	}

	// Add filter for column: updated_date_time
	if req.UpdatedDateTime != nil {
		switch filter := req.UpdatedDateTime.Filter.(type) {
		case *UInt32Filter_Eq:
			qb.AddCondition("updated_date_time", "=", DateTimeValue{filter.Eq})
		case *UInt32Filter_Ne:
			qb.AddCondition("updated_date_time", "!=", DateTimeValue{filter.Ne})
		case *UInt32Filter_Lt:
			qb.AddCondition("updated_date_time", "<", DateTimeValue{filter.Lt})
		case *UInt32Filter_Lte:
			qb.AddCondition("updated_date_time", "<=", DateTimeValue{filter.Lte})
		case *UInt32Filter_Gt:
			qb.AddCondition("updated_date_time", ">", DateTimeValue{filter.Gt})
		case *UInt32Filter_Gte:
			qb.AddCondition("updated_date_time", ">=", DateTimeValue{filter.Gte})
		case *UInt32Filter_Between:
			qb.AddBetweenCondition("updated_date_time", DateTimeValue{filter.Between.Min}, DateTimeValue{filter.Between.Max.GetValue()})
		case *UInt32Filter_In:
			if len(filter.In.Values) > 0 {
				converted := make([]interface{}, len(filter.In.Values))
				for i, v := range filter.In.Values {
					converted[i] = DateTimeValue{v}
				}
				qb.AddInCondition("updated_date_time", converted)
			}
		case *UInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				converted := make([]interface{}, len(filter.NotIn.Values))
				for i, v := range filter.NotIn.Values {
					converted[i] = DateTimeValue{v}
				}
				qb.AddNotInCondition("updated_date_time", converted)
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: block_count
	if req.BlockCount != nil {
		switch filter := req.BlockCount.Filter.(type) {
		case *UInt32Filter_Eq:
			qb.AddCondition("block_count", "=", filter.Eq)
		case *UInt32Filter_Ne:
			qb.AddCondition("block_count", "!=", filter.Ne)
		case *UInt32Filter_Lt:
			qb.AddCondition("block_count", "<", filter.Lt)
		case *UInt32Filter_Lte:
			qb.AddCondition("block_count", "<=", filter.Lte)
		case *UInt32Filter_Gt:
			qb.AddCondition("block_count", ">", filter.Gt)
		case *UInt32Filter_Gte:
			qb.AddCondition("block_count", ">=", filter.Gte)
		case *UInt32Filter_Between:
			qb.AddBetweenCondition("block_count", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt32Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("block_count", UInt32SliceToInterface(filter.In.Values))
			}
		case *UInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("block_count", UInt32SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: total_opcode_count
	if req.TotalOpcodeCount != nil {
		switch filter := req.TotalOpcodeCount.Filter.(type) {
		case *UInt64Filter_Eq:
			qb.AddCondition("total_opcode_count", "=", filter.Eq)
		case *UInt64Filter_Ne:
			qb.AddCondition("total_opcode_count", "!=", filter.Ne)
		case *UInt64Filter_Lt:
			qb.AddCondition("total_opcode_count", "<", filter.Lt)
		case *UInt64Filter_Lte:
			qb.AddCondition("total_opcode_count", "<=", filter.Lte)
		case *UInt64Filter_Gt:
			qb.AddCondition("total_opcode_count", ">", filter.Gt)
		case *UInt64Filter_Gte:
			qb.AddCondition("total_opcode_count", ">=", filter.Gte)
		case *UInt64Filter_Between:
			qb.AddBetweenCondition("total_opcode_count", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt64Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("total_opcode_count", UInt64SliceToInterface(filter.In.Values))
			}
		case *UInt64Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("total_opcode_count", UInt64SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: total_gas
	if req.TotalGas != nil {
		switch filter := req.TotalGas.Filter.(type) {
		case *UInt64Filter_Eq:
			qb.AddCondition("total_gas", "=", filter.Eq)
		case *UInt64Filter_Ne:
			qb.AddCondition("total_gas", "!=", filter.Ne)
		case *UInt64Filter_Lt:
			qb.AddCondition("total_gas", "<", filter.Lt)
		case *UInt64Filter_Lte:
			qb.AddCondition("total_gas", "<=", filter.Lte)
		case *UInt64Filter_Gt:
			qb.AddCondition("total_gas", ">", filter.Gt)
		case *UInt64Filter_Gte:
			qb.AddCondition("total_gas", ">=", filter.Gte)
		case *UInt64Filter_Between:
			qb.AddBetweenCondition("total_gas", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt64Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("total_gas", UInt64SliceToInterface(filter.In.Values))
			}
		case *UInt64Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("total_gas", UInt64SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: total_seconds
	if req.TotalSeconds != nil {
		switch filter := req.TotalSeconds.Filter.(type) {
		case *UInt32Filter_Eq:
			qb.AddCondition("total_seconds", "=", filter.Eq)
		case *UInt32Filter_Ne:
			qb.AddCondition("total_seconds", "!=", filter.Ne)
		case *UInt32Filter_Lt:
			qb.AddCondition("total_seconds", "<", filter.Lt)
		case *UInt32Filter_Lte:
			qb.AddCondition("total_seconds", "<=", filter.Lte)
		case *UInt32Filter_Gt:
			qb.AddCondition("total_seconds", ">", filter.Gt)
		case *UInt32Filter_Gte:
			qb.AddCondition("total_seconds", ">=", filter.Gte)
		case *UInt32Filter_Between:
			qb.AddBetweenCondition("total_seconds", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt32Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("total_seconds", UInt32SliceToInterface(filter.In.Values))
			}
		case *UInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("total_seconds", UInt32SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: avg_ops

	// Add filter for column: min_ops

	// Add filter for column: max_ops

	// Add filter for column: p05_ops

	// Add filter for column: p50_ops

	// Add filter for column: p95_ops

	// Add filter for column: stddev_ops

	// Add filter for column: upper_band_ops

	// Add filter for column: lower_band_ops

	// Add filter for column: moving_avg_ops

	// Handle pagination per AIP-132
	// Validate page size
	if req.PageSize < 0 {
		return SQLQuery{}, fmt.Errorf("page_size must be non-negative, got %d", req.PageSize)
	}
	if req.PageSize > 10000 {
		return SQLQuery{}, fmt.Errorf("page_size must not exceed %d, got %d", 10000, req.PageSize)
	}

	var limit, offset uint32
	limit = 100 // Default page size
	if req.PageSize > 0 {
		limit = uint32(req.PageSize)
	}
	if req.PageToken != "" {
		decodedOffset, err := DecodePageToken(req.PageToken)
		if err != nil {
			return SQLQuery{}, fmt.Errorf("invalid page_token: %w", err)
		}
		offset = decodedOffset
	}

	// Handle custom ordering if provided
	var orderByClause string
	if req.OrderBy != "" {
		validFields := []string{"updated_date_time", "hour_start_date_time", "block_count", "total_opcode_count", "total_gas", "total_seconds", "avg_ops", "min_ops", "max_ops", "p05_ops", "p50_ops", "p95_ops", "stddev_ops", "upper_band_ops", "lower_band_ops", "moving_avg_ops"}
		orderFields, err := ParseOrderBy(req.OrderBy, validFields)
		if err != nil {
			return SQLQuery{}, fmt.Errorf("invalid order_by: %w", err)
		}
		orderByClause = BuildOrderByClause(orderFields)
	} else {
		// Default sorting by primary key
		orderByClause = " ORDER BY hour_start_date_time"
	}

	// Build column list
	columns := []string{"toUnixTimestamp(`updated_date_time`) AS `updated_date_time`", "toUnixTimestamp(`hour_start_date_time`) AS `hour_start_date_time`", "block_count", "total_opcode_count", "total_gas", "total_seconds", "avg_ops", "min_ops", "max_ops", "p05_ops", "p50_ops", "p95_ops", "stddev_ops", "upper_band_ops", "lower_band_ops", "moving_avg_ops"}

	return BuildParameterizedQuery("fct_opcode_ops_hourly", columns, qb, orderByClause, limit, offset, options...)
}

// BuildGetFctOpcodeOpsHourlyQuery constructs a parameterized SQL query from a GetFctOpcodeOpsHourlyRequest
func BuildGetFctOpcodeOpsHourlyQuery(req *GetFctOpcodeOpsHourlyRequest, options ...QueryOption) (SQLQuery, error) {
	// Validate primary key is provided
	if req.HourStartDateTime == 0 {
		return SQLQuery{}, fmt.Errorf("primary key field hour_start_date_time is required")
	}

	// Build query with primary key condition
	qb := NewQueryBuilder()
	qb.AddCondition("hour_start_date_time", "=", req.HourStartDateTime)

	// Build ORDER BY clause
	orderByClause := " ORDER BY hour_start_date_time"

	// Build column list
	columns := []string{"toUnixTimestamp(`updated_date_time`) AS `updated_date_time`", "toUnixTimestamp(`hour_start_date_time`) AS `hour_start_date_time`", "block_count", "total_opcode_count", "total_gas", "total_seconds", "avg_ops", "min_ops", "max_ops", "p05_ops", "p50_ops", "p95_ops", "stddev_ops", "upper_band_ops", "lower_band_ops", "moving_avg_ops"}

	// Return single record
	return BuildParameterizedQuery("fct_opcode_ops_hourly", columns, qb, orderByClause, 1, 0, options...)
}
