// Code generated by clickhouse-proto-gen. DO NOT EDIT.
// SQL query builder for fct_block_first_seen_by_node_monthly

package clickhouse

import (
	"fmt"
)

// BuildListFctBlockFirstSeenByNodeMonthlyQuery constructs a parameterized SQL query from a ListFctBlockFirstSeenByNodeMonthlyRequest
//
// Available projections:
//   - p_by_month_node (primary key: month)
//
// Use WithProjection() option to select a specific projection.
func BuildListFctBlockFirstSeenByNodeMonthlyQuery(req *ListFctBlockFirstSeenByNodeMonthlyRequest, options ...QueryOption) (SQLQuery, error) {
	// Validate that at least one primary key is provided
	// Primary keys can come from base table or projections
	if req.Month == nil {
		return SQLQuery{}, fmt.Errorf("primary key field month is required")
	}

	// Build query using QueryBuilder
	qb := NewQueryBuilder()

	// Add primary key filter
	switch filter := req.Month.Filter.(type) {
	case *UInt32Filter_Eq:
		qb.AddCondition("month", "=", filter.Eq)
	case *UInt32Filter_Ne:
		qb.AddCondition("month", "!=", filter.Ne)
	case *UInt32Filter_Lt:
		qb.AddCondition("month", "<", filter.Lt)
	case *UInt32Filter_Lte:
		qb.AddCondition("month", "<=", filter.Lte)
	case *UInt32Filter_Gt:
		qb.AddCondition("month", ">", filter.Gt)
	case *UInt32Filter_Gte:
		qb.AddCondition("month", ">=", filter.Gte)
	case *UInt32Filter_Between:
		qb.AddBetweenCondition("month", filter.Between.Min, filter.Between.Max.GetValue())
	case *UInt32Filter_In:
		if len(filter.In.Values) > 0 {
			qb.AddInCondition("month", UInt32SliceToInterface(filter.In.Values))
		}
	case *UInt32Filter_NotIn:
		if len(filter.NotIn.Values) > 0 {
			qb.AddNotInCondition("month", UInt32SliceToInterface(filter.NotIn.Values))
		}
	default:
		// Unsupported filter type
	}

	// Add filter for column: updated_date_time
	if req.UpdatedDateTime != nil {
		switch filter := req.UpdatedDateTime.Filter.(type) {
		case *UInt32Filter_Eq:
			qb.AddCondition("updated_date_time", "=", DateTimeValue{filter.Eq})
		case *UInt32Filter_Ne:
			qb.AddCondition("updated_date_time", "!=", DateTimeValue{filter.Ne})
		case *UInt32Filter_Lt:
			qb.AddCondition("updated_date_time", "<", DateTimeValue{filter.Lt})
		case *UInt32Filter_Lte:
			qb.AddCondition("updated_date_time", "<=", DateTimeValue{filter.Lte})
		case *UInt32Filter_Gt:
			qb.AddCondition("updated_date_time", ">", DateTimeValue{filter.Gt})
		case *UInt32Filter_Gte:
			qb.AddCondition("updated_date_time", ">=", DateTimeValue{filter.Gte})
		case *UInt32Filter_Between:
			qb.AddBetweenCondition("updated_date_time", DateTimeValue{filter.Between.Min}, DateTimeValue{filter.Between.Max.GetValue()})
		case *UInt32Filter_In:
			if len(filter.In.Values) > 0 {
				converted := make([]interface{}, len(filter.In.Values))
				for i, v := range filter.In.Values {
					converted[i] = DateTimeValue{v}
				}
				qb.AddInCondition("updated_date_time", converted)
			}
		case *UInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				converted := make([]interface{}, len(filter.NotIn.Values))
				for i, v := range filter.NotIn.Values {
					converted[i] = DateTimeValue{v}
				}
				qb.AddNotInCondition("updated_date_time", converted)
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: month_start_date_time
	if req.MonthStartDateTime != nil {
		switch filter := req.MonthStartDateTime.Filter.(type) {
		case *UInt32Filter_Eq:
			qb.AddCondition("month_start_date_time", "=", DateTimeValue{filter.Eq})
		case *UInt32Filter_Ne:
			qb.AddCondition("month_start_date_time", "!=", DateTimeValue{filter.Ne})
		case *UInt32Filter_Lt:
			qb.AddCondition("month_start_date_time", "<", DateTimeValue{filter.Lt})
		case *UInt32Filter_Lte:
			qb.AddCondition("month_start_date_time", "<=", DateTimeValue{filter.Lte})
		case *UInt32Filter_Gt:
			qb.AddCondition("month_start_date_time", ">", DateTimeValue{filter.Gt})
		case *UInt32Filter_Gte:
			qb.AddCondition("month_start_date_time", ">=", DateTimeValue{filter.Gte})
		case *UInt32Filter_Between:
			qb.AddBetweenCondition("month_start_date_time", DateTimeValue{filter.Between.Min}, DateTimeValue{filter.Between.Max.GetValue()})
		case *UInt32Filter_In:
			if len(filter.In.Values) > 0 {
				converted := make([]interface{}, len(filter.In.Values))
				for i, v := range filter.In.Values {
					converted[i] = DateTimeValue{v}
				}
				qb.AddInCondition("month_start_date_time", converted)
			}
		case *UInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				converted := make([]interface{}, len(filter.NotIn.Values))
				for i, v := range filter.NotIn.Values {
					converted[i] = DateTimeValue{v}
				}
				qb.AddNotInCondition("month_start_date_time", converted)
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: username
	if req.Username != nil {
		switch filter := req.Username.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("username", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("username", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("username", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("username", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("username", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("username", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("username", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("username", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("username", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: node_id
	if req.NodeId != nil {
		switch filter := req.NodeId.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("node_id", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("node_id", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("node_id", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("node_id", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("node_id", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("node_id", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("node_id", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("node_id", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("node_id", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: classification
	if req.Classification != nil {
		switch filter := req.Classification.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("classification", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("classification", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("classification", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("classification", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("classification", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("classification", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("classification", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("classification", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("classification", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: meta_client_name
	if req.MetaClientName != nil {
		switch filter := req.MetaClientName.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("meta_client_name", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("meta_client_name", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("meta_client_name", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("meta_client_name", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("meta_client_name", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("meta_client_name", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("meta_client_name", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("meta_client_name", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("meta_client_name", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: meta_client_implementation
	if req.MetaClientImplementation != nil {
		switch filter := req.MetaClientImplementation.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("meta_client_implementation", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("meta_client_implementation", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("meta_client_implementation", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("meta_client_implementation", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("meta_client_implementation", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("meta_client_implementation", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("meta_client_implementation", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("meta_client_implementation", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("meta_client_implementation", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: meta_client_geo_city
	if req.MetaClientGeoCity != nil {
		switch filter := req.MetaClientGeoCity.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("meta_client_geo_city", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("meta_client_geo_city", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("meta_client_geo_city", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("meta_client_geo_city", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("meta_client_geo_city", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("meta_client_geo_city", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("meta_client_geo_city", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("meta_client_geo_city", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("meta_client_geo_city", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: meta_client_geo_country
	if req.MetaClientGeoCountry != nil {
		switch filter := req.MetaClientGeoCountry.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("meta_client_geo_country", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("meta_client_geo_country", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("meta_client_geo_country", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("meta_client_geo_country", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("meta_client_geo_country", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("meta_client_geo_country", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("meta_client_geo_country", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("meta_client_geo_country", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("meta_client_geo_country", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: meta_client_geo_country_code
	if req.MetaClientGeoCountryCode != nil {
		switch filter := req.MetaClientGeoCountryCode.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("meta_client_geo_country_code", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("meta_client_geo_country_code", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("meta_client_geo_country_code", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("meta_client_geo_country_code", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("meta_client_geo_country_code", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("meta_client_geo_country_code", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("meta_client_geo_country_code", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("meta_client_geo_country_code", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("meta_client_geo_country_code", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: meta_client_geo_continent_code
	if req.MetaClientGeoContinentCode != nil {
		switch filter := req.MetaClientGeoContinentCode.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("meta_client_geo_continent_code", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("meta_client_geo_continent_code", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("meta_client_geo_continent_code", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("meta_client_geo_continent_code", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("meta_client_geo_continent_code", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("meta_client_geo_continent_code", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("meta_client_geo_continent_code", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("meta_client_geo_continent_code", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("meta_client_geo_continent_code", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: meta_client_geo_longitude

	// Add filter for column: meta_client_geo_latitude

	// Add filter for column: meta_client_geo_autonomous_system_number
	if req.MetaClientGeoAutonomousSystemNumber != nil {
		switch filter := req.MetaClientGeoAutonomousSystemNumber.Filter.(type) {
		case *NullableUInt32Filter_Eq:
			qb.AddCondition("meta_client_geo_autonomous_system_number", "=", filter.Eq)
		case *NullableUInt32Filter_Ne:
			qb.AddCondition("meta_client_geo_autonomous_system_number", "!=", filter.Ne)
		case *NullableUInt32Filter_Lt:
			qb.AddCondition("meta_client_geo_autonomous_system_number", "<", filter.Lt)
		case *NullableUInt32Filter_Lte:
			qb.AddCondition("meta_client_geo_autonomous_system_number", "<=", filter.Lte)
		case *NullableUInt32Filter_Gt:
			qb.AddCondition("meta_client_geo_autonomous_system_number", ">", filter.Gt)
		case *NullableUInt32Filter_Gte:
			qb.AddCondition("meta_client_geo_autonomous_system_number", ">=", filter.Gte)
		case *NullableUInt32Filter_Between:
			qb.AddBetweenCondition("meta_client_geo_autonomous_system_number", filter.Between.Min, filter.Between.Max.GetValue())
		case *NullableUInt32Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("meta_client_geo_autonomous_system_number", UInt32SliceToInterface(filter.In.Values))
			}
		case *NullableUInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("meta_client_geo_autonomous_system_number", UInt32SliceToInterface(filter.NotIn.Values))
			}
		case *NullableUInt32Filter_IsNull:
			qb.AddIsNullCondition("meta_client_geo_autonomous_system_number")
		case *NullableUInt32Filter_IsNotNull:
			qb.AddIsNotNullCondition("meta_client_geo_autonomous_system_number")
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: meta_client_geo_autonomous_system_organization
	if req.MetaClientGeoAutonomousSystemOrganization != nil {
		switch filter := req.MetaClientGeoAutonomousSystemOrganization.Filter.(type) {
		case *NullableStringFilter_Eq:
			qb.AddCondition("meta_client_geo_autonomous_system_organization", "=", filter.Eq)
		case *NullableStringFilter_Ne:
			qb.AddCondition("meta_client_geo_autonomous_system_organization", "!=", filter.Ne)
		case *NullableStringFilter_Contains:
			qb.AddLikeCondition("meta_client_geo_autonomous_system_organization", "%" + filter.Contains + "%")
		case *NullableStringFilter_StartsWith:
			qb.AddLikeCondition("meta_client_geo_autonomous_system_organization", filter.StartsWith + "%")
		case *NullableStringFilter_EndsWith:
			qb.AddLikeCondition("meta_client_geo_autonomous_system_organization", "%" + filter.EndsWith)
		case *NullableStringFilter_Like:
			qb.AddLikeCondition("meta_client_geo_autonomous_system_organization", filter.Like)
		case *NullableStringFilter_NotLike:
			qb.AddNotLikeCondition("meta_client_geo_autonomous_system_organization", filter.NotLike)
		case *NullableStringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("meta_client_geo_autonomous_system_organization", StringSliceToInterface(filter.In.Values))
			}
		case *NullableStringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("meta_client_geo_autonomous_system_organization", StringSliceToInterface(filter.NotIn.Values))
			}
		case *NullableStringFilter_IsNull:
			qb.AddIsNullCondition("meta_client_geo_autonomous_system_organization")
		case *NullableStringFilter_IsNotNull:
			qb.AddIsNotNullCondition("meta_client_geo_autonomous_system_organization")
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: min_slot
	if req.MinSlot != nil {
		switch filter := req.MinSlot.Filter.(type) {
		case *UInt64Filter_Eq:
			qb.AddCondition("min_slot", "=", filter.Eq)
		case *UInt64Filter_Ne:
			qb.AddCondition("min_slot", "!=", filter.Ne)
		case *UInt64Filter_Lt:
			qb.AddCondition("min_slot", "<", filter.Lt)
		case *UInt64Filter_Lte:
			qb.AddCondition("min_slot", "<=", filter.Lte)
		case *UInt64Filter_Gt:
			qb.AddCondition("min_slot", ">", filter.Gt)
		case *UInt64Filter_Gte:
			qb.AddCondition("min_slot", ">=", filter.Gte)
		case *UInt64Filter_Between:
			qb.AddBetweenCondition("min_slot", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt64Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("min_slot", UInt64SliceToInterface(filter.In.Values))
			}
		case *UInt64Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("min_slot", UInt64SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: max_slot
	if req.MaxSlot != nil {
		switch filter := req.MaxSlot.Filter.(type) {
		case *UInt64Filter_Eq:
			qb.AddCondition("max_slot", "=", filter.Eq)
		case *UInt64Filter_Ne:
			qb.AddCondition("max_slot", "!=", filter.Ne)
		case *UInt64Filter_Lt:
			qb.AddCondition("max_slot", "<", filter.Lt)
		case *UInt64Filter_Lte:
			qb.AddCondition("max_slot", "<=", filter.Lte)
		case *UInt64Filter_Gt:
			qb.AddCondition("max_slot", ">", filter.Gt)
		case *UInt64Filter_Gte:
			qb.AddCondition("max_slot", ">=", filter.Gte)
		case *UInt64Filter_Between:
			qb.AddBetweenCondition("max_slot", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt64Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("max_slot", UInt64SliceToInterface(filter.In.Values))
			}
		case *UInt64Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("max_slot", UInt64SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: day_count
	if req.DayCount != nil {
		switch filter := req.DayCount.Filter.(type) {
		case *UInt32Filter_Eq:
			qb.AddCondition("day_count", "=", filter.Eq)
		case *UInt32Filter_Ne:
			qb.AddCondition("day_count", "!=", filter.Ne)
		case *UInt32Filter_Lt:
			qb.AddCondition("day_count", "<", filter.Lt)
		case *UInt32Filter_Lte:
			qb.AddCondition("day_count", "<=", filter.Lte)
		case *UInt32Filter_Gt:
			qb.AddCondition("day_count", ">", filter.Gt)
		case *UInt32Filter_Gte:
			qb.AddCondition("day_count", ">=", filter.Gte)
		case *UInt32Filter_Between:
			qb.AddBetweenCondition("day_count", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt32Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("day_count", UInt32SliceToInterface(filter.In.Values))
			}
		case *UInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("day_count", UInt32SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: epoch_count
	if req.EpochCount != nil {
		switch filter := req.EpochCount.Filter.(type) {
		case *UInt32Filter_Eq:
			qb.AddCondition("epoch_count", "=", filter.Eq)
		case *UInt32Filter_Ne:
			qb.AddCondition("epoch_count", "!=", filter.Ne)
		case *UInt32Filter_Lt:
			qb.AddCondition("epoch_count", "<", filter.Lt)
		case *UInt32Filter_Lte:
			qb.AddCondition("epoch_count", "<=", filter.Lte)
		case *UInt32Filter_Gt:
			qb.AddCondition("epoch_count", ">", filter.Gt)
		case *UInt32Filter_Gte:
			qb.AddCondition("epoch_count", ">=", filter.Gte)
		case *UInt32Filter_Between:
			qb.AddBetweenCondition("epoch_count", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt32Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("epoch_count", UInt32SliceToInterface(filter.In.Values))
			}
		case *UInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("epoch_count", UInt32SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: slot_count
	if req.SlotCount != nil {
		switch filter := req.SlotCount.Filter.(type) {
		case *UInt32Filter_Eq:
			qb.AddCondition("slot_count", "=", filter.Eq)
		case *UInt32Filter_Ne:
			qb.AddCondition("slot_count", "!=", filter.Ne)
		case *UInt32Filter_Lt:
			qb.AddCondition("slot_count", "<", filter.Lt)
		case *UInt32Filter_Lte:
			qb.AddCondition("slot_count", "<=", filter.Lte)
		case *UInt32Filter_Gt:
			qb.AddCondition("slot_count", ">", filter.Gt)
		case *UInt32Filter_Gte:
			qb.AddCondition("slot_count", ">=", filter.Gte)
		case *UInt32Filter_Between:
			qb.AddBetweenCondition("slot_count", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt32Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("slot_count", UInt32SliceToInterface(filter.In.Values))
			}
		case *UInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("slot_count", UInt32SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: min_seen_slot_start_diff_ms
	if req.MinSeenSlotStartDiffMs != nil {
		switch filter := req.MinSeenSlotStartDiffMs.Filter.(type) {
		case *UInt32Filter_Eq:
			qb.AddCondition("min_seen_slot_start_diff_ms", "=", filter.Eq)
		case *UInt32Filter_Ne:
			qb.AddCondition("min_seen_slot_start_diff_ms", "!=", filter.Ne)
		case *UInt32Filter_Lt:
			qb.AddCondition("min_seen_slot_start_diff_ms", "<", filter.Lt)
		case *UInt32Filter_Lte:
			qb.AddCondition("min_seen_slot_start_diff_ms", "<=", filter.Lte)
		case *UInt32Filter_Gt:
			qb.AddCondition("min_seen_slot_start_diff_ms", ">", filter.Gt)
		case *UInt32Filter_Gte:
			qb.AddCondition("min_seen_slot_start_diff_ms", ">=", filter.Gte)
		case *UInt32Filter_Between:
			qb.AddBetweenCondition("min_seen_slot_start_diff_ms", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt32Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("min_seen_slot_start_diff_ms", UInt32SliceToInterface(filter.In.Values))
			}
		case *UInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("min_seen_slot_start_diff_ms", UInt32SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: p05_seen_slot_start_diff_ms
	if req.P05SeenSlotStartDiffMs != nil {
		switch filter := req.P05SeenSlotStartDiffMs.Filter.(type) {
		case *UInt32Filter_Eq:
			qb.AddCondition("p05_seen_slot_start_diff_ms", "=", filter.Eq)
		case *UInt32Filter_Ne:
			qb.AddCondition("p05_seen_slot_start_diff_ms", "!=", filter.Ne)
		case *UInt32Filter_Lt:
			qb.AddCondition("p05_seen_slot_start_diff_ms", "<", filter.Lt)
		case *UInt32Filter_Lte:
			qb.AddCondition("p05_seen_slot_start_diff_ms", "<=", filter.Lte)
		case *UInt32Filter_Gt:
			qb.AddCondition("p05_seen_slot_start_diff_ms", ">", filter.Gt)
		case *UInt32Filter_Gte:
			qb.AddCondition("p05_seen_slot_start_diff_ms", ">=", filter.Gte)
		case *UInt32Filter_Between:
			qb.AddBetweenCondition("p05_seen_slot_start_diff_ms", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt32Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("p05_seen_slot_start_diff_ms", UInt32SliceToInterface(filter.In.Values))
			}
		case *UInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("p05_seen_slot_start_diff_ms", UInt32SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: p50_seen_slot_start_diff_ms
	if req.P50SeenSlotStartDiffMs != nil {
		switch filter := req.P50SeenSlotStartDiffMs.Filter.(type) {
		case *UInt32Filter_Eq:
			qb.AddCondition("p50_seen_slot_start_diff_ms", "=", filter.Eq)
		case *UInt32Filter_Ne:
			qb.AddCondition("p50_seen_slot_start_diff_ms", "!=", filter.Ne)
		case *UInt32Filter_Lt:
			qb.AddCondition("p50_seen_slot_start_diff_ms", "<", filter.Lt)
		case *UInt32Filter_Lte:
			qb.AddCondition("p50_seen_slot_start_diff_ms", "<=", filter.Lte)
		case *UInt32Filter_Gt:
			qb.AddCondition("p50_seen_slot_start_diff_ms", ">", filter.Gt)
		case *UInt32Filter_Gte:
			qb.AddCondition("p50_seen_slot_start_diff_ms", ">=", filter.Gte)
		case *UInt32Filter_Between:
			qb.AddBetweenCondition("p50_seen_slot_start_diff_ms", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt32Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("p50_seen_slot_start_diff_ms", UInt32SliceToInterface(filter.In.Values))
			}
		case *UInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("p50_seen_slot_start_diff_ms", UInt32SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: avg_seen_slot_start_diff_ms
	if req.AvgSeenSlotStartDiffMs != nil {
		switch filter := req.AvgSeenSlotStartDiffMs.Filter.(type) {
		case *UInt32Filter_Eq:
			qb.AddCondition("avg_seen_slot_start_diff_ms", "=", filter.Eq)
		case *UInt32Filter_Ne:
			qb.AddCondition("avg_seen_slot_start_diff_ms", "!=", filter.Ne)
		case *UInt32Filter_Lt:
			qb.AddCondition("avg_seen_slot_start_diff_ms", "<", filter.Lt)
		case *UInt32Filter_Lte:
			qb.AddCondition("avg_seen_slot_start_diff_ms", "<=", filter.Lte)
		case *UInt32Filter_Gt:
			qb.AddCondition("avg_seen_slot_start_diff_ms", ">", filter.Gt)
		case *UInt32Filter_Gte:
			qb.AddCondition("avg_seen_slot_start_diff_ms", ">=", filter.Gte)
		case *UInt32Filter_Between:
			qb.AddBetweenCondition("avg_seen_slot_start_diff_ms", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt32Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("avg_seen_slot_start_diff_ms", UInt32SliceToInterface(filter.In.Values))
			}
		case *UInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("avg_seen_slot_start_diff_ms", UInt32SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: p90_seen_slot_start_diff_ms
	if req.P90SeenSlotStartDiffMs != nil {
		switch filter := req.P90SeenSlotStartDiffMs.Filter.(type) {
		case *UInt32Filter_Eq:
			qb.AddCondition("p90_seen_slot_start_diff_ms", "=", filter.Eq)
		case *UInt32Filter_Ne:
			qb.AddCondition("p90_seen_slot_start_diff_ms", "!=", filter.Ne)
		case *UInt32Filter_Lt:
			qb.AddCondition("p90_seen_slot_start_diff_ms", "<", filter.Lt)
		case *UInt32Filter_Lte:
			qb.AddCondition("p90_seen_slot_start_diff_ms", "<=", filter.Lte)
		case *UInt32Filter_Gt:
			qb.AddCondition("p90_seen_slot_start_diff_ms", ">", filter.Gt)
		case *UInt32Filter_Gte:
			qb.AddCondition("p90_seen_slot_start_diff_ms", ">=", filter.Gte)
		case *UInt32Filter_Between:
			qb.AddBetweenCondition("p90_seen_slot_start_diff_ms", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt32Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("p90_seen_slot_start_diff_ms", UInt32SliceToInterface(filter.In.Values))
			}
		case *UInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("p90_seen_slot_start_diff_ms", UInt32SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: p95_seen_slot_start_diff_ms
	if req.P95SeenSlotStartDiffMs != nil {
		switch filter := req.P95SeenSlotStartDiffMs.Filter.(type) {
		case *UInt32Filter_Eq:
			qb.AddCondition("p95_seen_slot_start_diff_ms", "=", filter.Eq)
		case *UInt32Filter_Ne:
			qb.AddCondition("p95_seen_slot_start_diff_ms", "!=", filter.Ne)
		case *UInt32Filter_Lt:
			qb.AddCondition("p95_seen_slot_start_diff_ms", "<", filter.Lt)
		case *UInt32Filter_Lte:
			qb.AddCondition("p95_seen_slot_start_diff_ms", "<=", filter.Lte)
		case *UInt32Filter_Gt:
			qb.AddCondition("p95_seen_slot_start_diff_ms", ">", filter.Gt)
		case *UInt32Filter_Gte:
			qb.AddCondition("p95_seen_slot_start_diff_ms", ">=", filter.Gte)
		case *UInt32Filter_Between:
			qb.AddBetweenCondition("p95_seen_slot_start_diff_ms", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt32Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("p95_seen_slot_start_diff_ms", UInt32SliceToInterface(filter.In.Values))
			}
		case *UInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("p95_seen_slot_start_diff_ms", UInt32SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: p99_seen_slot_start_diff_ms
	if req.P99SeenSlotStartDiffMs != nil {
		switch filter := req.P99SeenSlotStartDiffMs.Filter.(type) {
		case *UInt32Filter_Eq:
			qb.AddCondition("p99_seen_slot_start_diff_ms", "=", filter.Eq)
		case *UInt32Filter_Ne:
			qb.AddCondition("p99_seen_slot_start_diff_ms", "!=", filter.Ne)
		case *UInt32Filter_Lt:
			qb.AddCondition("p99_seen_slot_start_diff_ms", "<", filter.Lt)
		case *UInt32Filter_Lte:
			qb.AddCondition("p99_seen_slot_start_diff_ms", "<=", filter.Lte)
		case *UInt32Filter_Gt:
			qb.AddCondition("p99_seen_slot_start_diff_ms", ">", filter.Gt)
		case *UInt32Filter_Gte:
			qb.AddCondition("p99_seen_slot_start_diff_ms", ">=", filter.Gte)
		case *UInt32Filter_Between:
			qb.AddBetweenCondition("p99_seen_slot_start_diff_ms", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt32Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("p99_seen_slot_start_diff_ms", UInt32SliceToInterface(filter.In.Values))
			}
		case *UInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("p99_seen_slot_start_diff_ms", UInt32SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: max_seen_slot_start_diff_ms
	if req.MaxSeenSlotStartDiffMs != nil {
		switch filter := req.MaxSeenSlotStartDiffMs.Filter.(type) {
		case *UInt32Filter_Eq:
			qb.AddCondition("max_seen_slot_start_diff_ms", "=", filter.Eq)
		case *UInt32Filter_Ne:
			qb.AddCondition("max_seen_slot_start_diff_ms", "!=", filter.Ne)
		case *UInt32Filter_Lt:
			qb.AddCondition("max_seen_slot_start_diff_ms", "<", filter.Lt)
		case *UInt32Filter_Lte:
			qb.AddCondition("max_seen_slot_start_diff_ms", "<=", filter.Lte)
		case *UInt32Filter_Gt:
			qb.AddCondition("max_seen_slot_start_diff_ms", ">", filter.Gt)
		case *UInt32Filter_Gte:
			qb.AddCondition("max_seen_slot_start_diff_ms", ">=", filter.Gte)
		case *UInt32Filter_Between:
			qb.AddBetweenCondition("max_seen_slot_start_diff_ms", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt32Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("max_seen_slot_start_diff_ms", UInt32SliceToInterface(filter.In.Values))
			}
		case *UInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("max_seen_slot_start_diff_ms", UInt32SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Handle pagination per AIP-132
	// Validate page size
	if req.PageSize < 0 {
		return SQLQuery{}, fmt.Errorf("page_size must be non-negative, got %d", req.PageSize)
	}
	if req.PageSize > 10000 {
		return SQLQuery{}, fmt.Errorf("page_size must not exceed %d, got %d", 10000, req.PageSize)
	}

	var limit, offset uint32
	limit = 100 // Default page size
	if req.PageSize > 0 {
		limit = uint32(req.PageSize)
	}
	if req.PageToken != "" {
		decodedOffset, err := DecodePageToken(req.PageToken)
		if err != nil {
			return SQLQuery{}, fmt.Errorf("invalid page_token: %w", err)
		}
		offset = decodedOffset
	}

	// Handle custom ordering if provided
	var orderByClause string
	if req.OrderBy != "" {
		validFields := []string{"updated_date_time", "month", "month_start_date_time", "username", "node_id", "classification", "meta_client_name", "meta_client_implementation", "meta_client_geo_city", "meta_client_geo_country", "meta_client_geo_country_code", "meta_client_geo_continent_code", "meta_client_geo_longitude", "meta_client_geo_latitude", "meta_client_geo_autonomous_system_number", "meta_client_geo_autonomous_system_organization", "min_slot", "max_slot", "day_count", "epoch_count", "slot_count", "min_seen_slot_start_diff_ms", "p05_seen_slot_start_diff_ms", "p50_seen_slot_start_diff_ms", "avg_seen_slot_start_diff_ms", "p90_seen_slot_start_diff_ms", "p95_seen_slot_start_diff_ms", "p99_seen_slot_start_diff_ms", "max_seen_slot_start_diff_ms"}
		orderFields, err := ParseOrderBy(req.OrderBy, validFields)
		if err != nil {
			return SQLQuery{}, fmt.Errorf("invalid order_by: %w", err)
		}
		orderByClause = BuildOrderByClause(orderFields)
	} else {
		// Default sorting by primary key
		orderByClause = " ORDER BY month" + ", meta_client_name"
	}

	// Build column list
	columns := []string{"toUnixTimestamp(`updated_date_time`) AS `updated_date_time`", "month", "toUnixTimestamp(`month_start_date_time`) AS `month_start_date_time`", "username", "node_id", "classification", "meta_client_name", "meta_client_implementation", "meta_client_geo_city", "meta_client_geo_country", "meta_client_geo_country_code", "meta_client_geo_continent_code", "meta_client_geo_longitude", "meta_client_geo_latitude", "meta_client_geo_autonomous_system_number", "meta_client_geo_autonomous_system_organization", "min_slot", "max_slot", "day_count", "epoch_count", "slot_count", "min_seen_slot_start_diff_ms", "p05_seen_slot_start_diff_ms", "p50_seen_slot_start_diff_ms", "avg_seen_slot_start_diff_ms", "p90_seen_slot_start_diff_ms", "p95_seen_slot_start_diff_ms", "p99_seen_slot_start_diff_ms", "max_seen_slot_start_diff_ms"}

	return BuildParameterizedQuery("fct_block_first_seen_by_node_monthly", columns, qb, orderByClause, limit, offset, options...)
}

// BuildGetFctBlockFirstSeenByNodeMonthlyQuery constructs a parameterized SQL query from a GetFctBlockFirstSeenByNodeMonthlyRequest
func BuildGetFctBlockFirstSeenByNodeMonthlyQuery(req *GetFctBlockFirstSeenByNodeMonthlyRequest, options ...QueryOption) (SQLQuery, error) {
	// Validate primary key is provided
	if req.Month == 0 {
		return SQLQuery{}, fmt.Errorf("primary key field month is required")
	}

	// Build query with primary key condition
	qb := NewQueryBuilder()
	qb.AddCondition("month", "=", req.Month)

	// Build ORDER BY clause
	orderByClause := " ORDER BY month, meta_client_name"

	// Build column list
	columns := []string{"toUnixTimestamp(`updated_date_time`) AS `updated_date_time`", "month", "toUnixTimestamp(`month_start_date_time`) AS `month_start_date_time`", "username", "node_id", "classification", "meta_client_name", "meta_client_implementation", "meta_client_geo_city", "meta_client_geo_country", "meta_client_geo_country_code", "meta_client_geo_continent_code", "meta_client_geo_longitude", "meta_client_geo_latitude", "meta_client_geo_autonomous_system_number", "meta_client_geo_autonomous_system_organization", "min_slot", "max_slot", "day_count", "epoch_count", "slot_count", "min_seen_slot_start_diff_ms", "p05_seen_slot_start_diff_ms", "p50_seen_slot_start_diff_ms", "avg_seen_slot_start_diff_ms", "p90_seen_slot_start_diff_ms", "p95_seen_slot_start_diff_ms", "p99_seen_slot_start_diff_ms", "max_seen_slot_start_diff_ms"}

	// Return single record
	return BuildParameterizedQuery("fct_block_first_seen_by_node_monthly", columns, qb, orderByClause, 1, 0, options...)
}
