// Code generated by clickhouse-proto-gen. DO NOT EDIT.
// Scannable result row for fct_validator_balance

package clickhouse

// FctValidatorBalanceRow is a ClickHouse-scannable result row for the fct_validator_balance table.
// Field types match the SELECT column expressions produced by
// BuildListFctValidatorBalanceQuery and BuildGetFctValidatorBalanceQuery: DateTime columns are unix
// timestamps, DateTime64 columns are unix microseconds, Date and large
// integer and decimal columns are strings, and FixedString columns are
// nullable. Scan rows with clickhouse-go's ScanStruct.
type FctValidatorBalanceRow struct {
	UpdatedDateTime uint32 `ch:"updated_date_time" json:"updated_date_time"`
	Epoch uint32 `ch:"epoch" json:"epoch"`
	EpochStartDateTime uint32 `ch:"epoch_start_date_time" json:"epoch_start_date_time"`
	ValidatorIndex uint32 `ch:"validator_index" json:"validator_index"`
	Balance uint64 `ch:"balance" json:"balance"`
	EffectiveBalance uint64 `ch:"effective_balance" json:"effective_balance"`
	Status string `ch:"status" json:"status"`
	Slashed bool `ch:"slashed" json:"slashed"`
}

// TableName returns the ClickHouse table this row maps to.
func (FctValidatorBalanceRow) TableName() string {
	return "fct_validator_balance"
}

// ToProto converts the row to its protobuf message.
func (r *FctValidatorBalanceRow) ToProto() *FctValidatorBalance {
	p := &FctValidatorBalance{}

	p.UpdatedDateTime = r.UpdatedDateTime
	p.Epoch = r.Epoch
	p.EpochStartDateTime = r.EpochStartDateTime
	p.ValidatorIndex = r.ValidatorIndex
	p.Balance = r.Balance
	p.EffectiveBalance = r.EffectiveBalance
	p.Status = r.Status
	p.Slashed = r.Slashed
	return p
}
