// Code generated by clickhouse-proto-gen. DO NOT EDIT.
// Scannable result row for fct_attestation_inclusion_delay_daily

package clickhouse

// FctAttestationInclusionDelayDailyRow is a ClickHouse-scannable result row for the fct_attestation_inclusion_delay_daily table.
// Field types match the SELECT column expressions produced by
// BuildListFctAttestationInclusionDelayDailyQuery and BuildGetFctAttestationInclusionDelayDailyQuery: DateTime columns are unix
// timestamps, DateTime64 columns are unix microseconds, Date and large
// integer and decimal columns are strings, and FixedString columns are
// nullable. Scan rows with clickhouse-go's ScanStruct.
type FctAttestationInclusionDelayDailyRow struct {
	UpdatedDateTime uint32 `ch:"updated_date_time" json:"updated_date_time"`
	DayStartDate string `ch:"day_start_date" json:"day_start_date"`
	SlotCount uint32 `ch:"slot_count" json:"slot_count"`
	AvgInclusionDelay float32 `ch:"avg_inclusion_delay" json:"avg_inclusion_delay"`
	MinInclusionDelay float32 `ch:"min_inclusion_delay" json:"min_inclusion_delay"`
	MaxInclusionDelay float32 `ch:"max_inclusion_delay" json:"max_inclusion_delay"`
	P05InclusionDelay float32 `ch:"p05_inclusion_delay" json:"p05_inclusion_delay"`
	P50InclusionDelay float32 `ch:"p50_inclusion_delay" json:"p50_inclusion_delay"`
	P95InclusionDelay float32 `ch:"p95_inclusion_delay" json:"p95_inclusion_delay"`
	StddevInclusionDelay float32 `ch:"stddev_inclusion_delay" json:"stddev_inclusion_delay"`
	UpperBandInclusionDelay float32 `ch:"upper_band_inclusion_delay" json:"upper_band_inclusion_delay"`
	LowerBandInclusionDelay float32 `ch:"lower_band_inclusion_delay" json:"lower_band_inclusion_delay"`
	MovingAvgInclusionDelay float32 `ch:"moving_avg_inclusion_delay" json:"moving_avg_inclusion_delay"`
}

// TableName returns the ClickHouse table this row maps to.
func (FctAttestationInclusionDelayDailyRow) TableName() string {
	return "fct_attestation_inclusion_delay_daily"
}

// ToProto converts the row to its protobuf message.
func (r *FctAttestationInclusionDelayDailyRow) ToProto() *FctAttestationInclusionDelayDaily {
	p := &FctAttestationInclusionDelayDaily{}

	p.UpdatedDateTime = r.UpdatedDateTime
	p.DayStartDate = r.DayStartDate
	p.SlotCount = r.SlotCount
	p.AvgInclusionDelay = r.AvgInclusionDelay
	p.MinInclusionDelay = r.MinInclusionDelay
	p.MaxInclusionDelay = r.MaxInclusionDelay
	p.P05InclusionDelay = r.P05InclusionDelay
	p.P50InclusionDelay = r.P50InclusionDelay
	p.P95InclusionDelay = r.P95InclusionDelay
	p.StddevInclusionDelay = r.StddevInclusionDelay
	p.UpperBandInclusionDelay = r.UpperBandInclusionDelay
	p.LowerBandInclusionDelay = r.LowerBandInclusionDelay
	p.MovingAvgInclusionDelay = r.MovingAvgInclusionDelay
	return p
}
