// Code generated by clickhouse-proto-gen. DO NOT EDIT.
// Scannable result row for fct_block_fast_confirmation_by_client_daily

package clickhouse

// FctBlockFastConfirmationByClientDailyRow is a ClickHouse-scannable result row for the fct_block_fast_confirmation_by_client_daily table.
// Field types match the SELECT column expressions produced by
// BuildListFctBlockFastConfirmationByClientDailyQuery and BuildGetFctBlockFastConfirmationByClientDailyQuery: DateTime columns are unix
// timestamps, DateTime64 columns are unix microseconds, Date and large
// integer and decimal columns are strings, and FixedString columns are
// nullable. Scan rows with clickhouse-go's ScanStruct.
type FctBlockFastConfirmationByClientDailyRow struct {
	UpdatedDateTime uint32 `ch:"updated_date_time" json:"updated_date_time"`
	DayStartDate string `ch:"day_start_date" json:"day_start_date"`
	MetaConsensusImplementation string `ch:"meta_consensus_implementation" json:"meta_consensus_implementation"`
	NodeCount uint32 `ch:"node_count" json:"node_count"`
	SlotCount uint32 `ch:"slot_count" json:"slot_count"`
	ObservationCount uint32 `ch:"observation_count" json:"observation_count"`
	DirectCount uint32 `ch:"direct_count" json:"direct_count"`
	DescendantCount uint32 `ch:"descendant_count" json:"descendant_count"`
	UnconfirmedCount uint32 `ch:"unconfirmed_count" json:"unconfirmed_count"`
	OrphanedCount uint32 `ch:"orphaned_count" json:"orphaned_count"`
	AvgFastConfirmationMs uint32 `ch:"avg_fast_confirmation_ms" json:"avg_fast_confirmation_ms"`
	MinFastConfirmationMs uint32 `ch:"min_fast_confirmation_ms" json:"min_fast_confirmation_ms"`
	P50FastConfirmationMs uint32 `ch:"p50_fast_confirmation_ms" json:"p50_fast_confirmation_ms"`
	P90FastConfirmationMs uint32 `ch:"p90_fast_confirmation_ms" json:"p90_fast_confirmation_ms"`
	P95FastConfirmationMs uint32 `ch:"p95_fast_confirmation_ms" json:"p95_fast_confirmation_ms"`
	P99FastConfirmationMs uint32 `ch:"p99_fast_confirmation_ms" json:"p99_fast_confirmation_ms"`
	MaxFastConfirmationMs uint32 `ch:"max_fast_confirmation_ms" json:"max_fast_confirmation_ms"`
	AvgFinalityMs uint32 `ch:"avg_finality_ms" json:"avg_finality_ms"`
	MinFinalityMs uint32 `ch:"min_finality_ms" json:"min_finality_ms"`
	P50FinalityMs uint32 `ch:"p50_finality_ms" json:"p50_finality_ms"`
	P95FinalityMs uint32 `ch:"p95_finality_ms" json:"p95_finality_ms"`
	MaxFinalityMs uint32 `ch:"max_finality_ms" json:"max_finality_ms"`
	P50Speedup float32 `ch:"p50_speedup" json:"p50_speedup"`
}

// TableName returns the ClickHouse table this row maps to.
func (FctBlockFastConfirmationByClientDailyRow) TableName() string {
	return "fct_block_fast_confirmation_by_client_daily"
}

// ToProto converts the row to its protobuf message.
func (r *FctBlockFastConfirmationByClientDailyRow) ToProto() *FctBlockFastConfirmationByClientDaily {
	p := &FctBlockFastConfirmationByClientDaily{}

	p.UpdatedDateTime = r.UpdatedDateTime
	p.DayStartDate = r.DayStartDate
	p.MetaConsensusImplementation = r.MetaConsensusImplementation
	p.NodeCount = r.NodeCount
	p.SlotCount = r.SlotCount
	p.ObservationCount = r.ObservationCount
	p.DirectCount = r.DirectCount
	p.DescendantCount = r.DescendantCount
	p.UnconfirmedCount = r.UnconfirmedCount
	p.OrphanedCount = r.OrphanedCount
	p.AvgFastConfirmationMs = r.AvgFastConfirmationMs
	p.MinFastConfirmationMs = r.MinFastConfirmationMs
	p.P50FastConfirmationMs = r.P50FastConfirmationMs
	p.P90FastConfirmationMs = r.P90FastConfirmationMs
	p.P95FastConfirmationMs = r.P95FastConfirmationMs
	p.P99FastConfirmationMs = r.P99FastConfirmationMs
	p.MaxFastConfirmationMs = r.MaxFastConfirmationMs
	p.AvgFinalityMs = r.AvgFinalityMs
	p.MinFinalityMs = r.MinFinalityMs
	p.P50FinalityMs = r.P50FinalityMs
	p.P95FinalityMs = r.P95FinalityMs
	p.MaxFinalityMs = r.MaxFinalityMs
	p.P50Speedup = r.P50Speedup
	return p
}
