// Code generated by clickhouse-proto-gen. DO NOT EDIT.
// SQL query builder for fct_sync_committee_participation_by_validator_hourly

package clickhouse

import (
	"fmt"
)

// BuildListFctSyncCommitteeParticipationByValidatorHourlyQuery constructs a parameterized SQL query from a ListFctSyncCommitteeParticipationByValidatorHourlyRequest
func BuildListFctSyncCommitteeParticipationByValidatorHourlyQuery(req *ListFctSyncCommitteeParticipationByValidatorHourlyRequest, options ...QueryOption) (SQLQuery, error) {
	// Validate that at least one primary key is provided
	// Primary keys can come from base table or projections
	if req.ValidatorIndex == nil {
		return SQLQuery{}, fmt.Errorf("primary key field validator_index is required")
	}

	// Build query using QueryBuilder
	qb := NewQueryBuilder()

	// Add primary key filter
	switch filter := req.ValidatorIndex.Filter.(type) {
	case *UInt32Filter_Eq:
		qb.AddCondition("validator_index", "=", filter.Eq)
	case *UInt32Filter_Ne:
		qb.AddCondition("validator_index", "!=", filter.Ne)
	case *UInt32Filter_Lt:
		qb.AddCondition("validator_index", "<", filter.Lt)
	case *UInt32Filter_Lte:
		qb.AddCondition("validator_index", "<=", filter.Lte)
	case *UInt32Filter_Gt:
		qb.AddCondition("validator_index", ">", filter.Gt)
	case *UInt32Filter_Gte:
		qb.AddCondition("validator_index", ">=", filter.Gte)
	case *UInt32Filter_Between:
		qb.AddBetweenCondition("validator_index", filter.Between.Min, filter.Between.Max.GetValue())
	case *UInt32Filter_In:
		if len(filter.In.Values) > 0 {
			qb.AddInCondition("validator_index", UInt32SliceToInterface(filter.In.Values))
		}
	case *UInt32Filter_NotIn:
		if len(filter.NotIn.Values) > 0 {
			qb.AddNotInCondition("validator_index", UInt32SliceToInterface(filter.NotIn.Values))
		}
	default:
		// Unsupported filter type
	}

	// Add filter for column: updated_date_time
	if req.UpdatedDateTime != nil {
		switch filter := req.UpdatedDateTime.Filter.(type) {
		case *UInt32Filter_Eq:
			qb.AddCondition("updated_date_time", "=", DateTimeValue{filter.Eq})
		case *UInt32Filter_Ne:
			qb.AddCondition("updated_date_time", "!=", DateTimeValue{filter.Ne})
		case *UInt32Filter_Lt:
			qb.AddCondition("updated_date_time", "<", DateTimeValue{filter.Lt})
		case *UInt32Filter_Lte:
			qb.AddCondition("updated_date_time", "<=", DateTimeValue{filter.Lte})
		case *UInt32Filter_Gt:
			qb.AddCondition("updated_date_time", ">", DateTimeValue{filter.Gt})
		case *UInt32Filter_Gte:
			qb.AddCondition("updated_date_time", ">=", DateTimeValue{filter.Gte})
		case *UInt32Filter_Between:
			qb.AddBetweenCondition("updated_date_time", DateTimeValue{filter.Between.Min}, DateTimeValue{filter.Between.Max.GetValue()})
		case *UInt32Filter_In:
			if len(filter.In.Values) > 0 {
				converted := make([]interface{}, len(filter.In.Values))
				for i, v := range filter.In.Values {
					converted[i] = DateTimeValue{v}
				}
				qb.AddInCondition("updated_date_time", converted)
			}
		case *UInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				converted := make([]interface{}, len(filter.NotIn.Values))
				for i, v := range filter.NotIn.Values {
					converted[i] = DateTimeValue{v}
				}
				qb.AddNotInCondition("updated_date_time", converted)
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: hour_start_date_time
	if req.HourStartDateTime != nil {
		switch filter := req.HourStartDateTime.Filter.(type) {
		case *UInt32Filter_Eq:
			qb.AddCondition("hour_start_date_time", "=", DateTimeValue{filter.Eq})
		case *UInt32Filter_Ne:
			qb.AddCondition("hour_start_date_time", "!=", DateTimeValue{filter.Ne})
		case *UInt32Filter_Lt:
			qb.AddCondition("hour_start_date_time", "<", DateTimeValue{filter.Lt})
		case *UInt32Filter_Lte:
			qb.AddCondition("hour_start_date_time", "<=", DateTimeValue{filter.Lte})
		case *UInt32Filter_Gt:
			qb.AddCondition("hour_start_date_time", ">", DateTimeValue{filter.Gt})
		case *UInt32Filter_Gte:
			qb.AddCondition("hour_start_date_time", ">=", DateTimeValue{filter.Gte})
		case *UInt32Filter_Between:
			qb.AddBetweenCondition("hour_start_date_time", DateTimeValue{filter.Between.Min}, DateTimeValue{filter.Between.Max.GetValue()})
		case *UInt32Filter_In:
			if len(filter.In.Values) > 0 {
				converted := make([]interface{}, len(filter.In.Values))
				for i, v := range filter.In.Values {
					converted[i] = DateTimeValue{v}
				}
				qb.AddInCondition("hour_start_date_time", converted)
			}
		case *UInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				converted := make([]interface{}, len(filter.NotIn.Values))
				for i, v := range filter.NotIn.Values {
					converted[i] = DateTimeValue{v}
				}
				qb.AddNotInCondition("hour_start_date_time", converted)
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: total_slots
	if req.TotalSlots != nil {
		switch filter := req.TotalSlots.Filter.(type) {
		case *UInt32Filter_Eq:
			qb.AddCondition("total_slots", "=", filter.Eq)
		case *UInt32Filter_Ne:
			qb.AddCondition("total_slots", "!=", filter.Ne)
		case *UInt32Filter_Lt:
			qb.AddCondition("total_slots", "<", filter.Lt)
		case *UInt32Filter_Lte:
			qb.AddCondition("total_slots", "<=", filter.Lte)
		case *UInt32Filter_Gt:
			qb.AddCondition("total_slots", ">", filter.Gt)
		case *UInt32Filter_Gte:
			qb.AddCondition("total_slots", ">=", filter.Gte)
		case *UInt32Filter_Between:
			qb.AddBetweenCondition("total_slots", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt32Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("total_slots", UInt32SliceToInterface(filter.In.Values))
			}
		case *UInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("total_slots", UInt32SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: participated_count
	if req.ParticipatedCount != nil {
		switch filter := req.ParticipatedCount.Filter.(type) {
		case *UInt32Filter_Eq:
			qb.AddCondition("participated_count", "=", filter.Eq)
		case *UInt32Filter_Ne:
			qb.AddCondition("participated_count", "!=", filter.Ne)
		case *UInt32Filter_Lt:
			qb.AddCondition("participated_count", "<", filter.Lt)
		case *UInt32Filter_Lte:
			qb.AddCondition("participated_count", "<=", filter.Lte)
		case *UInt32Filter_Gt:
			qb.AddCondition("participated_count", ">", filter.Gt)
		case *UInt32Filter_Gte:
			qb.AddCondition("participated_count", ">=", filter.Gte)
		case *UInt32Filter_Between:
			qb.AddBetweenCondition("participated_count", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt32Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("participated_count", UInt32SliceToInterface(filter.In.Values))
			}
		case *UInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("participated_count", UInt32SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: missed_count
	if req.MissedCount != nil {
		switch filter := req.MissedCount.Filter.(type) {
		case *UInt32Filter_Eq:
			qb.AddCondition("missed_count", "=", filter.Eq)
		case *UInt32Filter_Ne:
			qb.AddCondition("missed_count", "!=", filter.Ne)
		case *UInt32Filter_Lt:
			qb.AddCondition("missed_count", "<", filter.Lt)
		case *UInt32Filter_Lte:
			qb.AddCondition("missed_count", "<=", filter.Lte)
		case *UInt32Filter_Gt:
			qb.AddCondition("missed_count", ">", filter.Gt)
		case *UInt32Filter_Gte:
			qb.AddCondition("missed_count", ">=", filter.Gte)
		case *UInt32Filter_Between:
			qb.AddBetweenCondition("missed_count", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt32Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("missed_count", UInt32SliceToInterface(filter.In.Values))
			}
		case *UInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("missed_count", UInt32SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Handle pagination per AIP-132
	// Validate page size
	if req.PageSize < 0 {
		return SQLQuery{}, fmt.Errorf("page_size must be non-negative, got %d", req.PageSize)
	}
	if req.PageSize > 10000 {
		return SQLQuery{}, fmt.Errorf("page_size must not exceed %d, got %d", 10000, req.PageSize)
	}

	var limit, offset uint32
	limit = 100 // Default page size
	if req.PageSize > 0 {
		limit = uint32(req.PageSize)
	}
	if req.PageToken != "" {
		decodedOffset, err := DecodePageToken(req.PageToken)
		if err != nil {
			return SQLQuery{}, fmt.Errorf("invalid page_token: %w", err)
		}
		offset = decodedOffset
	}

	// Handle custom ordering if provided
	var orderByClause string
	if req.OrderBy != "" {
		validFields := []string{"updated_date_time", "hour_start_date_time", "validator_index", "total_slots", "participated_count", "missed_count"}
		orderFields, err := ParseOrderBy(req.OrderBy, validFields)
		if err != nil {
			return SQLQuery{}, fmt.Errorf("invalid order_by: %w", err)
		}
		orderByClause = BuildOrderByClause(orderFields)
	} else {
		// Default sorting by primary key
		orderByClause = " ORDER BY validator_index" + ", hour_start_date_time"
	}

	// Build column list
	columns := []string{"toUnixTimestamp(`updated_date_time`) AS `updated_date_time`", "toUnixTimestamp(`hour_start_date_time`) AS `hour_start_date_time`", "validator_index", "total_slots", "participated_count", "missed_count"}

	return BuildParameterizedQuery("fct_sync_committee_participation_by_validator_hourly", columns, qb, orderByClause, limit, offset, options...)
}

// BuildGetFctSyncCommitteeParticipationByValidatorHourlyQuery constructs a parameterized SQL query from a GetFctSyncCommitteeParticipationByValidatorHourlyRequest
func BuildGetFctSyncCommitteeParticipationByValidatorHourlyQuery(req *GetFctSyncCommitteeParticipationByValidatorHourlyRequest, options ...QueryOption) (SQLQuery, error) {
	// Validate primary key is provided
	if req.ValidatorIndex == 0 {
		return SQLQuery{}, fmt.Errorf("primary key field validator_index is required")
	}

	// Build query with primary key condition
	qb := NewQueryBuilder()
	qb.AddCondition("validator_index", "=", req.ValidatorIndex)

	// Build ORDER BY clause
	orderByClause := " ORDER BY validator_index, hour_start_date_time"

	// Build column list
	columns := []string{"toUnixTimestamp(`updated_date_time`) AS `updated_date_time`", "toUnixTimestamp(`hour_start_date_time`) AS `hour_start_date_time`", "validator_index", "total_slots", "participated_count", "missed_count"}

	// Return single record
	return BuildParameterizedQuery("fct_sync_committee_participation_by_validator_hourly", columns, qb, orderByClause, 1, 0, options...)
}
