// Code generated by clickhouse-proto-gen. DO NOT EDIT.
// Scannable result row for int_custody_probe

package clickhouse

import (
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
)

// IntCustodyProbeRow is a ClickHouse-scannable result row for the int_custody_probe table.
// Field types match the SELECT column expressions produced by
// BuildListIntCustodyProbeQuery and BuildGetIntCustodyProbeQuery: DateTime columns are unix
// timestamps, DateTime64 columns are unix microseconds, Date and large
// integer and decimal columns are strings, and FixedString columns are
// nullable. Scan rows with clickhouse-go's ScanStruct.
type IntCustodyProbeRow struct {
	UpdatedDateTime uint32 `ch:"updated_date_time" json:"updated_date_time"`
	ProbeDateTime uint32 `ch:"probe_date_time" json:"probe_date_time"`
	Slot uint32 `ch:"slot" json:"slot"`
	SlotStartDateTime uint32 `ch:"slot_start_date_time" json:"slot_start_date_time"`
	PeerIdUniqueKey int64 `ch:"peer_id_unique_key" json:"peer_id_unique_key"`
	Result string `ch:"result" json:"result"`
	Error string `ch:"error" json:"error"`
	ColumnIndices []uint64 `ch:"column_indices" json:"column_indices"`
	BlobSubmitters []string `ch:"blob_submitters" json:"blob_submitters"`
	ResponseTimeMs int32 `ch:"response_time_ms" json:"response_time_ms"`
	Username string `ch:"username" json:"username"`
	NodeId string `ch:"node_id" json:"node_id"`
	Classification string `ch:"classification" json:"classification"`
	MetaClientVersion string `ch:"meta_client_version" json:"meta_client_version"`
	MetaClientImplementation string `ch:"meta_client_implementation" json:"meta_client_implementation"`
	MetaClientOs string `ch:"meta_client_os" json:"meta_client_os"`
	MetaClientGeoCity string `ch:"meta_client_geo_city" json:"meta_client_geo_city"`
	MetaClientGeoCountry string `ch:"meta_client_geo_country" json:"meta_client_geo_country"`
	MetaClientGeoCountryCode string `ch:"meta_client_geo_country_code" json:"meta_client_geo_country_code"`
	MetaClientGeoContinentCode string `ch:"meta_client_geo_continent_code" json:"meta_client_geo_continent_code"`
	MetaClientGeoLongitude *float64 `ch:"meta_client_geo_longitude" json:"meta_client_geo_longitude"`
	MetaClientGeoLatitude *float64 `ch:"meta_client_geo_latitude" json:"meta_client_geo_latitude"`
	MetaClientGeoAutonomousSystemNumber *uint32 `ch:"meta_client_geo_autonomous_system_number" json:"meta_client_geo_autonomous_system_number"`
	MetaClientGeoAutonomousSystemOrganization *string `ch:"meta_client_geo_autonomous_system_organization" json:"meta_client_geo_autonomous_system_organization"`
	MetaPeerImplementation string `ch:"meta_peer_implementation" json:"meta_peer_implementation"`
	MetaPeerVersion string `ch:"meta_peer_version" json:"meta_peer_version"`
	MetaPeerPlatform string `ch:"meta_peer_platform" json:"meta_peer_platform"`
	MetaPeerGeoCity string `ch:"meta_peer_geo_city" json:"meta_peer_geo_city"`
	MetaPeerGeoCountry string `ch:"meta_peer_geo_country" json:"meta_peer_geo_country"`
	MetaPeerGeoCountryCode string `ch:"meta_peer_geo_country_code" json:"meta_peer_geo_country_code"`
	MetaPeerGeoContinentCode string `ch:"meta_peer_geo_continent_code" json:"meta_peer_geo_continent_code"`
	MetaPeerGeoLongitude *float64 `ch:"meta_peer_geo_longitude" json:"meta_peer_geo_longitude"`
	MetaPeerGeoLatitude *float64 `ch:"meta_peer_geo_latitude" json:"meta_peer_geo_latitude"`
	MetaPeerGeoAutonomousSystemNumber *uint32 `ch:"meta_peer_geo_autonomous_system_number" json:"meta_peer_geo_autonomous_system_number"`
	MetaPeerGeoAutonomousSystemOrganization *string `ch:"meta_peer_geo_autonomous_system_organization" json:"meta_peer_geo_autonomous_system_organization"`
}

// TableName returns the ClickHouse table this row maps to.
func (IntCustodyProbeRow) TableName() string {
	return "int_custody_probe"
}

// ToProto converts the row to its protobuf message.
func (r *IntCustodyProbeRow) ToProto() *IntCustodyProbe {
	p := &IntCustodyProbe{}

	p.UpdatedDateTime = r.UpdatedDateTime
	p.ProbeDateTime = r.ProbeDateTime
	p.Slot = r.Slot
	p.SlotStartDateTime = r.SlotStartDateTime
	p.PeerIdUniqueKey = r.PeerIdUniqueKey
	p.Result = r.Result
	p.Error = r.Error
	p.ColumnIndices = r.ColumnIndices
	p.BlobSubmitters = r.BlobSubmitters
	p.ResponseTimeMs = r.ResponseTimeMs
	p.Username = r.Username
	p.NodeId = r.NodeId
	p.Classification = r.Classification
	p.MetaClientVersion = r.MetaClientVersion
	p.MetaClientImplementation = r.MetaClientImplementation
	p.MetaClientOs = r.MetaClientOs
	p.MetaClientGeoCity = r.MetaClientGeoCity
	p.MetaClientGeoCountry = r.MetaClientGeoCountry
	p.MetaClientGeoCountryCode = r.MetaClientGeoCountryCode
	p.MetaClientGeoContinentCode = r.MetaClientGeoContinentCode
	if r.MetaClientGeoLongitude != nil {
		p.MetaClientGeoLongitude = wrapperspb.Double(*r.MetaClientGeoLongitude)
	}
	if r.MetaClientGeoLatitude != nil {
		p.MetaClientGeoLatitude = wrapperspb.Double(*r.MetaClientGeoLatitude)
	}
	if r.MetaClientGeoAutonomousSystemNumber != nil {
		p.MetaClientGeoAutonomousSystemNumber = wrapperspb.UInt32(*r.MetaClientGeoAutonomousSystemNumber)
	}
	if r.MetaClientGeoAutonomousSystemOrganization != nil {
		p.MetaClientGeoAutonomousSystemOrganization = wrapperspb.String(*r.MetaClientGeoAutonomousSystemOrganization)
	}
	p.MetaPeerImplementation = r.MetaPeerImplementation
	p.MetaPeerVersion = r.MetaPeerVersion
	p.MetaPeerPlatform = r.MetaPeerPlatform
	p.MetaPeerGeoCity = r.MetaPeerGeoCity
	p.MetaPeerGeoCountry = r.MetaPeerGeoCountry
	p.MetaPeerGeoCountryCode = r.MetaPeerGeoCountryCode
	p.MetaPeerGeoContinentCode = r.MetaPeerGeoContinentCode
	if r.MetaPeerGeoLongitude != nil {
		p.MetaPeerGeoLongitude = wrapperspb.Double(*r.MetaPeerGeoLongitude)
	}
	if r.MetaPeerGeoLatitude != nil {
		p.MetaPeerGeoLatitude = wrapperspb.Double(*r.MetaPeerGeoLatitude)
	}
	if r.MetaPeerGeoAutonomousSystemNumber != nil {
		p.MetaPeerGeoAutonomousSystemNumber = wrapperspb.UInt32(*r.MetaPeerGeoAutonomousSystemNumber)
	}
	if r.MetaPeerGeoAutonomousSystemOrganization != nil {
		p.MetaPeerGeoAutonomousSystemOrganization = wrapperspb.String(*r.MetaPeerGeoAutonomousSystemOrganization)
	}
	return p
}
