// Code generated by clickhouse-proto-gen. DO NOT EDIT.
// SQL query builder for int_address_diffs

package clickhouse

import (
	"fmt"
)

// BuildListIntAddressDiffsQuery constructs a parameterized SQL query from a ListIntAddressDiffsRequest
func BuildListIntAddressDiffsQuery(req *ListIntAddressDiffsRequest, options ...QueryOption) (SQLQuery, error) {
	// Validate that at least one primary key is provided
	// Primary keys can come from base table or projections
	if req.Address == nil {
		return SQLQuery{}, fmt.Errorf("primary key field address is required")
	}

	// Build query using QueryBuilder
	qb := NewQueryBuilder()

	// Add primary key filter
	switch filter := req.Address.Filter.(type) {
	case *StringFilter_Eq:
		qb.AddCondition("address", "=", filter.Eq)
	case *StringFilter_Ne:
		qb.AddCondition("address", "!=", filter.Ne)
	case *StringFilter_Contains:
		qb.AddLikeCondition("address", "%" + filter.Contains + "%")
	case *StringFilter_StartsWith:
		qb.AddLikeCondition("address", filter.StartsWith + "%")
	case *StringFilter_EndsWith:
		qb.AddLikeCondition("address", "%" + filter.EndsWith)
	case *StringFilter_Like:
		qb.AddLikeCondition("address", filter.Like)
	case *StringFilter_NotLike:
		qb.AddNotLikeCondition("address", filter.NotLike)
	case *StringFilter_In:
		if len(filter.In.Values) > 0 {
			qb.AddInCondition("address", StringSliceToInterface(filter.In.Values))
		}
	case *StringFilter_NotIn:
		if len(filter.NotIn.Values) > 0 {
			qb.AddNotInCondition("address", StringSliceToInterface(filter.NotIn.Values))
		}
	default:
		// Unsupported filter type
	}

	// Add filter for column: block_number
	if req.BlockNumber != nil {
		switch filter := req.BlockNumber.Filter.(type) {
		case *UInt32Filter_Eq:
			qb.AddCondition("block_number", "=", filter.Eq)
		case *UInt32Filter_Ne:
			qb.AddCondition("block_number", "!=", filter.Ne)
		case *UInt32Filter_Lt:
			qb.AddCondition("block_number", "<", filter.Lt)
		case *UInt32Filter_Lte:
			qb.AddCondition("block_number", "<=", filter.Lte)
		case *UInt32Filter_Gt:
			qb.AddCondition("block_number", ">", filter.Gt)
		case *UInt32Filter_Gte:
			qb.AddCondition("block_number", ">=", filter.Gte)
		case *UInt32Filter_Between:
			qb.AddBetweenCondition("block_number", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt32Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("block_number", UInt32SliceToInterface(filter.In.Values))
			}
		case *UInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("block_number", UInt32SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: tx_count
	if req.TxCount != nil {
		switch filter := req.TxCount.Filter.(type) {
		case *UInt32Filter_Eq:
			qb.AddCondition("tx_count", "=", filter.Eq)
		case *UInt32Filter_Ne:
			qb.AddCondition("tx_count", "!=", filter.Ne)
		case *UInt32Filter_Lt:
			qb.AddCondition("tx_count", "<", filter.Lt)
		case *UInt32Filter_Lte:
			qb.AddCondition("tx_count", "<=", filter.Lte)
		case *UInt32Filter_Gt:
			qb.AddCondition("tx_count", ">", filter.Gt)
		case *UInt32Filter_Gte:
			qb.AddCondition("tx_count", ">=", filter.Gte)
		case *UInt32Filter_Between:
			qb.AddBetweenCondition("tx_count", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt32Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("tx_count", UInt32SliceToInterface(filter.In.Values))
			}
		case *UInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("tx_count", UInt32SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: last_tx_index
	if req.LastTxIndex != nil {
		switch filter := req.LastTxIndex.Filter.(type) {
		case *UInt32Filter_Eq:
			qb.AddCondition("last_tx_index", "=", filter.Eq)
		case *UInt32Filter_Ne:
			qb.AddCondition("last_tx_index", "!=", filter.Ne)
		case *UInt32Filter_Lt:
			qb.AddCondition("last_tx_index", "<", filter.Lt)
		case *UInt32Filter_Lte:
			qb.AddCondition("last_tx_index", "<=", filter.Lte)
		case *UInt32Filter_Gt:
			qb.AddCondition("last_tx_index", ">", filter.Gt)
		case *UInt32Filter_Gte:
			qb.AddCondition("last_tx_index", ">=", filter.Gte)
		case *UInt32Filter_Between:
			qb.AddBetweenCondition("last_tx_index", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt32Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("last_tx_index", UInt32SliceToInterface(filter.In.Values))
			}
		case *UInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("last_tx_index", UInt32SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Handle pagination per AIP-132
	// Validate page size
	if req.PageSize < 0 {
		return SQLQuery{}, fmt.Errorf("page_size must be non-negative, got %d", req.PageSize)
	}
	if req.PageSize > 10000 {
		return SQLQuery{}, fmt.Errorf("page_size must not exceed %d, got %d", 10000, req.PageSize)
	}

	var limit, offset uint32
	limit = 100 // Default page size
	if req.PageSize > 0 {
		limit = uint32(req.PageSize)
	}
	if req.PageToken != "" {
		decodedOffset, err := DecodePageToken(req.PageToken)
		if err != nil {
			return SQLQuery{}, fmt.Errorf("invalid page_token: %w", err)
		}
		offset = decodedOffset
	}

	// Handle custom ordering if provided
	var orderByClause string
	if req.OrderBy != "" {
		validFields := []string{"address", "block_number", "tx_count", "last_tx_index"}
		orderFields, err := ParseOrderBy(req.OrderBy, validFields)
		if err != nil {
			return SQLQuery{}, fmt.Errorf("invalid order_by: %w", err)
		}
		orderByClause = BuildOrderByClause(orderFields)
	} else {
		// Default sorting by primary key
		orderByClause = " ORDER BY address"
	}

	// Build column list
	columns := []string{"address", "block_number", "tx_count", "last_tx_index"}

	return BuildParameterizedQuery("int_address_diffs", columns, qb, orderByClause, limit, offset, options...)
}

// BuildGetIntAddressDiffsQuery constructs a parameterized SQL query from a GetIntAddressDiffsRequest
func BuildGetIntAddressDiffsQuery(req *GetIntAddressDiffsRequest, options ...QueryOption) (SQLQuery, error) {
	// Validate primary key is provided
	if req.Address == "" {
		return SQLQuery{}, fmt.Errorf("primary key field address is required")
	}

	// Build query with primary key condition
	qb := NewQueryBuilder()
	qb.AddCondition("address", "=", req.Address)

	// Build ORDER BY clause
	orderByClause := " ORDER BY address"

	// Build column list
	columns := []string{"address", "block_number", "tx_count", "last_tx_index"}

	// Return single record
	return BuildParameterizedQuery("int_address_diffs", columns, qb, orderByClause, 1, 0, options...)
}
