// Code generated by clickhouse-proto-gen. DO NOT EDIT.
// SQL query builder for int_storage_slot_expiry_1m

package clickhouse

import (
	"fmt"
)

// BuildListIntStorageSlotExpiry1MQuery constructs a parameterized SQL query from a ListIntStorageSlotExpiry1MRequest
func BuildListIntStorageSlotExpiry1MQuery(req *ListIntStorageSlotExpiry1MRequest, options ...QueryOption) (SQLQuery, error) {
	// Validate that at least one primary key is provided
	// Primary keys can come from base table or projections
	if req.BlockNumber == nil {
		return SQLQuery{}, fmt.Errorf("primary key field block_number is required")
	}

	// Build query using QueryBuilder
	qb := NewQueryBuilder()

	// Add primary key filter
	switch filter := req.BlockNumber.Filter.(type) {
	case *UInt32Filter_Eq:
		qb.AddCondition("block_number", "=", filter.Eq)
	case *UInt32Filter_Ne:
		qb.AddCondition("block_number", "!=", filter.Ne)
	case *UInt32Filter_Lt:
		qb.AddCondition("block_number", "<", filter.Lt)
	case *UInt32Filter_Lte:
		qb.AddCondition("block_number", "<=", filter.Lte)
	case *UInt32Filter_Gt:
		qb.AddCondition("block_number", ">", filter.Gt)
	case *UInt32Filter_Gte:
		qb.AddCondition("block_number", ">=", filter.Gte)
	case *UInt32Filter_Between:
		qb.AddBetweenCondition("block_number", filter.Between.Min, filter.Between.Max.GetValue())
	case *UInt32Filter_In:
		if len(filter.In.Values) > 0 {
			qb.AddInCondition("block_number", UInt32SliceToInterface(filter.In.Values))
		}
	case *UInt32Filter_NotIn:
		if len(filter.NotIn.Values) > 0 {
			qb.AddNotInCondition("block_number", UInt32SliceToInterface(filter.NotIn.Values))
		}
	default:
		// Unsupported filter type
	}

	// Add filter for column: updated_date_time
	if req.UpdatedDateTime != nil {
		switch filter := req.UpdatedDateTime.Filter.(type) {
		case *UInt32Filter_Eq:
			qb.AddCondition("updated_date_time", "=", DateTimeValue{filter.Eq})
		case *UInt32Filter_Ne:
			qb.AddCondition("updated_date_time", "!=", DateTimeValue{filter.Ne})
		case *UInt32Filter_Lt:
			qb.AddCondition("updated_date_time", "<", DateTimeValue{filter.Lt})
		case *UInt32Filter_Lte:
			qb.AddCondition("updated_date_time", "<=", DateTimeValue{filter.Lte})
		case *UInt32Filter_Gt:
			qb.AddCondition("updated_date_time", ">", DateTimeValue{filter.Gt})
		case *UInt32Filter_Gte:
			qb.AddCondition("updated_date_time", ">=", DateTimeValue{filter.Gte})
		case *UInt32Filter_Between:
			qb.AddBetweenCondition("updated_date_time", DateTimeValue{filter.Between.Min}, DateTimeValue{filter.Between.Max.GetValue()})
		case *UInt32Filter_In:
			if len(filter.In.Values) > 0 {
				converted := make([]interface{}, len(filter.In.Values))
				for i, v := range filter.In.Values {
					converted[i] = DateTimeValue{v}
				}
				qb.AddInCondition("updated_date_time", converted)
			}
		case *UInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				converted := make([]interface{}, len(filter.NotIn.Values))
				for i, v := range filter.NotIn.Values {
					converted[i] = DateTimeValue{v}
				}
				qb.AddNotInCondition("updated_date_time", converted)
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: address
	if req.Address != nil {
		switch filter := req.Address.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("address", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("address", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("address", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("address", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("address", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("address", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("address", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("address", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("address", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: slot_key
	if req.SlotKey != nil {
		switch filter := req.SlotKey.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("slot_key", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("slot_key", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("slot_key", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("slot_key", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("slot_key", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("slot_key", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("slot_key", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("slot_key", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("slot_key", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: touch_block
	if req.TouchBlock != nil {
		switch filter := req.TouchBlock.Filter.(type) {
		case *UInt32Filter_Eq:
			qb.AddCondition("touch_block", "=", filter.Eq)
		case *UInt32Filter_Ne:
			qb.AddCondition("touch_block", "!=", filter.Ne)
		case *UInt32Filter_Lt:
			qb.AddCondition("touch_block", "<", filter.Lt)
		case *UInt32Filter_Lte:
			qb.AddCondition("touch_block", "<=", filter.Lte)
		case *UInt32Filter_Gt:
			qb.AddCondition("touch_block", ">", filter.Gt)
		case *UInt32Filter_Gte:
			qb.AddCondition("touch_block", ">=", filter.Gte)
		case *UInt32Filter_Between:
			qb.AddBetweenCondition("touch_block", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt32Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("touch_block", UInt32SliceToInterface(filter.In.Values))
			}
		case *UInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("touch_block", UInt32SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: effective_bytes
	if req.EffectiveBytes != nil {
		switch filter := req.EffectiveBytes.Filter.(type) {
		case *UInt32Filter_Eq:
			qb.AddCondition("effective_bytes", "=", filter.Eq)
		case *UInt32Filter_Ne:
			qb.AddCondition("effective_bytes", "!=", filter.Ne)
		case *UInt32Filter_Lt:
			qb.AddCondition("effective_bytes", "<", filter.Lt)
		case *UInt32Filter_Lte:
			qb.AddCondition("effective_bytes", "<=", filter.Lte)
		case *UInt32Filter_Gt:
			qb.AddCondition("effective_bytes", ">", filter.Gt)
		case *UInt32Filter_Gte:
			qb.AddCondition("effective_bytes", ">=", filter.Gte)
		case *UInt32Filter_Between:
			qb.AddBetweenCondition("effective_bytes", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt32Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("effective_bytes", UInt32SliceToInterface(filter.In.Values))
			}
		case *UInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("effective_bytes", UInt32SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Handle pagination per AIP-132
	// Validate page size
	if req.PageSize < 0 {
		return SQLQuery{}, fmt.Errorf("page_size must be non-negative, got %d", req.PageSize)
	}
	if req.PageSize > 10000 {
		return SQLQuery{}, fmt.Errorf("page_size must not exceed %d, got %d", 10000, req.PageSize)
	}

	var limit, offset uint32
	limit = 100 // Default page size
	if req.PageSize > 0 {
		limit = uint32(req.PageSize)
	}
	if req.PageToken != "" {
		decodedOffset, err := DecodePageToken(req.PageToken)
		if err != nil {
			return SQLQuery{}, fmt.Errorf("invalid page_token: %w", err)
		}
		offset = decodedOffset
	}

	// Handle custom ordering if provided
	var orderByClause string
	if req.OrderBy != "" {
		validFields := []string{"updated_date_time", "block_number", "address", "slot_key", "touch_block", "effective_bytes"}
		orderFields, err := ParseOrderBy(req.OrderBy, validFields)
		if err != nil {
			return SQLQuery{}, fmt.Errorf("invalid order_by: %w", err)
		}
		orderByClause = BuildOrderByClause(orderFields)
	} else {
		// Default sorting by primary key
		orderByClause = " ORDER BY block_number" + ", address" + ", slot_key" + ", touch_block"
	}

	// Build column list
	columns := []string{"toUnixTimestamp(`updated_date_time`) AS `updated_date_time`", "block_number", "address", "slot_key", "touch_block", "toUInt32(`effective_bytes`) AS `effective_bytes`"}

	return BuildParameterizedQuery("int_storage_slot_expiry_1m", columns, qb, orderByClause, limit, offset, options...)
}

// BuildGetIntStorageSlotExpiry1MQuery constructs a parameterized SQL query from a GetIntStorageSlotExpiry1MRequest
func BuildGetIntStorageSlotExpiry1MQuery(req *GetIntStorageSlotExpiry1MRequest, options ...QueryOption) (SQLQuery, error) {
	// Validate primary key is provided
	if req.BlockNumber == 0 {
		return SQLQuery{}, fmt.Errorf("primary key field block_number is required")
	}

	// Build query with primary key condition
	qb := NewQueryBuilder()
	qb.AddCondition("block_number", "=", req.BlockNumber)

	// Build ORDER BY clause
	orderByClause := " ORDER BY block_number, address, slot_key, touch_block"

	// Build column list
	columns := []string{"toUnixTimestamp(`updated_date_time`) AS `updated_date_time`", "block_number", "address", "slot_key", "touch_block", "toUInt32(`effective_bytes`) AS `effective_bytes`"}

	// Return single record
	return BuildParameterizedQuery("int_storage_slot_expiry_1m", columns, qb, orderByClause, 1, 0, options...)
}
