// Code generated by clickhouse-proto-gen. DO NOT EDIT.
// Scannable result row for int_contract_storage_state_with_expiry_by_block

package clickhouse

// IntContractStorageStateWithExpiryByBlockRow is a ClickHouse-scannable result row for the int_contract_storage_state_with_expiry_by_block table.
// Field types match the SELECT column expressions produced by
// BuildListIntContractStorageStateWithExpiryByBlockQuery and BuildGetIntContractStorageStateWithExpiryByBlockQuery: DateTime columns are unix
// timestamps, DateTime64 columns are unix microseconds, Date and large
// integer and decimal columns are strings, and FixedString columns are
// nullable. Scan rows with clickhouse-go's ScanStruct.
type IntContractStorageStateWithExpiryByBlockRow struct {
	UpdatedDateTime uint32 `ch:"updated_date_time" json:"updated_date_time"`
	BlockNumber uint32 `ch:"block_number" json:"block_number"`
	ExpiryPolicy string `ch:"expiry_policy" json:"expiry_policy"`
	ActiveSlots int64 `ch:"active_slots" json:"active_slots"`
	EffectiveBytes int64 `ch:"effective_bytes" json:"effective_bytes"`
	ActiveContracts int64 `ch:"active_contracts" json:"active_contracts"`
}

// TableName returns the ClickHouse table this row maps to.
func (IntContractStorageStateWithExpiryByBlockRow) TableName() string {
	return "int_contract_storage_state_with_expiry_by_block"
}

// ToProto converts the row to its protobuf message.
func (r *IntContractStorageStateWithExpiryByBlockRow) ToProto() *IntContractStorageStateWithExpiryByBlock {
	p := &IntContractStorageStateWithExpiryByBlock{}

	p.UpdatedDateTime = r.UpdatedDateTime
	p.BlockNumber = r.BlockNumber
	p.ExpiryPolicy = r.ExpiryPolicy
	p.ActiveSlots = r.ActiveSlots
	p.EffectiveBytes = r.EffectiveBytes
	p.ActiveContracts = r.ActiveContracts
	return p
}
