// Code generated by clickhouse-proto-gen. DO NOT EDIT.
// Scannable result row for int_block_payload_ptc_vote_canonical

package clickhouse

// IntBlockPayloadPtcVoteCanonicalRow is a ClickHouse-scannable result row for the int_block_payload_ptc_vote_canonical table.
// Field types match the SELECT column expressions produced by
// BuildListIntBlockPayloadPtcVoteCanonicalQuery and BuildGetIntBlockPayloadPtcVoteCanonicalQuery: DateTime columns are unix
// timestamps, DateTime64 columns are unix microseconds, Date and large
// integer and decimal columns are strings, and FixedString columns are
// nullable. Scan rows with clickhouse-go's ScanStruct.
type IntBlockPayloadPtcVoteCanonicalRow struct {
	UpdatedDateTime uint32 `ch:"updated_date_time" json:"updated_date_time"`
	Slot uint32 `ch:"slot" json:"slot"`
	SlotStartDateTime uint32 `ch:"slot_start_date_time" json:"slot_start_date_time"`
	Epoch uint32 `ch:"epoch" json:"epoch"`
	EpochStartDateTime uint32 `ch:"epoch_start_date_time" json:"epoch_start_date_time"`
	BlockRoot string `ch:"block_root" json:"block_root"`
	BlockVersion string `ch:"block_version" json:"block_version"`
	IncludedInSlot uint32 `ch:"included_in_slot" json:"included_in_slot"`
	IncludedInBlockRoot string `ch:"included_in_block_root" json:"included_in_block_root"`
	PtcValidators uint32 `ch:"ptc_validators" json:"ptc_validators"`
	PayloadPresentVotes uint32 `ch:"payload_present_votes" json:"payload_present_votes"`
	BlobDataAvailableVotes uint32 `ch:"blob_data_available_votes" json:"blob_data_available_votes"`
}

// TableName returns the ClickHouse table this row maps to.
func (IntBlockPayloadPtcVoteCanonicalRow) TableName() string {
	return "int_block_payload_ptc_vote_canonical"
}

// ToProto converts the row to its protobuf message.
func (r *IntBlockPayloadPtcVoteCanonicalRow) ToProto() *IntBlockPayloadPtcVoteCanonical {
	p := &IntBlockPayloadPtcVoteCanonical{}

	p.UpdatedDateTime = r.UpdatedDateTime
	p.Slot = r.Slot
	p.SlotStartDateTime = r.SlotStartDateTime
	p.Epoch = r.Epoch
	p.EpochStartDateTime = r.EpochStartDateTime
	p.BlockRoot = r.BlockRoot
	p.BlockVersion = r.BlockVersion
	p.IncludedInSlot = r.IncludedInSlot
	p.IncludedInBlockRoot = r.IncludedInBlockRoot
	p.PtcValidators = r.PtcValidators
	p.PayloadPresentVotes = r.PayloadPresentVotes
	p.BlobDataAvailableVotes = r.BlobDataAvailableVotes
	return p
}
