// Code generated by clickhouse-proto-gen. DO NOT EDIT.
// Scannable result row for int_contract_selfdestruct

package clickhouse

import (
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
)

// IntContractSelfdestructRow is a ClickHouse-scannable result row for the int_contract_selfdestruct table.
// Field types match the SELECT column expressions produced by
// BuildListIntContractSelfdestructQuery and BuildGetIntContractSelfdestructQuery: DateTime columns are unix
// timestamps, DateTime64 columns are unix microseconds, Date and large
// integer and decimal columns are strings, and FixedString columns are
// nullable. Scan rows with clickhouse-go's ScanStruct.
type IntContractSelfdestructRow struct {
	UpdatedDateTime uint32 `ch:"updated_date_time" json:"updated_date_time"`
	BlockNumber uint32 `ch:"block_number" json:"block_number"`
	TransactionHash string `ch:"transaction_hash" json:"transaction_hash"`
	TransactionIndex uint32 `ch:"transaction_index" json:"transaction_index"`
	InternalIndex uint32 `ch:"internal_index" json:"internal_index"`
	Address string `ch:"address" json:"address"`
	Beneficiary string `ch:"beneficiary" json:"beneficiary"`
	ValueTransferred string `ch:"value_transferred" json:"value_transferred"`
	Ephemeral bool `ch:"ephemeral" json:"ephemeral"`
	StorageCleared bool `ch:"storage_cleared" json:"storage_cleared"`
	CreationBlock *uint32 `ch:"creation_block" json:"creation_block"`
	CreationTransactionHash *string `ch:"creation_transaction_hash" json:"creation_transaction_hash"`
}

// TableName returns the ClickHouse table this row maps to.
func (IntContractSelfdestructRow) TableName() string {
	return "int_contract_selfdestruct"
}

// ToProto converts the row to its protobuf message.
func (r *IntContractSelfdestructRow) ToProto() *IntContractSelfdestruct {
	p := &IntContractSelfdestruct{}

	p.UpdatedDateTime = r.UpdatedDateTime
	p.BlockNumber = r.BlockNumber
	p.TransactionHash = r.TransactionHash
	p.TransactionIndex = r.TransactionIndex
	p.InternalIndex = r.InternalIndex
	p.Address = r.Address
	p.Beneficiary = r.Beneficiary
	p.ValueTransferred = r.ValueTransferred
	p.Ephemeral = r.Ephemeral
	p.StorageCleared = r.StorageCleared
	if r.CreationBlock != nil {
		p.CreationBlock = wrapperspb.UInt32(*r.CreationBlock)
	}
	if r.CreationTransactionHash != nil {
		p.CreationTransactionHash = wrapperspb.String(*r.CreationTransactionHash)
	}
	return p
}
