// Code generated by clickhouse-proto-gen. DO NOT EDIT.
// Scannable result row for int_attestation_attested_canonical

package clickhouse

// IntAttestationAttestedCanonicalRow is a ClickHouse-scannable result row for the int_attestation_attested_canonical table.
// Field types match the SELECT column expressions produced by
// BuildListIntAttestationAttestedCanonicalQuery and BuildGetIntAttestationAttestedCanonicalQuery: DateTime columns are unix
// timestamps, DateTime64 columns are unix microseconds, Date and large
// integer and decimal columns are strings, and FixedString columns are
// nullable. Scan rows with clickhouse-go's ScanStruct.
type IntAttestationAttestedCanonicalRow struct {
	UpdatedDateTime uint32 `ch:"updated_date_time" json:"updated_date_time"`
	Slot uint32 `ch:"slot" json:"slot"`
	SlotStartDateTime uint32 `ch:"slot_start_date_time" json:"slot_start_date_time"`
	Epoch uint32 `ch:"epoch" json:"epoch"`
	EpochStartDateTime uint32 `ch:"epoch_start_date_time" json:"epoch_start_date_time"`
	SourceEpoch uint32 `ch:"source_epoch" json:"source_epoch"`
	SourceEpochStartDateTime uint32 `ch:"source_epoch_start_date_time" json:"source_epoch_start_date_time"`
	SourceRoot *string `ch:"source_root" json:"source_root"`
	TargetEpoch uint32 `ch:"target_epoch" json:"target_epoch"`
	TargetEpochStartDateTime uint32 `ch:"target_epoch_start_date_time" json:"target_epoch_start_date_time"`
	TargetRoot *string `ch:"target_root" json:"target_root"`
	BlockRoot string `ch:"block_root" json:"block_root"`
	AttestingValidatorIndex uint32 `ch:"attesting_validator_index" json:"attesting_validator_index"`
	InclusionDistance uint32 `ch:"inclusion_distance" json:"inclusion_distance"`
}

// TableName returns the ClickHouse table this row maps to.
func (IntAttestationAttestedCanonicalRow) TableName() string {
	return "int_attestation_attested_canonical"
}

// ToProto converts the row to its protobuf message.
func (r *IntAttestationAttestedCanonicalRow) ToProto() *IntAttestationAttestedCanonical {
	p := &IntAttestationAttestedCanonical{}

	p.UpdatedDateTime = r.UpdatedDateTime
	p.Slot = r.Slot
	p.SlotStartDateTime = r.SlotStartDateTime
	p.Epoch = r.Epoch
	p.EpochStartDateTime = r.EpochStartDateTime
	p.SourceEpoch = r.SourceEpoch
	p.SourceEpochStartDateTime = r.SourceEpochStartDateTime
	if r.SourceRoot != nil {
		p.SourceRoot = *r.SourceRoot
	}
	p.TargetEpoch = r.TargetEpoch
	p.TargetEpochStartDateTime = r.TargetEpochStartDateTime
	if r.TargetRoot != nil {
		p.TargetRoot = *r.TargetRoot
	}
	p.BlockRoot = r.BlockRoot
	p.AttestingValidatorIndex = r.AttestingValidatorIndex
	p.InclusionDistance = r.InclusionDistance
	return p
}
