// Code generated by clickhouse-proto-gen. DO NOT EDIT.
// Scannable result row for int_storage_slot_read

package clickhouse

// IntStorageSlotReadRow is a ClickHouse-scannable result row for the int_storage_slot_read table.
// Field types match the SELECT column expressions produced by
// BuildListIntStorageSlotReadQuery and BuildGetIntStorageSlotReadQuery: DateTime columns are unix
// timestamps, DateTime64 columns are unix microseconds, Date and large
// integer and decimal columns are strings, and FixedString columns are
// nullable. Scan rows with clickhouse-go's ScanStruct.
type IntStorageSlotReadRow struct {
	UpdatedDateTime uint32 `ch:"updated_date_time" json:"updated_date_time"`
	BlockNumber uint32 `ch:"block_number" json:"block_number"`
	Address string `ch:"address" json:"address"`
	SlotKey string `ch:"slot_key" json:"slot_key"`
}

// TableName returns the ClickHouse table this row maps to.
func (IntStorageSlotReadRow) TableName() string {
	return "int_storage_slot_read"
}

// ToProto converts the row to its protobuf message.
func (r *IntStorageSlotReadRow) ToProto() *IntStorageSlotRead {
	p := &IntStorageSlotRead{}

	p.UpdatedDateTime = r.UpdatedDateTime
	p.BlockNumber = r.BlockNumber
	p.Address = r.Address
	p.SlotKey = r.SlotKey
	return p
}
