// Code generated by clickhouse-proto-gen. DO NOT EDIT.
// Scannable result row for int_contract_storage_state_with_expiry_by_address

package clickhouse

// IntContractStorageStateWithExpiryByAddressRow is a ClickHouse-scannable result row for the int_contract_storage_state_with_expiry_by_address table.
// Field types match the SELECT column expressions produced by
// BuildListIntContractStorageStateWithExpiryByAddressQuery and BuildGetIntContractStorageStateWithExpiryByAddressQuery: DateTime columns are unix
// timestamps, DateTime64 columns are unix microseconds, Date and large
// integer and decimal columns are strings, and FixedString columns are
// nullable. Scan rows with clickhouse-go's ScanStruct.
type IntContractStorageStateWithExpiryByAddressRow struct {
	UpdatedDateTime uint32 `ch:"updated_date_time" json:"updated_date_time"`
	BlockNumber uint32 `ch:"block_number" json:"block_number"`
	Address string `ch:"address" json:"address"`
	ExpiryPolicy string `ch:"expiry_policy" json:"expiry_policy"`
	ActiveSlots int64 `ch:"active_slots" json:"active_slots"`
	EffectiveBytes int64 `ch:"effective_bytes" json:"effective_bytes"`
}

// TableName returns the ClickHouse table this row maps to.
func (IntContractStorageStateWithExpiryByAddressRow) TableName() string {
	return "int_contract_storage_state_with_expiry_by_address"
}

// ToProto converts the row to its protobuf message.
func (r *IntContractStorageStateWithExpiryByAddressRow) ToProto() *IntContractStorageStateWithExpiryByAddress {
	p := &IntContractStorageStateWithExpiryByAddress{}

	p.UpdatedDateTime = r.UpdatedDateTime
	p.BlockNumber = r.BlockNumber
	p.Address = r.Address
	p.ExpiryPolicy = r.ExpiryPolicy
	p.ActiveSlots = r.ActiveSlots
	p.EffectiveBytes = r.EffectiveBytes
	return p
}
