// Code generated by clickhouse-proto-gen. DO NOT EDIT.
// SQL query builder for int_contract_selfdestruct

package clickhouse

import (
	"fmt"
)

// BuildListIntContractSelfdestructQuery constructs a parameterized SQL query from a ListIntContractSelfdestructRequest
func BuildListIntContractSelfdestructQuery(req *ListIntContractSelfdestructRequest, options ...QueryOption) (SQLQuery, error) {
	// Validate that at least one primary key is provided
	// Primary keys can come from base table or projections
	if req.BlockNumber == nil {
		return SQLQuery{}, fmt.Errorf("primary key field block_number is required")
	}

	// Build query using QueryBuilder
	qb := NewQueryBuilder()

	// Add primary key filter
	switch filter := req.BlockNumber.Filter.(type) {
	case *UInt32Filter_Eq:
		qb.AddCondition("block_number", "=", filter.Eq)
	case *UInt32Filter_Ne:
		qb.AddCondition("block_number", "!=", filter.Ne)
	case *UInt32Filter_Lt:
		qb.AddCondition("block_number", "<", filter.Lt)
	case *UInt32Filter_Lte:
		qb.AddCondition("block_number", "<=", filter.Lte)
	case *UInt32Filter_Gt:
		qb.AddCondition("block_number", ">", filter.Gt)
	case *UInt32Filter_Gte:
		qb.AddCondition("block_number", ">=", filter.Gte)
	case *UInt32Filter_Between:
		qb.AddBetweenCondition("block_number", filter.Between.Min, filter.Between.Max.GetValue())
	case *UInt32Filter_In:
		if len(filter.In.Values) > 0 {
			qb.AddInCondition("block_number", UInt32SliceToInterface(filter.In.Values))
		}
	case *UInt32Filter_NotIn:
		if len(filter.NotIn.Values) > 0 {
			qb.AddNotInCondition("block_number", UInt32SliceToInterface(filter.NotIn.Values))
		}
	default:
		// Unsupported filter type
	}

	// Add filter for column: updated_date_time
	if req.UpdatedDateTime != nil {
		switch filter := req.UpdatedDateTime.Filter.(type) {
		case *UInt32Filter_Eq:
			qb.AddCondition("updated_date_time", "=", DateTimeValue{filter.Eq})
		case *UInt32Filter_Ne:
			qb.AddCondition("updated_date_time", "!=", DateTimeValue{filter.Ne})
		case *UInt32Filter_Lt:
			qb.AddCondition("updated_date_time", "<", DateTimeValue{filter.Lt})
		case *UInt32Filter_Lte:
			qb.AddCondition("updated_date_time", "<=", DateTimeValue{filter.Lte})
		case *UInt32Filter_Gt:
			qb.AddCondition("updated_date_time", ">", DateTimeValue{filter.Gt})
		case *UInt32Filter_Gte:
			qb.AddCondition("updated_date_time", ">=", DateTimeValue{filter.Gte})
		case *UInt32Filter_Between:
			qb.AddBetweenCondition("updated_date_time", DateTimeValue{filter.Between.Min}, DateTimeValue{filter.Between.Max.GetValue()})
		case *UInt32Filter_In:
			if len(filter.In.Values) > 0 {
				converted := make([]interface{}, len(filter.In.Values))
				for i, v := range filter.In.Values {
					converted[i] = DateTimeValue{v}
				}
				qb.AddInCondition("updated_date_time", converted)
			}
		case *UInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				converted := make([]interface{}, len(filter.NotIn.Values))
				for i, v := range filter.NotIn.Values {
					converted[i] = DateTimeValue{v}
				}
				qb.AddNotInCondition("updated_date_time", converted)
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: transaction_hash
	if req.TransactionHash != nil {
		switch filter := req.TransactionHash.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("transaction_hash", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("transaction_hash", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("transaction_hash", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("transaction_hash", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("transaction_hash", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("transaction_hash", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("transaction_hash", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("transaction_hash", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("transaction_hash", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: transaction_index
	if req.TransactionIndex != nil {
		switch filter := req.TransactionIndex.Filter.(type) {
		case *UInt32Filter_Eq:
			qb.AddCondition("transaction_index", "=", filter.Eq)
		case *UInt32Filter_Ne:
			qb.AddCondition("transaction_index", "!=", filter.Ne)
		case *UInt32Filter_Lt:
			qb.AddCondition("transaction_index", "<", filter.Lt)
		case *UInt32Filter_Lte:
			qb.AddCondition("transaction_index", "<=", filter.Lte)
		case *UInt32Filter_Gt:
			qb.AddCondition("transaction_index", ">", filter.Gt)
		case *UInt32Filter_Gte:
			qb.AddCondition("transaction_index", ">=", filter.Gte)
		case *UInt32Filter_Between:
			qb.AddBetweenCondition("transaction_index", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt32Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("transaction_index", UInt32SliceToInterface(filter.In.Values))
			}
		case *UInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("transaction_index", UInt32SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: internal_index
	if req.InternalIndex != nil {
		switch filter := req.InternalIndex.Filter.(type) {
		case *UInt32Filter_Eq:
			qb.AddCondition("internal_index", "=", filter.Eq)
		case *UInt32Filter_Ne:
			qb.AddCondition("internal_index", "!=", filter.Ne)
		case *UInt32Filter_Lt:
			qb.AddCondition("internal_index", "<", filter.Lt)
		case *UInt32Filter_Lte:
			qb.AddCondition("internal_index", "<=", filter.Lte)
		case *UInt32Filter_Gt:
			qb.AddCondition("internal_index", ">", filter.Gt)
		case *UInt32Filter_Gte:
			qb.AddCondition("internal_index", ">=", filter.Gte)
		case *UInt32Filter_Between:
			qb.AddBetweenCondition("internal_index", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt32Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("internal_index", UInt32SliceToInterface(filter.In.Values))
			}
		case *UInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("internal_index", UInt32SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: address
	if req.Address != nil {
		switch filter := req.Address.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("address", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("address", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("address", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("address", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("address", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("address", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("address", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("address", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("address", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: beneficiary
	if req.Beneficiary != nil {
		switch filter := req.Beneficiary.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("beneficiary", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("beneficiary", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("beneficiary", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("beneficiary", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("beneficiary", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("beneficiary", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("beneficiary", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("beneficiary", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("beneficiary", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: value_transferred
	if req.ValueTransferred != nil {
		switch filter := req.ValueTransferred.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("value_transferred", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("value_transferred", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("value_transferred", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("value_transferred", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("value_transferred", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("value_transferred", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("value_transferred", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("value_transferred", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("value_transferred", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: ephemeral
	if req.Ephemeral != nil {
		switch filter := req.Ephemeral.Filter.(type) {
		case *BoolFilter_Eq:
			qb.AddCondition("ephemeral", "=", filter.Eq)
		case *BoolFilter_Ne:
			qb.AddCondition("ephemeral", "!=", filter.Ne)
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: storage_cleared
	if req.StorageCleared != nil {
		switch filter := req.StorageCleared.Filter.(type) {
		case *BoolFilter_Eq:
			qb.AddCondition("storage_cleared", "=", filter.Eq)
		case *BoolFilter_Ne:
			qb.AddCondition("storage_cleared", "!=", filter.Ne)
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: creation_block
	if req.CreationBlock != nil {
		switch filter := req.CreationBlock.Filter.(type) {
		case *NullableUInt32Filter_Eq:
			qb.AddCondition("creation_block", "=", filter.Eq)
		case *NullableUInt32Filter_Ne:
			qb.AddCondition("creation_block", "!=", filter.Ne)
		case *NullableUInt32Filter_Lt:
			qb.AddCondition("creation_block", "<", filter.Lt)
		case *NullableUInt32Filter_Lte:
			qb.AddCondition("creation_block", "<=", filter.Lte)
		case *NullableUInt32Filter_Gt:
			qb.AddCondition("creation_block", ">", filter.Gt)
		case *NullableUInt32Filter_Gte:
			qb.AddCondition("creation_block", ">=", filter.Gte)
		case *NullableUInt32Filter_Between:
			qb.AddBetweenCondition("creation_block", filter.Between.Min, filter.Between.Max.GetValue())
		case *NullableUInt32Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("creation_block", UInt32SliceToInterface(filter.In.Values))
			}
		case *NullableUInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("creation_block", UInt32SliceToInterface(filter.NotIn.Values))
			}
		case *NullableUInt32Filter_IsNull:
			qb.AddIsNullCondition("creation_block")
		case *NullableUInt32Filter_IsNotNull:
			qb.AddIsNotNullCondition("creation_block")
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: creation_transaction_hash
	if req.CreationTransactionHash != nil {
		switch filter := req.CreationTransactionHash.Filter.(type) {
		case *NullableStringFilter_Eq:
			qb.AddCondition("creation_transaction_hash", "=", filter.Eq)
		case *NullableStringFilter_Ne:
			qb.AddCondition("creation_transaction_hash", "!=", filter.Ne)
		case *NullableStringFilter_Contains:
			qb.AddLikeCondition("creation_transaction_hash", "%" + filter.Contains + "%")
		case *NullableStringFilter_StartsWith:
			qb.AddLikeCondition("creation_transaction_hash", filter.StartsWith + "%")
		case *NullableStringFilter_EndsWith:
			qb.AddLikeCondition("creation_transaction_hash", "%" + filter.EndsWith)
		case *NullableStringFilter_Like:
			qb.AddLikeCondition("creation_transaction_hash", filter.Like)
		case *NullableStringFilter_NotLike:
			qb.AddNotLikeCondition("creation_transaction_hash", filter.NotLike)
		case *NullableStringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("creation_transaction_hash", StringSliceToInterface(filter.In.Values))
			}
		case *NullableStringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("creation_transaction_hash", StringSliceToInterface(filter.NotIn.Values))
			}
		case *NullableStringFilter_IsNull:
			qb.AddIsNullCondition("creation_transaction_hash")
		case *NullableStringFilter_IsNotNull:
			qb.AddIsNotNullCondition("creation_transaction_hash")
		default:
			// Unsupported filter type
		}
	}

	// Handle pagination per AIP-132
	// Validate page size
	if req.PageSize < 0 {
		return SQLQuery{}, fmt.Errorf("page_size must be non-negative, got %d", req.PageSize)
	}
	if req.PageSize > 10000 {
		return SQLQuery{}, fmt.Errorf("page_size must not exceed %d, got %d", 10000, req.PageSize)
	}

	var limit, offset uint32
	limit = 100 // Default page size
	if req.PageSize > 0 {
		limit = uint32(req.PageSize)
	}
	if req.PageToken != "" {
		decodedOffset, err := DecodePageToken(req.PageToken)
		if err != nil {
			return SQLQuery{}, fmt.Errorf("invalid page_token: %w", err)
		}
		offset = decodedOffset
	}

	// Handle custom ordering if provided
	var orderByClause string
	if req.OrderBy != "" {
		validFields := []string{"updated_date_time", "block_number", "transaction_hash", "transaction_index", "internal_index", "address", "beneficiary", "value_transferred", "ephemeral", "storage_cleared", "creation_block", "creation_transaction_hash"}
		orderFields, err := ParseOrderBy(req.OrderBy, validFields)
		if err != nil {
			return SQLQuery{}, fmt.Errorf("invalid order_by: %w", err)
		}
		orderByClause = BuildOrderByClause(orderFields)
	} else {
		// Default sorting by primary key
		orderByClause = " ORDER BY block_number" + ", transaction_index" + ", internal_index" + ", address"
	}

	// Build column list
	columns := []string{"toUnixTimestamp(`updated_date_time`) AS `updated_date_time`", "block_number", "transaction_hash", "toUInt32(`transaction_index`) AS `transaction_index`", "internal_index", "address", "beneficiary", "toString(`value_transferred`) AS `value_transferred`", "ephemeral", "storage_cleared", "creation_block", "creation_transaction_hash"}

	return BuildParameterizedQuery("int_contract_selfdestruct", columns, qb, orderByClause, limit, offset, options...)
}

// BuildGetIntContractSelfdestructQuery constructs a parameterized SQL query from a GetIntContractSelfdestructRequest
func BuildGetIntContractSelfdestructQuery(req *GetIntContractSelfdestructRequest, options ...QueryOption) (SQLQuery, error) {
	// Validate primary key is provided
	if req.BlockNumber == 0 {
		return SQLQuery{}, fmt.Errorf("primary key field block_number is required")
	}

	// Build query with primary key condition
	qb := NewQueryBuilder()
	qb.AddCondition("block_number", "=", req.BlockNumber)

	// Build ORDER BY clause
	orderByClause := " ORDER BY block_number, transaction_index, internal_index, address"

	// Build column list
	columns := []string{"toUnixTimestamp(`updated_date_time`) AS `updated_date_time`", "block_number", "transaction_hash", "toUInt32(`transaction_index`) AS `transaction_index`", "internal_index", "address", "beneficiary", "toString(`value_transferred`) AS `value_transferred`", "ephemeral", "storage_cleared", "creation_block", "creation_transaction_hash"}

	// Return single record
	return BuildParameterizedQuery("int_contract_selfdestruct", columns, qb, orderByClause, 1, 0, options...)
}
