// Code generated by clickhouse-proto-gen. DO NOT EDIT.
// SQL query builder for int_transaction_call_frame

package clickhouse

import (
	"fmt"
)

// BuildListIntTransactionCallFrameQuery constructs a parameterized SQL query from a ListIntTransactionCallFrameRequest
//
// Available projections:
//   - p_by_transaction (primary key: transaction_hash)
//
// Use WithProjection() option to select a specific projection.
func BuildListIntTransactionCallFrameQuery(req *ListIntTransactionCallFrameRequest, options ...QueryOption) (SQLQuery, error) {
	// Validate that at least one primary key is provided
	// Primary keys can come from base table or projections
	if req.BlockNumber == nil && req.TransactionHash == nil {
		return SQLQuery{}, fmt.Errorf("at least one primary key field is required: block_number, transaction_hash")
	}

	// Build query using QueryBuilder
	qb := NewQueryBuilder()

	// Add primary key filter
	if req.BlockNumber != nil {
		switch filter := req.BlockNumber.Filter.(type) {
		case *UInt64Filter_Eq:
			qb.AddCondition("block_number", "=", filter.Eq)
		case *UInt64Filter_Ne:
			qb.AddCondition("block_number", "!=", filter.Ne)
		case *UInt64Filter_Lt:
			qb.AddCondition("block_number", "<", filter.Lt)
		case *UInt64Filter_Lte:
			qb.AddCondition("block_number", "<=", filter.Lte)
		case *UInt64Filter_Gt:
			qb.AddCondition("block_number", ">", filter.Gt)
		case *UInt64Filter_Gte:
			qb.AddCondition("block_number", ">=", filter.Gte)
		case *UInt64Filter_Between:
			qb.AddBetweenCondition("block_number", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt64Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("block_number", UInt64SliceToInterface(filter.In.Values))
			}
		case *UInt64Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("block_number", UInt64SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: updated_date_time
	if req.UpdatedDateTime != nil {
		switch filter := req.UpdatedDateTime.Filter.(type) {
		case *UInt32Filter_Eq:
			qb.AddCondition("updated_date_time", "=", DateTimeValue{filter.Eq})
		case *UInt32Filter_Ne:
			qb.AddCondition("updated_date_time", "!=", DateTimeValue{filter.Ne})
		case *UInt32Filter_Lt:
			qb.AddCondition("updated_date_time", "<", DateTimeValue{filter.Lt})
		case *UInt32Filter_Lte:
			qb.AddCondition("updated_date_time", "<=", DateTimeValue{filter.Lte})
		case *UInt32Filter_Gt:
			qb.AddCondition("updated_date_time", ">", DateTimeValue{filter.Gt})
		case *UInt32Filter_Gte:
			qb.AddCondition("updated_date_time", ">=", DateTimeValue{filter.Gte})
		case *UInt32Filter_Between:
			qb.AddBetweenCondition("updated_date_time", DateTimeValue{filter.Between.Min}, DateTimeValue{filter.Between.Max.GetValue()})
		case *UInt32Filter_In:
			if len(filter.In.Values) > 0 {
				converted := make([]interface{}, len(filter.In.Values))
				for i, v := range filter.In.Values {
					converted[i] = DateTimeValue{v}
				}
				qb.AddInCondition("updated_date_time", converted)
			}
		case *UInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				converted := make([]interface{}, len(filter.NotIn.Values))
				for i, v := range filter.NotIn.Values {
					converted[i] = DateTimeValue{v}
				}
				qb.AddNotInCondition("updated_date_time", converted)
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: transaction_hash
	if req.TransactionHash != nil {
		switch filter := req.TransactionHash.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("transaction_hash", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("transaction_hash", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("transaction_hash", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("transaction_hash", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("transaction_hash", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("transaction_hash", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("transaction_hash", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("transaction_hash", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("transaction_hash", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: transaction_index
	if req.TransactionIndex != nil {
		switch filter := req.TransactionIndex.Filter.(type) {
		case *UInt32Filter_Eq:
			qb.AddCondition("transaction_index", "=", filter.Eq)
		case *UInt32Filter_Ne:
			qb.AddCondition("transaction_index", "!=", filter.Ne)
		case *UInt32Filter_Lt:
			qb.AddCondition("transaction_index", "<", filter.Lt)
		case *UInt32Filter_Lte:
			qb.AddCondition("transaction_index", "<=", filter.Lte)
		case *UInt32Filter_Gt:
			qb.AddCondition("transaction_index", ">", filter.Gt)
		case *UInt32Filter_Gte:
			qb.AddCondition("transaction_index", ">=", filter.Gte)
		case *UInt32Filter_Between:
			qb.AddBetweenCondition("transaction_index", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt32Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("transaction_index", UInt32SliceToInterface(filter.In.Values))
			}
		case *UInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("transaction_index", UInt32SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: call_frame_id
	if req.CallFrameId != nil {
		switch filter := req.CallFrameId.Filter.(type) {
		case *UInt32Filter_Eq:
			qb.AddCondition("call_frame_id", "=", filter.Eq)
		case *UInt32Filter_Ne:
			qb.AddCondition("call_frame_id", "!=", filter.Ne)
		case *UInt32Filter_Lt:
			qb.AddCondition("call_frame_id", "<", filter.Lt)
		case *UInt32Filter_Lte:
			qb.AddCondition("call_frame_id", "<=", filter.Lte)
		case *UInt32Filter_Gt:
			qb.AddCondition("call_frame_id", ">", filter.Gt)
		case *UInt32Filter_Gte:
			qb.AddCondition("call_frame_id", ">=", filter.Gte)
		case *UInt32Filter_Between:
			qb.AddBetweenCondition("call_frame_id", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt32Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("call_frame_id", UInt32SliceToInterface(filter.In.Values))
			}
		case *UInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("call_frame_id", UInt32SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: parent_call_frame_id
	if req.ParentCallFrameId != nil {
		switch filter := req.ParentCallFrameId.Filter.(type) {
		case *NullableUInt32Filter_Eq:
			qb.AddCondition("parent_call_frame_id", "=", filter.Eq)
		case *NullableUInt32Filter_Ne:
			qb.AddCondition("parent_call_frame_id", "!=", filter.Ne)
		case *NullableUInt32Filter_Lt:
			qb.AddCondition("parent_call_frame_id", "<", filter.Lt)
		case *NullableUInt32Filter_Lte:
			qb.AddCondition("parent_call_frame_id", "<=", filter.Lte)
		case *NullableUInt32Filter_Gt:
			qb.AddCondition("parent_call_frame_id", ">", filter.Gt)
		case *NullableUInt32Filter_Gte:
			qb.AddCondition("parent_call_frame_id", ">=", filter.Gte)
		case *NullableUInt32Filter_Between:
			qb.AddBetweenCondition("parent_call_frame_id", filter.Between.Min, filter.Between.Max.GetValue())
		case *NullableUInt32Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("parent_call_frame_id", UInt32SliceToInterface(filter.In.Values))
			}
		case *NullableUInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("parent_call_frame_id", UInt32SliceToInterface(filter.NotIn.Values))
			}
		case *NullableUInt32Filter_IsNull:
			qb.AddIsNullCondition("parent_call_frame_id")
		case *NullableUInt32Filter_IsNotNull:
			qb.AddIsNotNullCondition("parent_call_frame_id")
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: depth
	if req.Depth != nil {
		switch filter := req.Depth.Filter.(type) {
		case *UInt32Filter_Eq:
			qb.AddCondition("depth", "=", filter.Eq)
		case *UInt32Filter_Ne:
			qb.AddCondition("depth", "!=", filter.Ne)
		case *UInt32Filter_Lt:
			qb.AddCondition("depth", "<", filter.Lt)
		case *UInt32Filter_Lte:
			qb.AddCondition("depth", "<=", filter.Lte)
		case *UInt32Filter_Gt:
			qb.AddCondition("depth", ">", filter.Gt)
		case *UInt32Filter_Gte:
			qb.AddCondition("depth", ">=", filter.Gte)
		case *UInt32Filter_Between:
			qb.AddBetweenCondition("depth", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt32Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("depth", UInt32SliceToInterface(filter.In.Values))
			}
		case *UInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("depth", UInt32SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: target_address
	if req.TargetAddress != nil {
		switch filter := req.TargetAddress.Filter.(type) {
		case *NullableStringFilter_Eq:
			qb.AddCondition("target_address", "=", filter.Eq)
		case *NullableStringFilter_Ne:
			qb.AddCondition("target_address", "!=", filter.Ne)
		case *NullableStringFilter_Contains:
			qb.AddLikeCondition("target_address", "%" + filter.Contains + "%")
		case *NullableStringFilter_StartsWith:
			qb.AddLikeCondition("target_address", filter.StartsWith + "%")
		case *NullableStringFilter_EndsWith:
			qb.AddLikeCondition("target_address", "%" + filter.EndsWith)
		case *NullableStringFilter_Like:
			qb.AddLikeCondition("target_address", filter.Like)
		case *NullableStringFilter_NotLike:
			qb.AddNotLikeCondition("target_address", filter.NotLike)
		case *NullableStringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("target_address", StringSliceToInterface(filter.In.Values))
			}
		case *NullableStringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("target_address", StringSliceToInterface(filter.NotIn.Values))
			}
		case *NullableStringFilter_IsNull:
			qb.AddIsNullCondition("target_address")
		case *NullableStringFilter_IsNotNull:
			qb.AddIsNotNullCondition("target_address")
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: call_type
	if req.CallType != nil {
		switch filter := req.CallType.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("call_type", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("call_type", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("call_type", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("call_type", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("call_type", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("call_type", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("call_type", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("call_type", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("call_type", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: function_selector
	if req.FunctionSelector != nil {
		switch filter := req.FunctionSelector.Filter.(type) {
		case *NullableStringFilter_Eq:
			qb.AddCondition("function_selector", "=", filter.Eq)
		case *NullableStringFilter_Ne:
			qb.AddCondition("function_selector", "!=", filter.Ne)
		case *NullableStringFilter_Contains:
			qb.AddLikeCondition("function_selector", "%" + filter.Contains + "%")
		case *NullableStringFilter_StartsWith:
			qb.AddLikeCondition("function_selector", filter.StartsWith + "%")
		case *NullableStringFilter_EndsWith:
			qb.AddLikeCondition("function_selector", "%" + filter.EndsWith)
		case *NullableStringFilter_Like:
			qb.AddLikeCondition("function_selector", filter.Like)
		case *NullableStringFilter_NotLike:
			qb.AddNotLikeCondition("function_selector", filter.NotLike)
		case *NullableStringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("function_selector", StringSliceToInterface(filter.In.Values))
			}
		case *NullableStringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("function_selector", StringSliceToInterface(filter.NotIn.Values))
			}
		case *NullableStringFilter_IsNull:
			qb.AddIsNullCondition("function_selector")
		case *NullableStringFilter_IsNotNull:
			qb.AddIsNotNullCondition("function_selector")
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: opcode_count
	if req.OpcodeCount != nil {
		switch filter := req.OpcodeCount.Filter.(type) {
		case *UInt64Filter_Eq:
			qb.AddCondition("opcode_count", "=", filter.Eq)
		case *UInt64Filter_Ne:
			qb.AddCondition("opcode_count", "!=", filter.Ne)
		case *UInt64Filter_Lt:
			qb.AddCondition("opcode_count", "<", filter.Lt)
		case *UInt64Filter_Lte:
			qb.AddCondition("opcode_count", "<=", filter.Lte)
		case *UInt64Filter_Gt:
			qb.AddCondition("opcode_count", ">", filter.Gt)
		case *UInt64Filter_Gte:
			qb.AddCondition("opcode_count", ">=", filter.Gte)
		case *UInt64Filter_Between:
			qb.AddBetweenCondition("opcode_count", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt64Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("opcode_count", UInt64SliceToInterface(filter.In.Values))
			}
		case *UInt64Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("opcode_count", UInt64SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: error_count
	if req.ErrorCount != nil {
		switch filter := req.ErrorCount.Filter.(type) {
		case *UInt64Filter_Eq:
			qb.AddCondition("error_count", "=", filter.Eq)
		case *UInt64Filter_Ne:
			qb.AddCondition("error_count", "!=", filter.Ne)
		case *UInt64Filter_Lt:
			qb.AddCondition("error_count", "<", filter.Lt)
		case *UInt64Filter_Lte:
			qb.AddCondition("error_count", "<=", filter.Lte)
		case *UInt64Filter_Gt:
			qb.AddCondition("error_count", ">", filter.Gt)
		case *UInt64Filter_Gte:
			qb.AddCondition("error_count", ">=", filter.Gte)
		case *UInt64Filter_Between:
			qb.AddBetweenCondition("error_count", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt64Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("error_count", UInt64SliceToInterface(filter.In.Values))
			}
		case *UInt64Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("error_count", UInt64SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: gas
	if req.Gas != nil {
		switch filter := req.Gas.Filter.(type) {
		case *UInt64Filter_Eq:
			qb.AddCondition("gas", "=", filter.Eq)
		case *UInt64Filter_Ne:
			qb.AddCondition("gas", "!=", filter.Ne)
		case *UInt64Filter_Lt:
			qb.AddCondition("gas", "<", filter.Lt)
		case *UInt64Filter_Lte:
			qb.AddCondition("gas", "<=", filter.Lte)
		case *UInt64Filter_Gt:
			qb.AddCondition("gas", ">", filter.Gt)
		case *UInt64Filter_Gte:
			qb.AddCondition("gas", ">=", filter.Gte)
		case *UInt64Filter_Between:
			qb.AddBetweenCondition("gas", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt64Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("gas", UInt64SliceToInterface(filter.In.Values))
			}
		case *UInt64Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("gas", UInt64SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: gas_cumulative
	if req.GasCumulative != nil {
		switch filter := req.GasCumulative.Filter.(type) {
		case *UInt64Filter_Eq:
			qb.AddCondition("gas_cumulative", "=", filter.Eq)
		case *UInt64Filter_Ne:
			qb.AddCondition("gas_cumulative", "!=", filter.Ne)
		case *UInt64Filter_Lt:
			qb.AddCondition("gas_cumulative", "<", filter.Lt)
		case *UInt64Filter_Lte:
			qb.AddCondition("gas_cumulative", "<=", filter.Lte)
		case *UInt64Filter_Gt:
			qb.AddCondition("gas_cumulative", ">", filter.Gt)
		case *UInt64Filter_Gte:
			qb.AddCondition("gas_cumulative", ">=", filter.Gte)
		case *UInt64Filter_Between:
			qb.AddBetweenCondition("gas_cumulative", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt64Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("gas_cumulative", UInt64SliceToInterface(filter.In.Values))
			}
		case *UInt64Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("gas_cumulative", UInt64SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: gas_refund
	if req.GasRefund != nil {
		switch filter := req.GasRefund.Filter.(type) {
		case *NullableUInt64Filter_Eq:
			qb.AddCondition("gas_refund", "=", filter.Eq)
		case *NullableUInt64Filter_Ne:
			qb.AddCondition("gas_refund", "!=", filter.Ne)
		case *NullableUInt64Filter_Lt:
			qb.AddCondition("gas_refund", "<", filter.Lt)
		case *NullableUInt64Filter_Lte:
			qb.AddCondition("gas_refund", "<=", filter.Lte)
		case *NullableUInt64Filter_Gt:
			qb.AddCondition("gas_refund", ">", filter.Gt)
		case *NullableUInt64Filter_Gte:
			qb.AddCondition("gas_refund", ">=", filter.Gte)
		case *NullableUInt64Filter_Between:
			qb.AddBetweenCondition("gas_refund", filter.Between.Min, filter.Between.Max.GetValue())
		case *NullableUInt64Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("gas_refund", UInt64SliceToInterface(filter.In.Values))
			}
		case *NullableUInt64Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("gas_refund", UInt64SliceToInterface(filter.NotIn.Values))
			}
		case *NullableUInt64Filter_IsNull:
			qb.AddIsNullCondition("gas_refund")
		case *NullableUInt64Filter_IsNotNull:
			qb.AddIsNotNullCondition("gas_refund")
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: intrinsic_gas
	if req.IntrinsicGas != nil {
		switch filter := req.IntrinsicGas.Filter.(type) {
		case *NullableUInt64Filter_Eq:
			qb.AddCondition("intrinsic_gas", "=", filter.Eq)
		case *NullableUInt64Filter_Ne:
			qb.AddCondition("intrinsic_gas", "!=", filter.Ne)
		case *NullableUInt64Filter_Lt:
			qb.AddCondition("intrinsic_gas", "<", filter.Lt)
		case *NullableUInt64Filter_Lte:
			qb.AddCondition("intrinsic_gas", "<=", filter.Lte)
		case *NullableUInt64Filter_Gt:
			qb.AddCondition("intrinsic_gas", ">", filter.Gt)
		case *NullableUInt64Filter_Gte:
			qb.AddCondition("intrinsic_gas", ">=", filter.Gte)
		case *NullableUInt64Filter_Between:
			qb.AddBetweenCondition("intrinsic_gas", filter.Between.Min, filter.Between.Max.GetValue())
		case *NullableUInt64Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("intrinsic_gas", UInt64SliceToInterface(filter.In.Values))
			}
		case *NullableUInt64Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("intrinsic_gas", UInt64SliceToInterface(filter.NotIn.Values))
			}
		case *NullableUInt64Filter_IsNull:
			qb.AddIsNullCondition("intrinsic_gas")
		case *NullableUInt64Filter_IsNotNull:
			qb.AddIsNotNullCondition("intrinsic_gas")
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: receipt_gas_used
	if req.ReceiptGasUsed != nil {
		switch filter := req.ReceiptGasUsed.Filter.(type) {
		case *NullableUInt64Filter_Eq:
			qb.AddCondition("receipt_gas_used", "=", filter.Eq)
		case *NullableUInt64Filter_Ne:
			qb.AddCondition("receipt_gas_used", "!=", filter.Ne)
		case *NullableUInt64Filter_Lt:
			qb.AddCondition("receipt_gas_used", "<", filter.Lt)
		case *NullableUInt64Filter_Lte:
			qb.AddCondition("receipt_gas_used", "<=", filter.Lte)
		case *NullableUInt64Filter_Gt:
			qb.AddCondition("receipt_gas_used", ">", filter.Gt)
		case *NullableUInt64Filter_Gte:
			qb.AddCondition("receipt_gas_used", ">=", filter.Gte)
		case *NullableUInt64Filter_Between:
			qb.AddBetweenCondition("receipt_gas_used", filter.Between.Min, filter.Between.Max.GetValue())
		case *NullableUInt64Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("receipt_gas_used", UInt64SliceToInterface(filter.In.Values))
			}
		case *NullableUInt64Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("receipt_gas_used", UInt64SliceToInterface(filter.NotIn.Values))
			}
		case *NullableUInt64Filter_IsNull:
			qb.AddIsNullCondition("receipt_gas_used")
		case *NullableUInt64Filter_IsNotNull:
			qb.AddIsNotNullCondition("receipt_gas_used")
		default:
			// Unsupported filter type
		}
	}

	// Handle pagination per AIP-132
	// Validate page size
	if req.PageSize < 0 {
		return SQLQuery{}, fmt.Errorf("page_size must be non-negative, got %d", req.PageSize)
	}
	if req.PageSize > 10000 {
		return SQLQuery{}, fmt.Errorf("page_size must not exceed %d, got %d", 10000, req.PageSize)
	}

	var limit, offset uint32
	limit = 100 // Default page size
	if req.PageSize > 0 {
		limit = uint32(req.PageSize)
	}
	if req.PageToken != "" {
		decodedOffset, err := DecodePageToken(req.PageToken)
		if err != nil {
			return SQLQuery{}, fmt.Errorf("invalid page_token: %w", err)
		}
		offset = decodedOffset
	}

	// Handle custom ordering if provided
	var orderByClause string
	if req.OrderBy != "" {
		validFields := []string{"updated_date_time", "block_number", "transaction_hash", "transaction_index", "call_frame_id", "parent_call_frame_id", "depth", "target_address", "call_type", "function_selector", "opcode_count", "error_count", "gas", "gas_cumulative", "gas_refund", "intrinsic_gas", "receipt_gas_used"}
		orderFields, err := ParseOrderBy(req.OrderBy, validFields)
		if err != nil {
			return SQLQuery{}, fmt.Errorf("invalid order_by: %w", err)
		}
		orderByClause = BuildOrderByClause(orderFields)
	} else {
		// Default sorting by primary key
		orderByClause = " ORDER BY block_number" + ", transaction_hash" + ", call_frame_id"
	}

	// Build column list
	columns := []string{"toUnixTimestamp(`updated_date_time`) AS `updated_date_time`", "block_number", "NULLIF(`transaction_hash`, repeat('\x00', 66)) AS `transaction_hash`", "transaction_index", "call_frame_id", "parent_call_frame_id", "depth", "target_address", "call_type", "function_selector", "opcode_count", "error_count", "gas", "gas_cumulative", "gas_refund", "intrinsic_gas", "receipt_gas_used"}

	return BuildParameterizedQuery("int_transaction_call_frame", columns, qb, orderByClause, limit, offset, options...)
}

// BuildGetIntTransactionCallFrameQuery constructs a parameterized SQL query from a GetIntTransactionCallFrameRequest
func BuildGetIntTransactionCallFrameQuery(req *GetIntTransactionCallFrameRequest, options ...QueryOption) (SQLQuery, error) {
	// Validate primary key is provided
	if req.BlockNumber == 0 {
		return SQLQuery{}, fmt.Errorf("primary key field block_number is required")
	}

	// Build query with primary key condition
	qb := NewQueryBuilder()
	qb.AddCondition("block_number", "=", req.BlockNumber)

	// Build ORDER BY clause
	orderByClause := " ORDER BY block_number, transaction_hash, call_frame_id"

	// Build column list
	columns := []string{"toUnixTimestamp(`updated_date_time`) AS `updated_date_time`", "block_number", "NULLIF(`transaction_hash`, repeat('\x00', 66)) AS `transaction_hash`", "transaction_index", "call_frame_id", "parent_call_frame_id", "depth", "target_address", "call_type", "function_selector", "opcode_count", "error_count", "gas", "gas_cumulative", "gas_refund", "intrinsic_gas", "receipt_gas_used"}

	// Return single record
	return BuildParameterizedQuery("int_transaction_call_frame", columns, qb, orderByClause, 1, 0, options...)
}
