// Code generated by clickhouse-proto-gen. DO NOT EDIT.
// Scannable result row for int_beacon_committee_head

package clickhouse

// IntBeaconCommitteeHeadRow is a ClickHouse-scannable result row for the int_beacon_committee_head table.
// Field types match the SELECT column expressions produced by
// BuildListIntBeaconCommitteeHeadQuery and BuildGetIntBeaconCommitteeHeadQuery: DateTime columns are unix
// timestamps, DateTime64 columns are unix microseconds, Date and large
// integer and decimal columns are strings, and FixedString columns are
// nullable. Scan rows with clickhouse-go's ScanStruct.
type IntBeaconCommitteeHeadRow struct {
	UpdatedDateTime uint32 `ch:"updated_date_time" json:"updated_date_time"`
	Slot uint32 `ch:"slot" json:"slot"`
	SlotStartDateTime uint32 `ch:"slot_start_date_time" json:"slot_start_date_time"`
	Epoch uint32 `ch:"epoch" json:"epoch"`
	EpochStartDateTime uint32 `ch:"epoch_start_date_time" json:"epoch_start_date_time"`
	CommitteeIndex string `ch:"committee_index" json:"committee_index"`
	Validators []uint32 `ch:"validators" json:"validators"`
}

// TableName returns the ClickHouse table this row maps to.
func (IntBeaconCommitteeHeadRow) TableName() string {
	return "int_beacon_committee_head"
}

// ToProto converts the row to its protobuf message.
func (r *IntBeaconCommitteeHeadRow) ToProto() *IntBeaconCommitteeHead {
	p := &IntBeaconCommitteeHead{}

	p.UpdatedDateTime = r.UpdatedDateTime
	p.Slot = r.Slot
	p.SlotStartDateTime = r.SlotStartDateTime
	p.Epoch = r.Epoch
	p.EpochStartDateTime = r.EpochStartDateTime
	p.CommitteeIndex = r.CommitteeIndex
	p.Validators = r.Validators
	return p
}
