// Code generated by clickhouse-proto-gen. DO NOT EDIT.
// Scannable result row for int_contract_storage_expiry_12m

package clickhouse

// IntContractStorageExpiry12MRow is a ClickHouse-scannable result row for the int_contract_storage_expiry_12m table.
// Field types match the SELECT column expressions produced by
// BuildListIntContractStorageExpiry12MQuery and BuildGetIntContractStorageExpiry12MQuery: DateTime columns are unix
// timestamps, DateTime64 columns are unix microseconds, Date and large
// integer and decimal columns are strings, and FixedString columns are
// nullable. Scan rows with clickhouse-go's ScanStruct.
type IntContractStorageExpiry12MRow struct {
	UpdatedDateTime uint32 `ch:"updated_date_time" json:"updated_date_time"`
	BlockNumber uint32 `ch:"block_number" json:"block_number"`
	Address string `ch:"address" json:"address"`
	TouchBlock uint32 `ch:"touch_block" json:"touch_block"`
	ActiveSlots uint64 `ch:"active_slots" json:"active_slots"`
	EffectiveBytes uint64 `ch:"effective_bytes" json:"effective_bytes"`
}

// TableName returns the ClickHouse table this row maps to.
func (IntContractStorageExpiry12MRow) TableName() string {
	return "int_contract_storage_expiry_12m"
}

// ToProto converts the row to its protobuf message.
func (r *IntContractStorageExpiry12MRow) ToProto() *IntContractStorageExpiry12M {
	p := &IntContractStorageExpiry12M{}

	p.UpdatedDateTime = r.UpdatedDateTime
	p.BlockNumber = r.BlockNumber
	p.Address = r.Address
	p.TouchBlock = r.TouchBlock
	p.ActiveSlots = r.ActiveSlots
	p.EffectiveBytes = r.EffectiveBytes
	return p
}
