// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: int_addresses_first_access.proto

package clickhouse

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IntAddressesFirstAccess struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The address of the account
	Address string `protobuf:"bytes,11,opt,name=address,proto3" json:"address,omitempty"`
	// The block number of the first access
	BlockNumber uint32 `protobuf:"varint,12,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	// Version for this address, for internal use in clickhouse to keep first access
	Version uint32 `protobuf:"varint,13,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *IntAddressesFirstAccess) Reset() {
	*x = IntAddressesFirstAccess{}
	if protoimpl.UnsafeEnabled {
		mi := &file_int_addresses_first_access_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IntAddressesFirstAccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntAddressesFirstAccess) ProtoMessage() {}

func (x *IntAddressesFirstAccess) ProtoReflect() protoreflect.Message {
	mi := &file_int_addresses_first_access_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntAddressesFirstAccess.ProtoReflect.Descriptor instead.
func (*IntAddressesFirstAccess) Descriptor() ([]byte, []int) {
	return file_int_addresses_first_access_proto_rawDescGZIP(), []int{0}
}

func (x *IntAddressesFirstAccess) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *IntAddressesFirstAccess) GetBlockNumber() uint32 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *IntAddressesFirstAccess) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

// ListIntAddressesFirstAccessRequest is the request message for listing int_addresses_first_access records
type ListIntAddressesFirstAccessRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Filter by address (PRIMARY KEY - required)
	Address *StringFilter `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// Filter by block_number (optional)
	BlockNumber *UInt32Filter `protobuf:"bytes,2,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	// Filter by version (optional)
	Version *UInt32Filter `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	// The maximum number of int_addresses_first_access to return.
	// If unspecified, at most 100 items will be returned.
	// The maximum value is 1000; values above 1000 will be coerced to 1000.
	PageSize int32 `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// A page token, received from a previous `ListIntAddressesFirstAccess` call.
	// Provide this to retrieve the subsequent page.
	PageToken string `protobuf:"bytes,5,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// The order of results. Format: comma-separated list of fields.
	// Example: "foo,bar" or "foo desc,bar" for descending order on foo.
	// If unspecified, results will be returned in the default order.
	OrderBy string `protobuf:"bytes,6,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
}

func (x *ListIntAddressesFirstAccessRequest) Reset() {
	*x = ListIntAddressesFirstAccessRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_int_addresses_first_access_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListIntAddressesFirstAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIntAddressesFirstAccessRequest) ProtoMessage() {}

func (x *ListIntAddressesFirstAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_int_addresses_first_access_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIntAddressesFirstAccessRequest.ProtoReflect.Descriptor instead.
func (*ListIntAddressesFirstAccessRequest) Descriptor() ([]byte, []int) {
	return file_int_addresses_first_access_proto_rawDescGZIP(), []int{1}
}

func (x *ListIntAddressesFirstAccessRequest) GetAddress() *StringFilter {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *ListIntAddressesFirstAccessRequest) GetBlockNumber() *UInt32Filter {
	if x != nil {
		return x.BlockNumber
	}
	return nil
}

func (x *ListIntAddressesFirstAccessRequest) GetVersion() *UInt32Filter {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *ListIntAddressesFirstAccessRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListIntAddressesFirstAccessRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListIntAddressesFirstAccessRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

// ListIntAddressesFirstAccessResponse is the response message for listing int_addresses_first_access records
type ListIntAddressesFirstAccessResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The list of int_addresses_first_access.
	IntAddressesFirstAccess []*IntAddressesFirstAccess `protobuf:"bytes,1,rep,name=int_addresses_first_access,json=intAddressesFirstAccess,proto3" json:"int_addresses_first_access,omitempty"`
	// A token, which can be sent as `page_token` to retrieve the next page.
	// If this field is omitted, there are no subsequent pages.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
}

func (x *ListIntAddressesFirstAccessResponse) Reset() {
	*x = ListIntAddressesFirstAccessResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_int_addresses_first_access_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListIntAddressesFirstAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIntAddressesFirstAccessResponse) ProtoMessage() {}

func (x *ListIntAddressesFirstAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_int_addresses_first_access_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIntAddressesFirstAccessResponse.ProtoReflect.Descriptor instead.
func (*ListIntAddressesFirstAccessResponse) Descriptor() ([]byte, []int) {
	return file_int_addresses_first_access_proto_rawDescGZIP(), []int{2}
}

func (x *ListIntAddressesFirstAccessResponse) GetIntAddressesFirstAccess() []*IntAddressesFirstAccess {
	if x != nil {
		return x.IntAddressesFirstAccess
	}
	return nil
}

func (x *ListIntAddressesFirstAccessResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// GetIntAddressesFirstAccessRequest is the request message for getting a single int_addresses_first_access record by primary key
type GetIntAddressesFirstAccessRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The address of the account
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"` // Primary key (required)
}

func (x *GetIntAddressesFirstAccessRequest) Reset() {
	*x = GetIntAddressesFirstAccessRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_int_addresses_first_access_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetIntAddressesFirstAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIntAddressesFirstAccessRequest) ProtoMessage() {}

func (x *GetIntAddressesFirstAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_int_addresses_first_access_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIntAddressesFirstAccessRequest.ProtoReflect.Descriptor instead.
func (*GetIntAddressesFirstAccessRequest) Descriptor() ([]byte, []int) {
	return file_int_addresses_first_access_proto_rawDescGZIP(), []int{3}
}

func (x *GetIntAddressesFirstAccessRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// GetIntAddressesFirstAccessResponse is the response message for getting a single int_addresses_first_access record
type GetIntAddressesFirstAccessResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Item *IntAddressesFirstAccess `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
}

func (x *GetIntAddressesFirstAccessResponse) Reset() {
	*x = GetIntAddressesFirstAccessResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_int_addresses_first_access_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetIntAddressesFirstAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIntAddressesFirstAccessResponse) ProtoMessage() {}

func (x *GetIntAddressesFirstAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_int_addresses_first_access_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIntAddressesFirstAccessResponse.ProtoReflect.Descriptor instead.
func (*GetIntAddressesFirstAccessResponse) Descriptor() ([]byte, []int) {
	return file_int_addresses_first_access_proto_rawDescGZIP(), []int{4}
}

func (x *GetIntAddressesFirstAccessResponse) GetItem() *IntAddressesFirstAccess {
	if x != nil {
		return x.Item
	}
	return nil
}

var File_int_addresses_first_access_proto protoreflect.FileDescriptor

var file_int_addresses_first_access_proto_rawDesc = []byte{
	0x0a, 0x20, 0x69, 0x6e, 0x74, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x5f,
	0x66, 0x69, 0x72, 0x73, 0x74, 0x5f, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x03, 0x63, 0x62, 0x74, 0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x70, 0x0a, 0x17, 0x49, 0x6e, 0x74, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x65, 0x73, 0x46, 0x69, 0x72, 0x73, 0x74, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x0b, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x62, 0x6c,
	0x6f, 0x63, 0x6b, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x0b, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x18, 0x0a,
	0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x8b, 0x02, 0x0a, 0x22, 0x4c, 0x69, 0x73, 0x74,
	0x49, 0x6e, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x46, 0x69, 0x72, 0x73,
	0x74, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2b,
	0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x63, 0x62, 0x74, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x46, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x34, 0x0a, 0x0c, 0x62,
	0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x63, 0x62, 0x74, 0x2e, 0x55, 0x49, 0x6e, 0x74, 0x33, 0x32, 0x46, 0x69,
	0x6c, 0x74, 0x65, 0x72, 0x52, 0x0b, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x4e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x12, 0x2b, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x63, 0x62, 0x74, 0x2e, 0x55, 0x49, 0x6e, 0x74, 0x33, 0x32, 0x46,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1b,
	0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x70,
	0x61, 0x67, 0x65, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x70, 0x61, 0x67, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x5f, 0x62, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x42, 0x79, 0x22, 0xa8, 0x01, 0x0a, 0x23, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x6e,
	0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x46, 0x69, 0x72, 0x73, 0x74, 0x41,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x59, 0x0a,
	0x1a, 0x69, 0x6e, 0x74, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x5f, 0x66,
	0x69, 0x72, 0x73, 0x74, 0x5f, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1c, 0x2e, 0x63, 0x62, 0x74, 0x2e, 0x49, 0x6e, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x65, 0x73, 0x46, 0x69, 0x72, 0x73, 0x74, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x52,
	0x17, 0x69, 0x6e, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x46, 0x69, 0x72,
	0x73, 0x74, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x26, 0x0a, 0x0f, 0x6e, 0x65, 0x78, 0x74,
	0x5f, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0d, 0x6e, 0x65, 0x78, 0x74, 0x50, 0x61, 0x67, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x22, 0x3d, 0x0a, 0x21, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x65, 0x73, 0x46, 0x69, 0x72, 0x73, 0x74, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22,
	0x56, 0x0a, 0x22, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x65, 0x73, 0x46, 0x69, 0x72, 0x73, 0x74, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x63, 0x62, 0x74, 0x2e, 0x49, 0x6e, 0x74, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x46, 0x69, 0x72, 0x73, 0x74, 0x41, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x52, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x32, 0xd3, 0x01, 0x0a, 0x1e, 0x49, 0x6e, 0x74, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x46, 0x69, 0x72, 0x73, 0x74, 0x41, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x59, 0x0a, 0x04, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x27, 0x2e, 0x63, 0x62, 0x74, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x6e, 0x74,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x46, 0x69, 0x72, 0x73, 0x74, 0x41, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x63, 0x62,
	0x74, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x6e, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x65, 0x73, 0x46, 0x69, 0x72, 0x73, 0x74, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x56, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x26, 0x2e, 0x63,
	0x62, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x65, 0x73, 0x46, 0x69, 0x72, 0x73, 0x74, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x63, 0x62, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x6e,
	0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x46, 0x69, 0x72, 0x73, 0x74, 0x41,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x36, 0x5a,
	0x34, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x65, 0x74, 0x68, 0x70,
	0x61, 0x6e, 0x64, 0x61, 0x6f, 0x70, 0x73, 0x2f, 0x78, 0x61, 0x74, 0x75, 0x2d, 0x63, 0x62, 0x74,
	0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6c, 0x69, 0x63, 0x6b,
	0x68, 0x6f, 0x75, 0x73, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_int_addresses_first_access_proto_rawDescOnce sync.Once
	file_int_addresses_first_access_proto_rawDescData = file_int_addresses_first_access_proto_rawDesc
)

func file_int_addresses_first_access_proto_rawDescGZIP() []byte {
	file_int_addresses_first_access_proto_rawDescOnce.Do(func() {
		file_int_addresses_first_access_proto_rawDescData = protoimpl.X.CompressGZIP(file_int_addresses_first_access_proto_rawDescData)
	})
	return file_int_addresses_first_access_proto_rawDescData
}

var file_int_addresses_first_access_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_int_addresses_first_access_proto_goTypes = []any{
	(*IntAddressesFirstAccess)(nil),             // 0: cbt.IntAddressesFirstAccess
	(*ListIntAddressesFirstAccessRequest)(nil),  // 1: cbt.ListIntAddressesFirstAccessRequest
	(*ListIntAddressesFirstAccessResponse)(nil), // 2: cbt.ListIntAddressesFirstAccessResponse
	(*GetIntAddressesFirstAccessRequest)(nil),   // 3: cbt.GetIntAddressesFirstAccessRequest
	(*GetIntAddressesFirstAccessResponse)(nil),  // 4: cbt.GetIntAddressesFirstAccessResponse
	(*StringFilter)(nil),                        // 5: cbt.StringFilter
	(*UInt32Filter)(nil),                        // 6: cbt.UInt32Filter
}
var file_int_addresses_first_access_proto_depIdxs = []int32{
	5, // 0: cbt.ListIntAddressesFirstAccessRequest.address:type_name -> cbt.StringFilter
	6, // 1: cbt.ListIntAddressesFirstAccessRequest.block_number:type_name -> cbt.UInt32Filter
	6, // 2: cbt.ListIntAddressesFirstAccessRequest.version:type_name -> cbt.UInt32Filter
	0, // 3: cbt.ListIntAddressesFirstAccessResponse.int_addresses_first_access:type_name -> cbt.IntAddressesFirstAccess
	0, // 4: cbt.GetIntAddressesFirstAccessResponse.item:type_name -> cbt.IntAddressesFirstAccess
	1, // 5: cbt.IntAddressesFirstAccessService.List:input_type -> cbt.ListIntAddressesFirstAccessRequest
	3, // 6: cbt.IntAddressesFirstAccessService.Get:input_type -> cbt.GetIntAddressesFirstAccessRequest
	2, // 7: cbt.IntAddressesFirstAccessService.List:output_type -> cbt.ListIntAddressesFirstAccessResponse
	4, // 8: cbt.IntAddressesFirstAccessService.Get:output_type -> cbt.GetIntAddressesFirstAccessResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_int_addresses_first_access_proto_init() }
func file_int_addresses_first_access_proto_init() {
	if File_int_addresses_first_access_proto != nil {
		return
	}
	file_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_int_addresses_first_access_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*IntAddressesFirstAccess); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_int_addresses_first_access_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ListIntAddressesFirstAccessRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_int_addresses_first_access_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*ListIntAddressesFirstAccessResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_int_addresses_first_access_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*GetIntAddressesFirstAccessRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_int_addresses_first_access_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*GetIntAddressesFirstAccessResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_int_addresses_first_access_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_int_addresses_first_access_proto_goTypes,
		DependencyIndexes: file_int_addresses_first_access_proto_depIdxs,
		MessageInfos:      file_int_addresses_first_access_proto_msgTypes,
	}.Build()
	File_int_addresses_first_access_proto = out.File
	file_int_addresses_first_access_proto_rawDesc = nil
	file_int_addresses_first_access_proto_goTypes = nil
	file_int_addresses_first_access_proto_depIdxs = nil
}
